### ISSUE TITLE
Show installed games on top and other UI improvements

### ISSUE THREAD

**Issue by JonnyCodewalker** [tkashkin/GameHub#102]
Not on the newest Gamehub version, so if some things are already implemented I am sorry.

# Show installed games on top
Because of the way the interface is structured it would greatly improve the user flow if installed games where listed first and non installed games afterwards, separated by a thin separator.

# Category filter
The ability to filter the games based on the categories they are tagged with.

# Custom lists
The ability to create custom folders/lists of games to display (like favourites in steam)

**Comment by tkashkin** [comment]
> Show installed games on top

Implemented for list view. I'll think how to implement it for grid view and should it be done as a new option or non-configurable.
It's also possible to hide not installed games with tags filter.

Speaking of tags filter:
> Category filter

> Custom lists

It's implemented too (#47).

Here's how it looks now:
![image](https://user-images.githubusercontent.com/2003017/47159289-30f5c100-d2f6-11e8-961b-ed105e72e869.png)

There's also game properties dialog. You can add custom tags.
![image](https://user-images.githubusercontent.com/2003017/47159399-787c4d00-d2f6-11e8-9e7c-d289c2084784.png)

**Comment by tkashkin** [comment]
It uses same sorting code for both list and grid views since 8dfd66a.
Exact sorting rules: https://github.com/tkashkin/GameHub/blob/8dfd66a7df840bd932d844cac03ed7bd144abc88/src/ui/views/GamesView/GamesView.vala#L704-L720

**Comment by tkashkin** [comment]
@JonnyCodewalker now games can also be sorted by last launch time.

**Comment by Lucki** [comment]
> Show installed games on top

Can this be optional?
Currently the alphabetical list isn't alphabetical because there's silently another sorting on top.
With the compact view you can't tell if you're in the installed or uninstalled section without clicking a game first or guessing how far you've scrolled.
