### ISSUE TITLE
Support adding custom games using installers

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#106]
Adding some custom games using compatibility options requires to run some executable (e.g. Origin or UPlay installer). This is not properly supported by the 'custom game' options, since it will only force you select the installer as the game executable.

**Comment by tkashkin** [comment]
Are Origin/Uplay games even working in Wine?

It should be possible to add Origin/Uplay itself as a game and install/launch games in prefix.

**Comment by neuromancer** [comment]
> Are Origin/Uplay games even working in Wine?

Yes, most of them. Origin works fine in Wine-stagging and Valve is fixing a lot issues in Proton to run UPlay since it are required for some games (e.g. https://github.com/ValveSoftware/Proton/issues/1735).

> It should be possible to add Origin/Uplay itself as a game and install/launch games in prefix.

You can install them, but the installers are used as 'executable'. If you try to change the executable to use Origin.exe or UPlay.exe, it fails (#105)

**Comment by tkashkin** [comment]
Now you can try to use "custom emulators" for this. https://github.com/tkashkin/GameHub/issues/103#issuecomment-433459660

**Comment by neuromancer** [comment]
I'm not sure how to use "custom emulators" for that, since UPlay and Origin have undocumented launch options... Anyway, changing the path (and directory) works well to manually add UPlay/Origin games since #105 was fixed.

**Comment by tkashkin** [comment]
I was thinking about how to implement it and will try to do that soon.

**Comment by tkashkin** [comment]
Implemented in 7e443e4 and seems to work correctly. Not implemented yet for custom emulators.
Should work the same way as regular game installers and support all already supported installer types. Archives are also supported.

**Comment by neuromancer** [comment]
It works fine!. I tested with a few installer: sometimes the popup to select the binary is triggered too soon. I suspect that certain installers run a program in the background and the control flow returns to GameHub to open the binary selection popup. If you don't care about that, just close this issue.

**Comment by tkashkin** [comment]
Custom emulators now can also be added with installers. It may be a bit buggy and UI may be a bit confusing.

**Comment by tkashkin** [comment]
f4a4847 fixes some bugs for this issue.

It also improves Wine/Proton support:
* Game directory is now mounted in Wine environment as D: drive
* There's button to kill everything in prefix
* Bugfixes

Also it's possible to use Uplay as "custom emulator":
* Install Uplay and setup it:
![image](https://user-images.githubusercontent.com/2003017/47958331-64b13600-dfda-11e8-90fb-8fc9a11ea85f.png)
* Run it, install games somewhere
* Setup games (find game shortcut in Uplay prefix and open it in text editor to get launch URL):
![image](https://user-images.githubusercontent.com/2003017/47958340-a641e100-dfda-11e8-83d3-246b6d6da85f.png)
