### ISSUE TITLE
GOG back ups? 

### ISSUE THREAD

**Issue by turin331** [tkashkin/GameHub#107]
Is there a way that instead of choosing to install a gog game to ask to just download the game files of the version of your choice as a back up without installing? Similar to gog galaxy basically. If not it would be a nice feature.

**Comment by tkashkin** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/2003017/47560784-00c7a700-d922-11e8-83c1-d31c0c6a5aee.png)

**Comment by tkashkin** [comment]
Should be available in 4150ba2. Also it's now possible to open installers/bonus directories from game details and context menu.

**Comment by turin331** [comment]
Damn you are fast...Thank a lot for your work!
