### ISSUE TITLE
Integration with Adamhm's Linux Wine Wrappers

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#108]
I wonder if you could somehow integrate [Adamhm's Linux Wine Wrappers](https://www.gog.com/forum/general/adamhms_linux_wine_wrappers_news_faq_discussion/post1), in particular for games that require the installation of specific components to run (e.g. .NET).

We can also ask [Adamhm](https://www.reddit.com/user/adamhm_), in case he has some suggestions.

**Comment by tkashkin** [comment]
@neuromancer initial integration is implemented. It should work for all games listed in [this gist](https://gist.github.com/tkashkin/10b55144c8bd17f76b5c14d18a658f5f). I'll ask adamhm to upload full wrapper list somewhere and update it when something changes.

**Comment by tkashkin** [comment]
It seems to work fine, reopen if there are any issues.

**Comment by neuromancer** [comment]
I tried a few games (e.g. Outlaws) and it works perfectly! Don't forget to add something in the README about this feature (I think it is not mentioned anywhere).

**Comment by tkashkin** [comment]
@neuromancer 
I have mentioned it at https://tkashkin.tk/projects/gamehub.

I plan to update repo README to have somewhat similar structure as project page has now.
However I'm quite bad at describing things and I have probably forgot to mention something important, so I'll wait for your suggestions.

**Comment by tkashkin** [comment]
@neuromancer I used webp because filesize is significantly less than png. I didn't know that Firefox doesn't support webp. I'll try to do something (maybe using `srcset`).

**Comment by tkashkin** [comment]
@neuromancer 
> Also, tkashkin.tk/projects/gamehub uses webp images for the screenshots, which are not rendered in Firefox. Is it too much trouble to convert them to png?

This and download counters should be fixed for Firefox.

**Comment by neuromancer** [comment]
Yeap, it is working fine. I will create an issue in https://github.com/tkashkin/tkashkin.github.io next time!

**Comment by tkashkin** [comment]
@neuromancer any suggestions about updated README?
