### ISSUE TITLE
List of games in "List" view scrollable too far horizontally

### ISSUE THREAD

**Issue by OctarineSorcerer** [tkashkin/GameHub#109]
When the games view is set to list, that list is scrollable horizontally, to the point that most titles aren't visible if you accidentally scroll to the right too much:
![image](https://user-images.githubusercontent.com/6842867/47615211-25e42300-daa4-11e8-942c-234b3b538eab.png)

It does have a limit, you don't have to scroll too far back to the left to have everything visible again, but that limit is also at the point where no titles in my library stretch that far.

Liking the look of this so far though!

**Comment by tkashkin** [comment]
There was a problem with list headers, I haven't found a way to expand them to fill available width. So headers are at least 1024px wide. See [this](https://github.com/tkashkin/GameHub/blob/dev/src/ui/views/GamesView/GamesView.vala#L268). You should be able to see this if you resize list to be wide enough. I'm not sure what to do with this.
