### ISSUE TITLE
No "Save" button in a game's properties dialog?

### ISSUE THREAD

**Issue by OctarineSorcerer** [tkashkin/GameHub#110]
There appears to be no "save" button in a game's properties dialog, and the only way I've found to close it without Alt-F4ing it is with Escape - but that doesn't save the settings. Is there something I'm missing here?

![image](https://user-images.githubusercontent.com/6842867/47616257-41562a80-dab2-11e8-9049-1ef6407f1251.png)

**Comment by tkashkin** [comment]
Dialog should show standard close button. Your screenshot suggests that GTK theme and/or WM you are using doesn't show close button in dialog header.
But escape should save changes. What changes were not saved exactly?

**Comment by OctarineSorcerer** [comment]
Yes, I'm currently using i3, which doesn't show close buttons. I'm used to that, but as changing the Executable to "start.sh" didn't get saved when I closed it, I assumed that was regular behaviour there should have been something showing which would allow me to save.

I'd installed Cultist Simulator using GameHub, and then there appeared to be no files in the resulting folder. So I installed it manually with the installer, and tried to point GameHub at the executable in the right place. Closed dialog, opened it again, and it was back to thinking the executable was the installer script

**Comment by neuromancer** [comment]
Are you using the latest revision of the `dev` branch? (a similar issue was recently reported and fixed: #105)

**Comment by OctarineSorcerer** [comment]
Ah, I may not be - I'm using the AUR's gamehub-git package, but I believe it's out of date. I'll manually build from source then get back on that

**Comment by OctarineSorcerer** [comment]
It works on the `dev` branch build :) Thank you! Sorry for not seeing the above issue first
