### ISSUE TITLE
Latest dev revision fails to run native games

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#112]
Latest `dev` revision of GameHub (4150ba217a9a93adfa7f106dea18736d8678272c) fails to run native games. It will open the `customscript.sh` file with the default content:

```
#!/bin/bash
GH_EXECUTABLE="$1"
GH_INSTALL_DIR="$2"
GH_GAME_ID="$3"
GH_GAME_ID_FULL="$4"
GH_GAME_NAME="$5"
GH_GAME_NAME_ESCAPED="$6"
```

This will happen despite the `start.sh` script is properly set for a game.

**Comment by tkashkin** [comment]
Doesn't happen for me, maybe duplicate of https://github.com/tkashkin/GameHub/issues/99#issuecomment-432226705

Try to build without optimizations.

**Comment by neuromancer** [comment]
You are right!, adding: 

```
unset CFLAGS
unset CXXFLAGS
unset CPPFLAGS
```

in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gamehub-git) solves this issue.
