### ISSUE TITLE
Can't run wine games

### ISSUE THREAD

**Issue by Hedronmx** [tkashkin/GameHub#116]
I get the following error
`wine: /mnt/514B1ADA3D5D3784/Crawl/_gamehub/wine_win64 is not owned by you`

Any ideas? Could it be because im running the game of a different hard drive?
Thanks!

**Comment by tkashkin** [comment]
Is that partition NTFS? You need to change mount options.

That `/etc/fstab` entry works for me:
```
UUID=01D3441872ECC5E0 /mnt/Games auto exec,umask=000,uid=1000,gid=1000,user,users,permissions,nofail,x-gvfs-show,x-gvfs-name=Games 0 0
```

**Comment by Hedronmx** [comment]
That did the trick, thank you!
