### ISSUE TITLE
Issues with steam library folders. Game hub cannot find the path to the game data?  

### ISSUE THREAD

**Issue by turin331** [tkashkin/GameHub#117]
Would it be possible to add support for multiple Steam library folders? I actually have the game data on a different partition with an added library folder but gamehub can only point to one installation directory thus the typical .steam (which is required as that is where the local credentials are). As a result the direct commands (like run, uninstall etc) on game hub just open steam and do not do anything more as gamehub cannot see the game data. 

Cheers!

**Comment by tkashkin** [comment]
GameHub is supposed to launch Steam client to do anything with Steam games.
However it does read Steam library directories to check if games are installed.
It should use main library directory `~/.steam/steam/steamapps/` and all library directories found in `~/.steam/steam/steamapps/libraryfolders.vdf`.

**Comment by turin331** [comment]
Interesting. It does not seem to do that for me and i see the folder on the .vdf. I have an automounted-at-login partition where the additional library folder is. Not sure if that is the issue cuase of the mnt naming. I will try a few things and check back.

**Comment by turin331** [comment]
Ok so my initial assumption was wrong. It is not a issue that has do to with the additional libraries. (sorry about that). The seems to be the same issue fort me even if i install sth on the default library folder.

**Comment by tkashkin** [comment]
What is the problem exactly? If it was not opening game install directory, it's fixed in d6eccf5. `install_dir` was not set for Steam games.

If you have different issue, please clarify what that issue exactly is and post errors from log if any errors occur.
(Run `com.github.tkashkin.gamehub --debug` in terminal.)

**Comment by turin331** [comment]
The issue is that none of the buttons on steam games did anything. The open installation folder one did nothing. Run and Uninstall just opened up steam on the home page and also did nothing after that. 

The issue with the installation folder was actually fixed on the last update as you say. Run and uninstall still do the same thing and i do not see any error on the debug output.  The only line i see when pressing run are these:

Running Steam on linuxmint 19 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!


I am attaching the full debug output in case you see sth i am missing: 

https://pastebin.com/8c2vXHpX

**Comment by tkashkin** [comment]
Maybe Steam is not configured as `steam://` URL handler on your system.
To test this try to open `steam://install/<appid>` in browser or do `xdg-open steam://install/<appid>` in terminal (replace <appid> with id of any Steam app).

Also try to click at "Generate key" link in settings. It should also open Steam client (steam://openurl/https://steamcommunity.com/dev/apikey).

**Comment by turin331** [comment]
Same result with both the appid and the generate key link. Opens steam at the store page.

**Comment by tkashkin** [comment]
Weird. Does `steam steam://install/<appid>` work?

---

Here's how it's configured on my system: 

`$ cat /usr/share/applications/mimeinfo.cache | grep steam`
```bash
x-scheme-handler/steam=steam.desktop;
```

`$ cat ~/.local/share/applications/mimeinfo.cache | grep steam`
```bash
x-scheme-handler/steamvr=valve-steamvr.desktop;
```

`$ cat /usr/share/applications/steam.desktop`
```ini
[Desktop Entry]
Name=Steam
Comment=Application for managing and playing games on Steam
Comment[...]=...
Exec=/usr/bin/steam %U
Icon=steam
Terminal=false
Type=Application
Categories=Network;FileTransfer;Game;
MimeType=x-scheme-handler/steam;
Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
...
```

---

Make sure your `steam.desktop` main entry has `MimeType` property and uses `%U` in `Exec` property.

Try to run `sudo update-desktop-database` and `sudo update-mime-database`. If that doesn't work, try solutions from https://askubuntu.com/questions/514125/url-protocol-handlers-in-basic-ubuntu-desktop (probably `xdg-mime default steam.desktop x-scheme-handler/steam` should work).

**Comment by turin331** [comment]
Same result. The configuration seems slightly different though not sure if it would be an issue: 

`cat /usr/share/applications/mimeinfo.cache | grep steam`
`x-scheme-handler/steam=steam.desktop;`

`[Desktop Entry]
Name=Steam
Comment=Application for managing and playing games on Steam
Comment[de]=Spiele auf Steam verwalten und spielen
Exec=sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam' %U
Icon=steam
Terminal=false
Type=Application
Categories=Network;FileTransfer;Game;
MimeType=x-scheme-handler/steam;
Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
Keywords=Games
`

**Comment by tkashkin** [comment]
`Exec` seems to not pass `%U` to Steam.
Try to change it to `Exec=env STEAM_FRAME_FORCE_CLOSE=1 steam %U`.

**Comment by turin331** [comment]
That worked. Thanks for the help. interesting though since this was the default configuration when installed the steam packages from the steam site directly.

**Comment by turin331** [comment]
As a final note to this...Steam updates reset the steam.desktop file annoyingly enough

**Comment by turin331** [comment]
If it is not Steam there some updated that reset it. I will try and keep an eye if it happens again

**Comment by turin331** [comment]
Turns out it resets the configuration with a reboot. I did not notice since i rarely reboot the machine and though it was an update.

**Comment by Jimi-James** [comment]
@turin331 Reading through this, that's very interesting. I'm still figuring out a similar issue myself, but I just wanted to say--on my system, Steam never modifies the my `.local/share/applications/steam.desktop` file, which also gets to be the default file my system uses thanks to the rules of Linux and user overrides. The modifications I've made to the file have always stayed there and have never been removed by anything or anyone but me. All I can guess at is maybe some difference in package setup/upgrades between distributions? You mentioned a .deb, while I'm an Arch user. Maybe I could be of help with getting to the bottom of why your `.desktop` file won't stay the same.

**Comment by turin331** [comment]
This is on Linux Mint 19.1. I have really tested this before but indeed it might be a distro specific issue.

**Comment by ghost** [comment]
> Turns out it resets the configuration file with a reboot. I did not notice since i rarely reboot the machine and though it was an update.

Did you find a way to prevent this?
