### ISSUE TITLE
GOG games with DLC (not bonus material) not downloading or installing the DLC

### ISSUE THREAD

**Issue by hogarthj** [tkashkin/GameHub#118]
It looks like that GameHub isn't correctly identifying the state of DLC content for GOG games.

It's displaying DLC in details that is not owned (eg War for the Overworld I don't own the Undergames but it still lists it) and for DLC which is owned is not providing any options to download (and preferably install) it.

Eg Hacknet shows Labyrinth as DLC but no installer ... if I click on it then it says it is installed when it isn't.

**Comment by tkashkin** [comment]
I'm working on this. Unfortunately I don't have too many DLCs on GOG to properly test it.

There are a few problems with DLCs:
* There's `is_installable` property which is `true` for DLC with installers and `false` for bonus-only DLCs. But I haven't found a way to know whether user owns DLC or not. If user doesn't own DLC/game, installer and bonus downloads will fail. I haven't found a way to know it before download.
* DLCs for Linux games that I have on GOG doesn't seem to include any metadata, so installed DLCs should be tracked separately.
* They doesn't seem to include uninstaller either.

Windows DLCs seem to include both metadata and uninstaller.

**Comment by tkashkin** [comment]
I have one interesting idea for DLCs, patches and mods management:

Base game, patches, DLCs and mods are installed in separate directories (let's call them "overlays"). Each overlay except base game can be disabled. All enabled overlays are layered on top of each other.

That should be useful and make installed DLC tracking easy while allowing to disable them.

I have implemented similar thing before on Windows using symlinks.
For Linux it should be even easier with [OverlayFS](https://wiki.archlinux.org/index.php/Overlay_filesystem).

**Comment by tkashkin** [comment]
6a72d84 allows to download and install owned DLCs. It will silently fail to download if DLC is not owned.
