### ISSUE TITLE
Integration with play.it scripts

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#119]
I wonder if you could somehow integrate [play.it](https://wiki.dotslashplay.it//en/start). They have a large library of [scripts available in GitHub](https://github.com/vv221/play.it). They even included hashes and installer sizes. I think we can learn a few tricks from them to improve GameHub!

**Comment by tkashkin** [comment]
Looks interesting, but I don't think that it's useful for GameHub.
