### ISSUE TITLE
Environment Variables?

### ISSUE THREAD

**Issue by Saroufim** [tkashkin/GameHub#121]
I suggest adding a section in the configs for some predefined environment variables. These can be useful for both native and wine-based games. Check a few of them here: https://github.com/lutris/lutris/wiki/Performance-Tweaks

**Comment by tkashkin** [comment]
Added as Wine/Proton option for next release.

![image](https://user-images.githubusercontent.com/2003017/47967401-e4d4ab80-e06d-11e8-958b-3f44d5587f50.png)

**Comment by Saroufim** [comment]
Has this been added to the dev branch or the master branch? I'm using 0.12 and I can't find the feature.

**Comment by Saroufim** [comment]
The fields don't show up with Proton either

**Comment by tkashkin** [comment]
Weird. It should appear for both Proton and Wine.

![image](https://user-images.githubusercontent.com/2003017/48268578-66e61b00-e446-11e8-8890-dbc2188313ff.png)

![image](https://user-images.githubusercontent.com/2003017/48268587-6fd6ec80-e446-11e8-9902-88044d95eb3f.png)

**Comment by Saroufim** [comment]
![captura de pantalla de 2018-11-09 16-41-10](https://user-images.githubusercontent.com/4712288/48268767-955ff800-e43e-11e8-8be4-54927803bc9e.png)

**Comment by tkashkin** [comment]
Options are shown only in run dialog. Open it from context menu.

**Comment by HuxyUK** [comment]
Hi,

I use Nvidia PRIME render offloading on a game by game basis. In steam I just need to add the prefix to %command%. In GameHub I can't seem to find a easy way of adding environment variables to the game. I looked at enabling the compatibility options, but it doesn't seem intuitive. 

I'd like to apply the environment variable on **native** games as well as compatibility layer games.

For reference I use the following for OpenGL Games:
```__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __GLX_VENDOR_LIBRARY_NAME=nvidia```

A good solution might be to add an Environment box to the UI, similar to the parameters one?
![Properties](https://user-images.githubusercontent.com/3058486/66039379-a0b38a80-e50c-11e9-8018-8930e4cd94d5.png)

Thoughts?

**Comment by tkashkin** [comment]
@HuxyUK https://github.com/tkashkin/GameHub/issues/297#issuecomment-523275727. Something like this should probably work:
```
env __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __GLX_VENDOR_LIBRARY_NAME=nvidia ${command}
```

**Comment by HuxyUK** [comment]
Thanks the for the quick reply!

Where would I use that command? Can I add it using the UI or do I need to write a compatibility script? Adding it solely to the Executable or Arguments doesn't work, so I guess I'm missing something..  :confused:

**Comment by tkashkin** [comment]
@HuxyUK you should just add it to the Arguments field.

It hasn't been merged in `master` branch yet, so you need to be on `dev` branch for it to work. Check your version in Settings or with `com.github.tkashkin.gamehub -v` in terminal.

**Comment by HuxyUK** [comment]
Ahh right!
I'm on the master branch packaged in Solus at the moment. Explains why I can't get it to work. 

```Version: 0.14.2--master
Branch:  master
Commit:   ()
Distro:  Solus
DE:      GNOME```

**Comment by tkashkin** [comment]
@HuxyUK as a workaround for older versions you can try this:

Executable:
```
/usr/bin/env
```
Arguments:
```
__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __GLX_VENDOR_LIBRARY_NAME=nvidia /path/to/game/executable
```

**Comment by HuxyUK** [comment]
I tried what you suggested but every time I set ```/usr/bin/env``` in the executable field it ends up resetting it back to the game's startup executable. It's very odd behaviour.
