### ISSUE TITLE
Xbox guide button Focus or Open Gamehub

### ISSUE THREAD

**Issue by Hedronmx** [tkashkin/GameHub#122]
This would be awesome to have, to be able to open and focus GameHub with the xbox guide button.

**Comment by tkashkin** [comment]
It should be possible if your controller sends events for guide button and these events are captured by GameHub.

Run `com.github.tkashkin.gamehub --debug` and press controller buttons.

You should see "[Gamepad] Button `<pressed/released>`: `<short name>` (`<long name>`) [`<code>`]" in log if everything works correctly.

**Comment by tkashkin** [comment]
Example output for Steam Controller (Wireless) with `hid_steam` kernel module:
> [Gamepad] Button pressed: Home (Home) [316]

**Comment by Hedronmx** [comment]
Yeps it shows
`GamesView.vala:1036: [Gamepad] Button pressed: Home (Home) [316]
[DEBUG 15:04:41.755858] GamesView.vala:1036: [Gamepad] Button released: Home (Home) [316]
`

**Comment by tkashkin** [comment]
Focus should be easy to implement. You will still need to launch GameHub manually or bind it with other tools (`sc-controller`?).

**Comment by tkashkin** [comment]
Implemented for next release

**Comment by Jimi-James** [comment]
This feature, which I had no idea was even in GameHub, almost got me killed in Sekiro (because it didn't pause the game). Is there an option to disable it? If not, can there be one? I like using GameHub with a controller, but I can't do that anymore if I could accidentally press the Guide button and cause this to happen anytime mid-game.

**Comment by tkashkin** [comment]
@Jimi-James this feature was disabled automatically while game is running, but GameHub currently doesn't detect if Steam games are running. However it works for non-Steam games.

3628f0b adds settings to toggle controller support entirely and to disable focusing behavior.

I'll probably also add settings to ignore specific controllers in future.

**Comment by cafehaine** [comment]
On windows the running game has a key created in it's registry, maybe there's a similar thing on Linux?

**Comment by Jimi-James** [comment]
As far as I know, the process is exactly how. If Linux Steam has a reliable way to tell which game is running and when, then I don't know it.

**Comment by tkashkin** [comment]
There is `~/.steam/registry.vdf` file. It seems that Steam client still stores some data in registry and emulates it on non-Windows systems for probably some legacy reasons.

It has `RunningAppID` key which can be used for this:
```
"Registry"
{
	"HKLM"
	{
		"Software"
		{
			"Valve"
			{
				"Steam"
				{
					"SteamPID"		"0"
					"TempAppCmdLine"		""
				}
			}
		}
	}
	"HKCU"
	{
		"Software"
		{
			"Valve"
			{
				"Steam"
				{
					"RunningAppID"		"427520"
					...
					"Apps"
					{
						...
						"427520"
						{
							"installed"		"1"
							"Updating"		"0"
							"Running"		"1"
							"name"		"Factorio"
						}
						...
					}
				}
			}
		}
	}
}
```

It also has `Updating` key for each game so it should be possible to show game state in GameHub too.

**Comment by tkashkin** [comment]
@Jimi-James now GameHub should show running and updating Steam games. Controller focus should also be disabled when Steam game is running.
