### ISSUE TITLE
If you remove many games too fast, the app crashes.

### ISSUE THREAD

**Issue by Hedronmx** [tkashkin/GameHub#127]
If you remove a lot of games fast, the app crashes showing this error.
`**
ERROR:arraylist.c:1199:gee_array_list_real_get: assertion failed: (index < _size)
`

**Comment by tkashkin** [comment]
Have you been able to reproduce it multiple times? How hard is it to reproduce? How often does it happen?

**Comment by Hedronmx** [comment]
Yes i have done it multiple times, its really easy.
I just found out about this because I had to remove all of my rom games. So I did it fast and it crashed about 5 times

**Comment by tkashkin** [comment]
I'll try to debug it tomorrow. Probably some multithreading issue.
Does it happen if you wait some time for it to finish all loading and updates?

**Comment by Hedronmx** [comment]
It happens when you do it really fast, right click -> remove game, multiple times

**Comment by tkashkin** [comment]
I can't reproduce on my system for some reason. It may depend on number of games, number of games added by user, performance, etc. Or I'm just not fast enough.

It will help if you run it with `gdb` and get a backtrace:
* Run `gdb com.github.tkashkin.gamehub`
* Enter `r` to run, try to reproduce, enter `bt` when it crashes

**Comment by Hedronmx** [comment]
I couldn't replicate again.... I guess I will close this
