### ISSUE TITLE
Flatpak: Some icons do not appear

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#14]
![captura de tela de 2018-07-15 21-24-08](https://user-images.githubusercontent.com/26097419/42739985-03f264c0-8877-11e8-86b8-78ccb76cd7a8.png)
![captura de tela de 2018-07-15 21-24-22](https://user-images.githubusercontent.com/26097419/42739989-10e77c1a-8877-11e8-9851-dcd76c2e482b.png)
```
You will need to put all the icons inside the sandbox
```

**Comment by tkashkin** [comment]
@LeandroStanger Icons should be fixed in https://github.com/tkashkin/GameHub/releases/tag/0.5.4

Report if you'll find any missing icons.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-07-18 19-02-05](https://user-images.githubusercontent.com/26097419/42910494-2bc0717e-8abe-11e8-9b02-dc0f75256f4c.png)

**Comment by tkashkin** [comment]
@LeandroStanger This is not the same issue, in this case dialog takes `GLib.Icon`, but for some reason under flatpak it can't load it neither from local nor from remote file. It will be fixed when I'll slightly rewrite layout of this dialog.
