### ISSUE TITLE
Export game collection?

### ISSUE THREAD

**Issue by Hedronmx** [tkashkin/GameHub#143]
Could it be posible to export game collection, I have two pc's running elementary os, could it be possible to export it so I can duplicate my games on my other pc?

**Comment by tkashkin** [comment]
You can copy `~/.cache/com.github.tkashkin.gamehub` to other device. It contains database, cached images and cookies.

You can also try to copy settings:
* `dconf dump /com/github/tkashkin/gamehub/ > gamehub_settings` on first device
* `dconf load /com/github/tkashkin/gamehub/ < gamehub_settings` on second device
