### ISSUE TITLE
Dosbox detections fails on GOG games because they are not moved from the app folder

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#146]
Innoextract extracts the GOG installers, but most of the games (for instance, Theme Park), are located in the `app` folder. Since, GameHub does not move them into the proper game folder, the Dosbox detection fails. This feature used to work perfectly some time ago..

**Comment by tkashkin** [comment]
Broken by #114. Should be possible to fix by adding `app` to detection paths.

**Comment by neuromancer** [comment]
This should be fixed.
