### ISSUE TITLE
GOG games installed with compability tools do not show its version

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#148]
![version](https://user-images.githubusercontent.com/110782/48963746-13141f80-ef78-11e8-814e-51b1d3586736.png)

**Comment by tkashkin** [comment]
I haven't found a metadata file where version is stored for Windows GOG games. The best thing that can be done is to save version of installer.

**Comment by neuromancer** [comment]
Uhm, I checked the version of the installers and they have non-informatives names (e.g. `installer0`). Let's close this.
