### ISSUE TITLE
Feature: Keep db of games from game services

### ISSUE THREAD

**Issue by friday** [tkashkin/GameHub#159]
When I restart GameHub is shows nothing, and then starts syncing to get the data. While this seems to be pretty fast, it would be better to keep them in a local db, to avoid the wait and possible redundant requests.

**Comment by tkashkin** [comment]
Everything is already cached, but there is a small delay to prevent UI thread blocking. See https://github.com/tkashkin/GameHub/issues/57#issuecomment-428494266.

**Comment by friday** [comment]
Thanks! I disabled merging, which improved it at least.
