### ISSUE TITLE
Steam API key can be deleted

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#16]
![captura de tela de 2018-07-16 08-19-24](https://user-images.githubusercontent.com/26097419/42756116-2dc49494-88d1-11e8-9888-14babb548171.png)
Steam API key can be deleted

**Comment by tkashkin** [comment]
@LeandroStanger It's not a bug, user really should use own key. I may add reset button or just reset key if it's is empty in the future.
