### ISSUE TITLE
Button contrast is very low on dark headers and low on dark theme

### ISSUE THREAD

**Issue by friday** [tkashkin/GameHub#165]
These are hard to see (especially settings):

![gamehub-button-contract](https://user-images.githubusercontent.com/515120/50797760-271ca200-12d6-11e9-9d13-790f769f61c8.png)

**Comment by tkashkin** [comment]
I don't know if anything can be done with that.

App expects colored, full-size non-symbolic icons here, but your icon theme provides dark, flat, "symbolic-like but actually not" icons.

If these icons were symbolic they would at least change color.

**Comment by friday** [comment]
It's [Paper Icon Theme](https://snwh.org/paper) by Sam Hewitt. It mainly a png based icon theme, but has both symbolic and full size icons, for a various set of sizes. Never really seen issues like this with it before.

The settings icon is an eye too. Not a cogwheel, series of dots or strips.

Maybe it's a combination of factors somehow. Will try to investigate this.

**Comment by friday** [comment]
I've come to the conclusion that you're using unconventional icons and icon sizes in the headerbar. It may not be "wrong", but it's less likely to work for different icon themes, and may look unusual.

With some modifications, it now looks like this:

![screenshot from 2019-01-12 18-48-08](https://user-images.githubusercontent.com/515120/51076633-3ff0d300-169b-11e9-8acb-aa200ea2070f.png)

I changed all the icons in the headerbar to symbolic variants and `IconSize.BUTTON` and changed `emblem-downloads` to `folder-download`. Will send a PR if you want.

Since you seem to like large icons (or maybe it's part of the Elementary design policy), you may not like these changes though.

This is how it looked with Korla icon theme before changing to folder-download: :rofl: 
![screenshot from 2019-01-12 18-05-38](https://user-images.githubusercontent.com/515120/51076708-429ff800-169c-11e9-88a9-8360b727c5af.png)

**Comment by tkashkin** [comment]
I have added symbolic icons option. Let me know if I have missed any icons.

**Comment by friday** [comment]
Cool! You didn't miss any icon as far as I can see. Was just about to push a PR with this and some other changes mostly to share my code. I went other directions in a couple of places.

1. Changed all the headerbar icons to 16px (https://github.com/tkashkin/GameHub/commit/b32ea8022e78e5c79554b4afda52b749c53d5372)
2. Changed the GameDetailsPage icons to 32px (36px is non-standard, so it's more likely to look blurry or get the wrong size) (https://github.com/tkashkin/GameHub/commit/8f02067fd061d70bd7cbf0c0424c33071689c35a)
3. I didn't use symbol icons for files and folders. Mainly because it wasn't a problem. All themes I tried (except Korla which is new and in development) had file icons in 32px size, and they all looked better that way (again except Korla).. I think because file managers like Nautilus has many custom zoom modes, this is not a problem. But also according to [Elementary guidelines](https://elementary.io/docs/human-interface-guidelines#colored-vs-symbolic).

![symbolic-icons](https://user-images.githubusercontent.com/515120/51078111-8270da80-16b0-11e9-8e3a-2b0d7bad169c.png)
![my-fork](https://user-images.githubusercontent.com/515120/51078113-87358e80-16b0-11e9-9324-3d195698069a.png)

I understand if you don't want to do that though, since the option is named "Use symbolic icons instead of colored icons", and the other two changes your intended look and feel.

**Comment by tkashkin** [comment]
1. I don't think it changes anything. [Valadoc](https://valadoc.org/gtk+-3.0/Gtk.IconSize.html):
> Enum values:
INVALID - Invalid size.
MENU - Size appropriate for menus (16px).
SMALL_TOOLBAR - Size appropriate for small toolbars (16px).
LARGE_TOOLBAR - Size appropriate for large toolbars (24px)
BUTTON - Size appropriate for buttons (16px)
DND - Size appropriate for drag and drop (32px)
DIALOG - Size appropriate for dialogs (48px)

2. It should be size of the buttons itself, not icons. Icons have `IconSize.BUTTON` (16px) by default and are symbolic so should scale.
3. It looks a bit weird if some icons here are symbolic and some are not.

**Comment by friday** [comment]
3 is a reasonable arguments, and you're probably right about 2. I probably just tricked myself into thinking it made a difference.

Maybe the size could be part of the option/condition too, or another one for smaller icons? I wouldn't be pushing this if it was just me that had a strange preference. I'm not sure about Elementary OS, but in Gnome for sure the way you've been doing it is unconventional. Stacked GameHub on top of some Gnome apps to illustrate:

![stacked](https://user-images.githubusercontent.com/515120/51078648-0fb82d00-16b9-11e9-976a-cb8540fed4da.png)

If I'll think of something we can both agree on I'll submit a PR.

**Comment by tkashkin** [comment]
It will now use 16px icons in headerbar if symbolic.

![2019-01-13 00-59-08](https://user-images.githubusercontent.com/2003017/51078944-f91cd080-16ce-11e9-8bd3-16bb3727586c.png)

**Comment by friday** [comment]
Nothing left to improve now I think :+1:
