### ISSUE TITLE
Feature: Rename "The ..." to "..., The" in  titles.

### ISSUE THREAD

**Issue by friday** [tkashkin/GameHub#166]
Some game series are inconsistently named, for example: 

![blackwell](https://user-images.githubusercontent.com/515120/50798362-68ae4c80-12d8-11e9-8bb4-b9ddfd26cd9e.png)

Unless I had filtered out "blackwell" there, there would have been hundreds of games between Unbound and Epiphany.

Additionally GOG sometimes use "..., The", but steam doesn't seem to. So merging fails:

![merging](https://user-images.githubusercontent.com/515120/50798614-3d782d00-12d9-11e9-9481-4d01ba91a26a.png)

Possibly even safer for merging is using [Lutris](https://lutris.net/games/the-night-of-the-rabbit/), [IGDB](https://www.igdb.com/games/the-night-of-the-rabbit) or some other db which collects both GOG and steam id's. But that means even more requests, and maybe it's just not worth the effort.

**Comment by friday** [comment]
Can confirm sorting is solved, but I still get two entries for Night of the Rabbit.

**Comment by tkashkin** [comment]
It should merge all games after all games are loaded **if there's at least one new game added**. You can try to add user game and it should probably trigger merge.

**Comment by friday** [comment]
I added a free GOG game to my library, then restarted
Result: 0 Night of the Rabbit games
Disabled Meging, then restarted: 2 Night of the Rabbit games
Enabled again, restarted: Merging successful! :+1: 

Thanks again! :)
