### ISSUE TITLE
Suggestion: Split install selection into multiple choices

### ISSUE THREAD

**Issue by friday** [tkashkin/GameHub#167]
For some GOG games at least, it can become a little much:

![gamehub-beneath](https://user-images.githubusercontent.com/515120/50800615-3e14c180-12e1-11e9-9d0b-362c9d8a619d.png)

Their own view is much easier to navigate, and unless you want to change something, it could save one click (the view/window may not be needed at all):

![gog-beneath-choices](https://user-images.githubusercontent.com/515120/50800756-e75bb780-12e1-11e9-9cf4-4cd9fc490584.png)

Not sure if this is doable safely with the data they provide. And #161 may make this harder.
The pre-selected version is usually right, but not always. Sometimes the Mac version is highlighted by default (ex: Earth 2140 and Jagged Alliance 2: Unfinished Business).

**Comment by neuromancer** [comment]
Maybe it is better to hide the Mac installers by default.

**Comment by friday** [comment]
^ That's perhaps a better solution (especially from an implementation perspective). It could be hardcoded even.

I think a languages whitelist would be nice too. Many video players does something like this:

![vlc-subs-options](https://user-images.githubusercontent.com/515120/50802537-0dd02180-12e7-11e9-93d8-38f5c7dc03aa.png)

**Comment by tkashkin** [comment]
I think now it's better.

![image](https://user-images.githubusercontent.com/2003017/50805885-61516800-1305-11e9-95ca-b6a00beb9166.png)
