### ISSUE TITLE
New icon and accent colors

### ISSUE THREAD

**Issue by tkashkin** [tkashkin/GameHub#170]
Current icon seems to be a bit too generic.

**Comment by tkashkin** [comment]
@Hedronmx 

It is some random icon with hue-shifted background and random gamepad icon found on Google Images and placed on top. I don't think it's good.

I want something more unique and less ugly. I also want to pick some unique accent color and possibly add that accent to the app.

**Comment by Hedronmx** [comment]
What do you have in mind? Maybe I can create a concept or something...

**Comment by tkashkin** [comment]
> What do you have in mind?

That's the problem. I don't know exactly what do I want :confused:. Suggest your ideas if you have any.

**Comment by Hedronmx** [comment]
Alright I'll try to think of something... Something abstract maybe? Like origin logo or steam?

**Comment by tkashkin** [comment]
Yes, something recognizable, but not as boring and generic as a controller would be great.

**Comment by Hedronmx** [comment]
![Imgur](https://i.imgur.com/1KoHJH4.jpg) 

![Imgur](https://i.imgur.com/LqAWpS9.jpg)

![Imgur](https://i.imgur.com/2ndLtfE.jpg)

**Comment by neuromancer** [comment]
I agree that first icon looks nice and the second one is too abstract. However, I'm not a graphic designer, so don't take me too seriously. :open_mouth:

**Comment by Hedronmx** [comment]
@tkashkin You could try doing something like this browser.
![Imgur](https://i.imgur.com/fHAC7mq.png) Or if you have a color suggestion let me know so we can see how it looks on the icon

**Comment by friday** [comment]
Yeah, the first one is my favorite out of these too, but I don't think any of these are good enough to replace the current one. At least without more work. (sorry)

I think just the ABXY buttons looks like a dice (especially in monochrome), which is also something related to "Game", and hence could be confusing. The D-pad is more recognizable (but also used more in other icons).

**Comment by Hedronmx** [comment]
Any suggestions?

**Comment by friday** [comment]
I just edited to add some, but I'm not great with designing icons myself, so I'm not sure my suggestions are going to actually look good.

**Comment by Hedronmx** [comment]
This is how it looks on elementary dock. Ill make some changes later.
![Imgur](https://i.imgur.com/ZAhbaHN.png)

**Comment by tkashkin** [comment]
That's what I was able to do.

| purple | orange |
| :---: | :---: |
| ![test](https://user-images.githubusercontent.com/2003017/51439004-4e577400-1cc5-11e9-8173-1b8beea96484.png) | ![test_orange](https://user-images.githubusercontent.com/2003017/51439007-544d5500-1cc5-11e9-9b29-b709bca75927.png) |

I like colored buttons, but there are problems with contrast, especially for red button and for smaller icon sizes.

**Comment by friday** [comment]
Nice work with the shadows!

**Comment by Hedronmx** [comment]
@tkashkin Yeah the shadow looks really good!!

**Comment by friday** [comment]
I think @tkashkin's latest suggestion looks very polished and good, but perhaps it looks even more like a dice than the first suggestion (with the smaller buttons). Xbox and SNES-buttons are larger than that.

I don't have the time or skills to post a counter-proposal. However, I think something like this shape rather than the square (as well as larger buttons) could be used to make it look less like a dice and more like part of a gamepad (maybe more like a D-pad though)

![gamepad-shape](https://user-images.githubusercontent.com/515120/51476107-c9cc2a80-1d84-11e9-9e7a-f11061af825f.png)

Anyway, nice work both of you!

**Comment by tkashkin** [comment]
I have tried to make it look like buttons and not like a dice and here's what I have done.
Now it's even more weird :confused:.

| just xbox colors | xbox + dualshock colors |
| :---: | :---: |
| ![purple_xbox](https://user-images.githubusercontent.com/2003017/51487840-1cbdd600-1db5-11e9-879f-c38d00563ca8.png) | ![purple](https://user-images.githubusercontent.com/2003017/51487852-221b2080-1db5-11e9-8771-9715b81cb3d8.png) |

I have no idea how to improve it. Maybe that's why I have never seen anything similar in icons and everyone uses a generic controller icon :thinking:.

We need new ideas.

**Comment by friday** [comment]
I think some variant of a gamepad icon is still the easiest way. They seem to be by far the [most popular](https://www.google.com/search?q=video+games+icon&tbm=isch) [symbol](https://www.bing.com/discover/gaming-icons?first=1&tab=REC) for [gaming](https://www.shutterstock.com/search?page=2&searchterm=video%20gaming%20icon&measurement=px&sort=popular&image_type=vector&safe=true&search_source=base_search_form&language=en&saveFiltersLink=true&section=1). Probably for a good reason.

Mice and keyboards are perhaps more relevant for PC games, but these would be easy to associate with mouse and keyboard settings.
Just the WASD-keys might work for association, but I can't visualize that as a nice looking icon.

In-game symbolism [could work too](https://www.shutterstock.com/image-vector/vector-pixel-art-illustration-isons-fantasy-342284978?src=EwNeetdEv8vLWlfw6LC86g-2-73) (though these appeals to specific eras and genres).

Some nice examples (not too different from the current icon):

<img src="http://housing.umn.edu/sites/housing.umn.edu/files/video_game_icon-01.png" width="200">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Circle-icons-gamecontroller.svg/2000px-Circle-icons-gamecontroller.svg.png" width="200">

Maybe I ruined this by over-thinking though. As long as the icon doesn't have Tux (the Linux penguin) or neon green/rainbow keyboards or PC cases I think I'll be fine.

**Comment by tkashkin** [comment]
Ok, what about this?

![purple_controller](https://user-images.githubusercontent.com/2003017/51559142-32ed9400-1e92-11e9-9f99-bee55a58be7b.png)

**Comment by Saroufim** [comment]
I like this

**Comment by friday** [comment]
Yeah. Looks nicer this way :slightly_smiling_face:

**Comment by neuromancer** [comment]
Looks great!

**Comment by tkashkin** [comment]
I have updated icon and added a purple accent to app's css.

Unfortunately, every theme I have tried (except elementary) does hardcode colors and doesn't allow to override them. Here's how it looks with elementary theme:
![image](https://user-images.githubusercontent.com/2003017/51567394-283df980-1ea8-11e9-97e5-0a94a009667d.png)
![image](https://user-images.githubusercontent.com/2003017/51567458-4b68a900-1ea8-11e9-97ae-9af8e2d72cab.png)

Should I set accent color even if it works only on elementary?
Does this purple look good or should I change it to something else?

**Comment by Hedronmx** [comment]
Daaang it looks lovely!! Well I am using elementary... so for me the accent color looks fantastic. Love the purple

**Comment by friday** [comment]
In Gnome and most other GTK-based DE's, the convention (or maybe even rule) is for the theme to dictate the highlight colors and other colors.
EOS seems to have different [meanings for colors](https://www.reddit.com/r/elementaryos/comments/8m2s3d/official_elementary_os_colors/). Purple is for "dev" apparently, but they're "pretty flexible with color."

**Comment by tkashkin** [comment]
I continue to experiment with elementary theme branding and that's how it looks with a primary color:

![image](https://user-images.githubusercontent.com/2003017/51575455-32b9bc80-1ec3-11e9-834a-e9299da36b6d.png)
![image](https://user-images.githubusercontent.com/2003017/51575429-1cabfc00-1ec3-11e9-8c71-005c3bfd67a2.png)

I'm not sure if it's not too vibrant and distracting. I'm waiting for feedback and suggestions. I'm also open to other color suggestions.

---

> In Gnome and most other GTK-based DE's, the convention (or maybe even rule) is for the theme to dictate the highlight colors and other colors.

Yes, that's probably a (part of) reason why most themes don't allow app-specific customization.
elementary, unlike GNOME, allows and encourages app-specific branding: https://medium.com/elementaryos/a57cb44d31d3.

> eOS seems to have different meanings for colors. Purple is for "dev" apparently, but they're "pretty flexible with color."

These meanings are suggestions, but it does not mean that these colors can't be used in other contexts.

**Comment by Hedronmx** [comment]
I believe dark theme without the accent color on the header bar looks better. Everything else looks superb!
