### ISSUE TITLE
Games with .exe and .bin files do not get installed

### ISSUE THREAD

**Issue by loaderini** [tkashkin/GameHub#174]
I tried two things on Ubuntu 18.04.1:
**1.** installing XCOM: Enemy Unknown via download through Gamehub and 
**2.** adding an installer and use previously downloaded 6 files (1 .exe and 5 .bin) through the big plus button on the top bar of Gamehub.

On both cases, the installer did not finish. It works well with .exe files and when time comes to go to the next (which are .bin files for GOG games) it stops and simply says "Not installed". I noticed this with other GOG games that have .exe and .bin. Games that only have 1 .exe file and nothing else work perfectly.
Does anyone else have that problem?

**Comment by tkashkin** [comment]
You should not use plus button for supported games (those from Steam, GOG and Humble).

I need to know what exactly happens when you install game through GameHub.
Run `com.github.tkashkin.gamehub --debug --log-downloader` in terminal and post its output here.

**Comment by tkashkin** [comment]
I don't see anything wrong in log.

How are you trying to install the game? What compatibility layer are you trying to use and what layers do you have installed?

**Comment by loaderini** [comment]
Yes I successfully reproduced the issue before copying the log. I copied the .exe and .bin files in the proper folder so that it wouldn't need to download them again and then tried to install. So far I have tried all the layers, proton, wine 32 and 64, abrahms wine and innoextract. But no matter, no there's a different problem. I decided to start over, reinstall the app and remove all configuration/settings files, but every time I reinstall the app remembers the old settings. How do I completely remove everything in order to do a clean reinstallation?

**Comment by tkashkin** [comment]
* `rm -rf ~/.cache/com.github.tkashkin.gamehub/` to remove caches and database
* `dconf reset -f /com/github/tkashkin/gamehub` to reset settings
* `sudo apt remove com.github.tkashkin.gamehub` to remove package

Then install latest version and try again.

**Comment by deckoff** [comment]
Was this solved in any way? 
I am trying to install Heroes of Might and Magic 3, and getting the same issue. Not only is the game says it is not installed, the folder where the files should be are empty.

**Comment by tkashkin** [comment]
@deckoff

* Is this a Windows-only GOG game?
* Which compatibility layers do you have listed in install dialog and which layers did you try to use?
* Have you tried to uncheck silent install options if you have tried to install it with Wine or Proton? Some installers may try to show EULA and may not work in silent mode.

**Comment by deckoff** [comment]
OK, unchecking silend mode somehow solved it.  Thanx!

**Comment by neuromancer** [comment]
I think the use of some default installer options (silent mode, no-GUI, etc) should be disabled when using the manual installer option.
