### ISSUE TITLE
Feature: Prevent launching multiple instances

### ISSUE THREAD

**Issue by friday** [tkashkin/GameHub#175]
It's possible to launch multiple instances of GameHub using desktop entries-based apps or menus, or  `com.github.tkashkin.gamehub` (with no cli options).

I'm not sure this is safe (data races and such), but it's confusing at least.

Some other apps (including Spotify) has this problem too, and there are some wrappers (`raise-or-run` or `jumpapp` for example) that can be used in the desktop entries. This doesn't fully solve the problem though.

**Comment by tkashkin** [comment]
It doesn't seem to be the case in my local branch, but it may differ as I am reworking CLI parsing now.
However it shouldn't be the case in current version as well.

**Comment by friday** [comment]
My bad! I've been switching between versions when testing. It really is fixed in the latest commit in the dev-branch.
