### ISSUE TITLE
[Question] Advice for a Windows equivalent?

### ISSUE THREAD

**Issue by ronjouch** [tkashkin/GameHub#176]
Hi.

This is a non-"Issue", merely a question: with the rise of non-Steam stores (Itch, GoG, Ubi, MS App Store, Epic Store, ...), my Windows box games are fragmented across these stores. So I'd love something like GameHub, but for Windows.

Maintainers, users, passersby: any recommendation?

Thanks, and sorry for the noise.

**Comment by tkashkin** [comment]
Check out [Playnite](https://github.com/JosefNemec/Playnite).
Also I remember LaunchBox was a quite popular launcher, but I don't how does it compare to Playnite now.

As an alternative consider adding all your games to the Steam library and using Steam as your main launcher. I have written a small utility that adds GOG games to the Steam library: [GOGWrapper](https://github.com/tkashkin/GOGWrapper).

**Comment by tkashkin** [comment]
@ronjouch

I have tried to build GameHub on Windows and with some changes it compiled and started (using MSYS2).

With third-party GTK theme it even looks almost native:
![image](https://user-images.githubusercontent.com/2003017/61427285-3f751580-a926-11e9-93a0-6835f602473e.png)

There are some problems but I think it should be possible to port it to Windows.

Do you think I should try to do complete port or will it be completely useless?
(Especially considering GOG Galaxy 2.0, Playnite, Launchbox and unknown amount of other Windows launchers)

**Comment by ronjouch** [comment]
> I have tried to build GameHub on Windows and with some changes it compiled and started (using MSYS2). With third-party GTK theme it even looks almost native

@tkashkin cool!

> There are some problems but I think it should be possible to port it to Windows.
> 
> Do you think I should try to do complete port or will it be completely useless?
> (Especially considering GOG Galaxy 2.0, Playnite, Launchbox and unknown amount of other Windows launchers)

@tkashkin my take is that no, you shouldn't try to complete & maintain a Windows port, unless you earnestly want the challenge and/or want to make a living out of it (in which case selling it to a larger audience makes sense). I like software that stays focused –and restricting to Linux/GNOME brings focus–, for two reasons:

1. Focus increases quality, 1. by staying native to the platform (which you are doing focusing on a GNOME feeling and using GTK / Vala), 2. by reducing target variance, enabling allocating all resources (you 😄) to supporting the focused platform. It's just project management 101, doing job A is faster than doing job A + B (and here it's not just A + B, it's A + B + interactions!), I'm not contradicting that GameHub with a good Windows theme _"looks almost native"_.
2. Maintaining GameHub must already be lots of work, there probably won't be new maintainers flying over to help on GameHub Windows, and you'll be left with twice the work, leading quicker to boredom and transforming your hobby project into a hassle.

And yup, there are now gooooood alternatives under Windows. I've been enjoying Playnite recently, and am curious to see GOG Galaxy 2.0. So maybe this is a third argument, considering the Windows case is addressed by other tools.

My two cents! In the end, it's your take. At any rate, thanks again for your work 🙂.
