### ISSUE TITLE
Flatpak-erro: [FATAL 09:16:03.686163] string_to_string: assertion 'self != NULL' failed

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#18]
GameHub 0.5.3

**Comment by tkashkin** [comment]
@LeandroStanger Was it crash or just error in log. If it didn't crash and there were no noticeable bugs, it should be fine. What were you doing in app before this error?

**Comment by LeandroStanger** [comment]
![peek 18-07-2018 10-13](https://user-images.githubusercontent.com/26097419/42883961-724443dc-8a73-11e8-82a8-8095354bde6e.gif)

**Comment by tkashkin** [comment]
@LeandroStanger I think maybe games database is somehow corrupted.
Try to remove `~/.var/app/com.github.tkashkin.gamehub/cache/com.github.tkashkin.gamehub/games.db`.

Also you can launch GameHub with `--debug` parameter to get more logs.

**Comment by tkashkin** [comment]
@LeandroStanger I've uploaded [0.5.4 flatpak bundle](https://github.com/tkashkin/GameHub/releases/tag/0.5.4).

Also there's now a [flatpak branch](https://github.com/tkashkin/GameHub/tree/flatpak) with manifest and libs. I've added build instructions there, but I might have missed something.

**Comment by LeandroStanger** [comment]
@tkashkin Now it's working

- Add a button in the settings to delete the database

![captura de tela de 2018-07-18 10-33-31](https://user-images.githubusercontent.com/26097419/42885031-4bc917f2-8a76-11e8-9a3f-1064b0ebd161.png)

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-07-18 11-41-13](https://user-images.githubusercontent.com/26097419/42888858-801a6d5e-8a7f-11e8-9e33-738a0841661e.png)

**Comment by tkashkin** [comment]
@LeandroStanger I've added libivy, is should show stacktrace after crashes.
I've also updated [flatpak bundle](https://github.com/tkashkin/GameHub/releases/tag/0.5.4) to include libivy.

**Comment by LeandroStanger** [comment]
```
Registering Stacktrace 0.9.4
[INFO 20:32:55.289374] Application.vala:154: GameHub version: 0.5.4
[INFO 20:32:55.289526] Application.vala:156: Kernel version: 4.15.0-23-generic
[DEBUG 20:32:55.511640] Settings.vala:163: Loading settings from schema 'com.github.tkashkin.gamehub.ui'
[DEBUG 20:32:55.607703] Settings.vala:163: Loading settings from schema 'com.github.tkashkin.gamehub.auth.steam'
[DEBUG 20:32:55.608358] GOG.vala:134: [Auth] Refreshing GOG access token with refresh token: 8coxZBMBkhzRyTyJRsjxw0kjc4gUeni7877Ps5zXqCzcsGMQ7T9ucox6jPP_ryPG
[DEBUG 20:32:55.612784] Settings.vala:163: Loading settings from schema 'com.github.tkashkin.gamehub.saved-state'
[DEBUG 20:32:56.856465] GOG.vala:145: [Auth] GOG access token: swFwN9xajnXlJKZZPghiBUBdXNz9o6W8qIzTkuA3xd_Nur1CLWK5KgZApMMH8cdSa3uakVc9Ouq6C2yQjApRB95C6E7xypXZZEMWuc_6MjQOx8vXAQWLfPAIfks2BjudD5_9mBi7bGwfmD_TcXWh51EmdrBXmPDMSkiefta2xTs
[DEBUG 20:32:56.856596] GOG.vala:146: [Auth] GOG refresh token: 8coxZBMBkhzRyTyJRsjxw0kjc4gUeni7877Ps5zXqCzcsGMQ7T9ucox6jPP_ryPG
[DEBUG 20:32:56.856671] GOG.vala:147: [Auth] GOG user id: 50528420723022335
[FATAL 20:33:47.162230] [Json] json_object_get_string_member: assertion 'node != NULL' failed
Error while executing 'addr2line -f -e /app/bin/com.github.tkashkin.gamehub 0x7f9f69f4b83d': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGTRAP)
   The reason is likely an uncaught error.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

[FATAL 20:33:47.413541] string_to_string: assertion 'self != NULL' failed
Error while executing 'addr2line -f -e /app/bin/com.github.tkashkin.gamehub 0x7f9f69f4b83d': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGTRAP)
   The reason is likely an uncaught error.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?

[DEBUG 20:33:47.429842] Downloader.vala:70: Downloading 'https:'...
Error while executing 'addr2line -f -e /app/bin/com.github.tkashkin.gamehub 0x42e8c9': Failed to execute child process “addr2line” (No such file or directory)
Something went very wrong. Your stacktrace cannot be displayed
An error occured (SIGSEGV)
   The reason is likely a null reference being used.
   Note: no file path and line numbers can be retrieved. Are you sure you added -g -X -rdynamic to valac command line?
```

**Comment by tkashkin** [comment]
@LeandroStanger It seems ivy needs `addr2line` and `nm` to display stacktraces. Try to copy `addr2line` and `nm` from `/usr/bin` to `~/.local/share/flatpak/app/com.github.tkashkin.gamehub/current/active/files/bin`.
I'll add this binaries in the next bundles.

**Comment by LeandroStanger** [comment]
@tkashkin Has this been fixed in GamesHub 0.5.5?

**Comment by tkashkin** [comment]
@LeandroStanger Probably yes, but I didn't test it in flatpak much. I will upload manifest and bundle later today.

**Comment by tkashkin** [comment]
@LeandroStanger I think I've found cause of this error. Did it happen after you've opened details of `Hotline Miami 2: Wrong Number - Digital Comics` for the first time? It has no icon and it was the problem.

**Comment by tkashkin** [comment]
@LeandroStanger Try https://github.com/tkashkin/GameHub/releases/tag/0.5.6
