### ISSUE TITLE
Please Add GameHub to Flathub

### ISSUE THREAD

**Issue by pyroxar** [tkashkin/GameHub#183]
In my opinion, add GameHub to Falthub will be great improvement. 
GameHub will have more users and will be easier to install on many distributions.

What do you think about this?

**Comment by Saroufim** [comment]
I think it was on Flathub but got removed because it needs access to the
whole system and the Flathub maintainers didn't like that.

**Comment by tkashkin** [comment]
See https://github.com/flathub/flathub/pull/486#issuecomment-405053777
