### ISSUE TITLE
GameHub from flatpak can't be installed by GNOME Software nor Mintinstall

### ISSUE THREAD

**Issue by pyroxar** [tkashkin/GameHub#184]
###### Expected behavior
I should have a possibility to install GameHub from flatpak by use Mintinstall or GNOME Software.

###### Actual behavior
GameHub from flatpak can't be installed by GNOME Software nor Mintinstall.

###### Steps to reproduce
Download the flatpak file form:
https://github.com/tkashkin/GameHub/releases/download/0.13.1-1-master/GameHub-bionic-0.13.1-1-master-1f713f3.flatpak
Try to open It on Linux Mint 19.1.

###### Version and environment
Linux Mint 19.1,
Mintinstall: 7.9.7
GNOME Software: 3.28.1

**Comment by tkashkin** [comment]
Are there any specific errors?

**Comment by pyroxar** [comment]
How I can do this?
I tryied do:
![obraz](https://user-images.githubusercontent.com/23406555/51946399-a6a71800-2421-11e9-9fa5-998f9866324e.png)
but I get only "Something goes wrong"

**Comment by tkashkin** [comment]
I have tried gnome-software on elementary and it doesn't work for me as well.

Is it actually able to install any other flatpak bundle?

**Comment by Tids** [comment]
Is there any reason why you dont provide a flatpak repo or submit it to [Flathub](https://github.com/flathub/flathub/wiki/App-Submission) (wich is the default repo for gnome-software / KDE-discover on most distros)?

Because I dont think any software market right now supports standalone flatpaks.

**Comment by tkashkin** [comment]
@Tids 

#183
https://github.com/flathub/flathub/pull/486#issuecomment-405053777

**Comment by Tids** [comment]
@tkashkin I agree with them. I was very curious how you managed to support a flatpaks from another flatpaks, since they are sandboxes, they shouldn't even know that they exist.

However, in this case it would maybe a good idea to remove the flatpaks tutorial from the main site, or add a comment that your app is a software center class application, that can not be supported be flatpak itself in a good way. 🤔

**Comment by pyroxar** [comment]
Good idea is to add information how to install GameHub form flatpak by use terminal.

**Comment by AsavarTzeth** [comment]
The provided file is a [flatpak bundle file](http://docs.flatpak.org/en/latest/single-file-bundles.html) not a `.flatpakref` or `.flatpakrepo`. You need to first download it and then install it. No idea why `gnome-software` does not support bundle files.

Here is how you install it from the command line:

```
curl -OL https://github.com/tkashkin/GameHub/releases/download/0.13.1-1-master/GameHub-bionic-0.13.1-1-master-1f713f3.flatpak
flatpak install GameHub-bionic-0.13.1-1-master-1f713f3.flatpak
```
