### ISSUE TITLE
Adhere to XDG Base Directory Spec

### ISSUE THREAD

**Issue by JonnyCodewalker** [tkashkin/GameHub#188]
Currently Gamehub saves configuration files and data in ~/.var/com....../.

It would be an improvement to rely on the XDG Base Directory Spec, storing the data in ~/.config ~/.cache etc instead. 

The full spec can be found here:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by tkashkin** [comment]
GameHub follows XDG specs and stores its data in `$XDG_CACHE_HOME`.

flatpak overrides XDG directories so each flatpak app stores its data in `~/.var` 

The only exception is `dconf` settings, as `dconf` requires a connection to user daemon. `dconf` settings are stored in `~/.config` even for flatpak apps.
