### ISSUE TITLE
Cannot use path containing ~ character

### ISSUE THREAD

**Issue by camelCaseSucks** [tkashkin/GameHub#190]
###### Expected behavior
I should be able to use folder names containing `~`

###### Actual behavior
Any `~` in the path is replaced by contents of `$HOME`. This should only happen if the `~` is at the start of the path and followed by `/` or `USERNAME/`.

###### Steps to reproduce
Open the settings menu and set any path, e.g. "collection directory", to `/tmp/~test`. Close & open the settings menu. The path will now be `/tmp/home/USERNAMEtest`

###### Version and environment

```
Version: 0.13.1-1f713f3-master
Branch:  master
Commit:  1f713f3 (1f713f3f3d13385833106c9fc8a9cfccafc0a52b)
Distro:  NAME=Arch Linux
DE:      KDE
```

**Comment by tkashkin** [comment]
It should be fixed in latest commit.
