### ISSUE TITLE
Main executable can't be detected

### ISSUE THREAD

**Issue by sprite-1** [tkashkin/GameHub#192]
###### Expected behavior
It should install without a hitch

###### Actual behavior
After it downloads the exxe installer from GOG, it shows an error
 
![image](https://user-images.githubusercontent.com/33685433/52214369-6dacee80-28cc-11e9-84a9-fdfe0f8b961d.png)

###### Steps to reproduce
1.Pick a Windows-only game from your GOG library.
2. Install and wait for it to download.
3. You will get a notification like my screenshot above.

###### Version and environment

```
Version: 0.13.1-0abbc80-dev
Branch:  dev
Commit:  0abbc80 (0abbc80eca44311022c06d5c6e967004fd31fffa)
Distro:  elementary OS 5.0 Juno
DE:      Pantheon
```

**Comment by Lucki** [comment]
I can confirm this with Wizorb from Humble and Worms Forts: Under Siege from GOG (manually installed because the install button on the detail site is grayed out for whatever reason). Haven't tested any more.

**Comment by neuromancer** [comment]
How did you installed that game (innoextract or wine/proton). Also, can you look for the goggame-*.info file in the game directory and upload it here?

**Comment by sprite-1** [comment]
`innoextract` doesn't work at all.  It just creates the directory structure but it doesn't have anything else.
![image](https://user-images.githubusercontent.com/33685433/52223646-0baab400-28e1-11e9-925b-1eb4f9f25c2c.png)

Proton manages to open the installers but any game refuses to launch. Only the WINE method had any half-decent chance of running the game. After installation via vanilla WINE, it pops up the screenshot I had on the first post above. I have to manually set the executable to point to the right file on the game's settings afterwards though.

This is the goggame-*.info file inside the `_gamehub_game_root` folder.
[goggame-1180040534.info.txt](https://github.com/tkashkin/GameHub/files/2829023/goggame-1180040534.info.txt)

**Comment by Lucki** [comment]
There's no such file for my tested Worms and Ceasar 3, only a `goggame.dll`.

**Comment by neuromancer** [comment]
Which version of `innoextract` are you using?

**Comment by neuromancer** [comment]
> There's no such file for my tested Worms and Ceasar 3

Are these games packed with dosbox? (in that case, there is no need to setup the executable)

**Comment by Lucki** [comment]
> Are these games packed with dosbox?
No. They're normal Windows games. `innoextract 1.7-3`

**Comment by sprite-1** [comment]
I use the version that comes with elementary OS 5.0, as far as I'm aware, it was already preinstalled because when I tried `sudo apt install innoextract`, it just says it's already installed

**Comment by tkashkin** [comment]
This installer uses InnoSetup 5.6.2 and can't be extracted with innoextract 1.7.

```
[DEBUG]  [Utils.run] {'/usr/bin/innoextract' '-e' '-m' '-d' '/mnt/LinuxStorage/Games/GOG/DISTRAINT_Deluxe_Edition' '--gog' '/mnt/LinuxStorage/Games/_Collection/GOG/DISTRAINT - Deluxe Edition/setup_distraint_deluxe_edition_1.0_(26480).exe'}; dir: '/mnt/LinuxStorage/Games/_Collection/GOG/DISTRAINT - Deluxe Edition'
Warning: Unexpected setup data version: 5.6.2 (unicode)
Warning: Unexpected Auto Boolean value: 19
Warning: Unexpected Auto Boolean value: 20
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected trailing byte in UTF-16 string.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Warning: Unexpected data while converting from UTF-16LE to UTF-8.
Stream error while parsing setup headers!
 ├─ detected setup version: 5.6.2 (unicode)
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 8 warnings.
[DEBUG]  [Worker] Utils.run_thread finished
```

It should probably work with [innoextract dev snapshot](http://constexpr.org/innoextract/files/snapshots/) or if you install it with Wine/Proton.

Related:
* https://github.com/dscharrer/innoextract/issues/73
* https://github.com/dscharrer/innoextract/issues/74

**Comment by tkashkin** [comment]
Now game files should be moved from `_gamehub_game_root` to installation directory and automatic executable detection should work.

**Comment by neuromancer** [comment]
It works!. (It only fails for a few games like Nox that don't have `goggame-*.info` file)
