### ISSUE TITLE
Improvement: refactor the overlay code into a new source file

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#195]
The overlay functionality is located in the `Game.vala` file:

https://github.com/tkashkin/GameHub/blob/dev/src/data/Game.vala#L202-L437

It could be a good idea to refactor that code into a new source file (e.g. `Overlay.vala`, maybe?)

**Comment by tkashkin** [comment]
This code sets up overlays and its options for a game and is more related to the game itself. I don't think it needs to be refactored now.

Actual overlay code is already separated: https://github.com/tkashkin/GameHub/blob/dev/src/utils/FSOverlay.vala.
