### ISSUE TITLE
Current downloads are no longer visible on the top

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#196]
Using the latest `dev` revision,  the games that are downloading are not longer visible in the top of the screen:

![no-downloads](https://user-images.githubusercontent.com/110782/52750894-42ad5380-2fcc-11e9-83f9-39ad171fb585.png)

This means you cannot cancel them.

**Comment by tkashkin** [comment]
Nothing was changed here recently, so it should work.
What exactly happens when you try to open downloads list?

**Comment by neuromancer** [comment]
After disable and enable the dark team option, the icon is now an arrow and shows the downloads. I'm going to close it until I understand how to reproduce it..
