### ISSUE TITLE
No option to use wine compatability 

### ISSUE THREAD

**Issue by dmmcd** [tkashkin/GameHub#201]
Voidlinux with everything up to date. I use the appimage version which I have to extract because of a pixbuf error.
---
Loaded up Gamehub today and it wasn't showing any of my games as being installed.

I tried manually importing the games which worked fine for Linux native games but would not work for Windows based games.

I then tried installing a game from GOG but there was no option in the dropdown menu to use wine compatability, the only available option is "Custom Script". Verified this for any non-native game.

I've tried clearing the cache and resetting the dconf entries but there's still no wine compatability option. Steam is installed.

**Comment by tkashkin** [comment]
Do you actually have Wine installed and available in `$PATH`? Check `which wine`.

**Comment by dmmcd** [comment]
That gave me the hint I needed :)

I don't tend to install wine on Voidlinux. 
Previously I'd installed a proton compability build and I'm assuming I had symlinked it to /usr/bin/wine so Gamehub was picking that up, but as it was set up some time ago I'd forgotten how I went about it.
