### ISSUE TITLE
Default generic game cover when manually adding a new game

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#204]
When a user adds a new game manually, GameHub uses a gray background:

![new](https://user-images.githubusercontent.com/110782/53261698-7581d680-36b3-11e9-904a-b6f2e567c332.png)

It could be nice to have a default generic game cover instead. Even one with the GameHub logo is better than the gray background. Another interesting option is to try fetch a game cover / image using [IGDB](https://igdb.github.io/api/).

**Comment by tkashkin** [comment]
Default game icon is added.

I have tried IGDB API and unfortunately their covers are inconsistent. I don't think it's worth implementing now.

**Comment by neuromancer** [comment]
It works!. Thanks for giving the IGDB API a shot.

**Comment by neuromancer** [comment]
Oh, you implemented IGDB. Is it their API working better now?

**Comment by tkashkin** [comment]
@neuromancer IGDB images are inconsistent and GameHub uses IGDB only for metadata.

GameHub uses https://steamgriddb.com and https://steam.cryotank.net to download images.
