### ISSUE TITLE
Filter by operating system and another improves

### ISSUE THREAD

**Issue by trprado** [tkashkin/GameHub#207]
Add support to filter game list by operating system and possibility to add new tags. Another possibility is add fences and put games automatic by tag like the Gnome Desktop.

**Comment by tkashkin** [comment]
> Add support to filter game list by operating system

There are no such filters implemented now, but there's an option in settings to hide non-Linux games. I may implement more detailed OS filters in future.

> possibility to add new tags

It's possible to add new tags. Open game's properties (right click on game) and select/add tags in properties dialog.
One possible improvement to this would be to allow to select multiple games and edit their tags simultaneously like Steam client allows.

> Another possibility is add fences and put games automatic by tag like the Gnome Desktop.

I'm not sure what exactly do you mean, please explain.

**Comment by trprado** [comment]
Like this image, but for game categories.

![image](https://user-images.githubusercontent.com/4511706/54552466-e5237280-498e-11e9-81fc-89d79db23b7a.png)

**Comment by tkashkin** [comment]
OS filters [are implemented](https://github.com/tkashkin/GameHub/issues/247#issuecomment-502489916).
