### ISSUE TITLE
Clicking on Install Steam does nothing. Steam is installed but not detected.

### ISSUE THREAD

**Issue by twisty1** [tkashkin/GameHub#21]
GameHub is not detecting that Steam is installed on Arch Linux. 

Steam package is installed via pacman and runs fine. Logged in can install and run games from it. KDE application launcher recognizes it and has several icons for Steam including for the runtime and native versions. steam.desktop is installed under /usr/share/applications. Packagekit.qt5 is installed to provide pacman package support to KDE apps such as Discover. 

Distro: Arch Linux (current)
Gamehub version: 0.5.4 (from release tarball)
Steam package: steam 1.0.0.54-3
Desktop: KDE Plasma 5.13.3
Kernel: 4.17.6-1-ARCH 64-bit

**Comment by tkashkin** [comment]
@twisty1
It's expected for now, because package detection is implemented only for Debian-based distros. https://github.com/tkashkin/GameHub/blob/0.5.4/src/utils/Utils.vala#L86-L94

Package detection should be:
* implemented for other distros (maybe using PackageKit if it supports pacman)
* or replaced with `steam` existence in $PATH check
* or removed entirely as it's not so important in this case

**Comment by twisty1** [comment]
@tkashkin 
Okay thanks, guess we'll have to wait for the enhancement. I've made a preliminary package at the following anyhow as GOG etc seems to work fine: https://aur.archlinux.org/packages/gamehub/

**Comment by LeandroStanger** [comment]
@twisty1 Use the flatpak version: https://github.com/tkashkin/GameHub/releases

**Comment by twisty1** [comment]
@LeandroStanger thanks but I'd rather replace the distro specific check if we can. Looks like we just need to check what is returned from the command "pacman -Qi steam" is true or false.

**Comment by tkashkin** [comment]
@twisty1 what's the full output of `pacman -Qi <package>` when it's installed or not?

I'll try to use PackageKit to cover more distros if possible.

**Comment by twisty1** [comment]
@tkashkin 

This seems to at least turn let Gamehub detect that Steam is there (by modifying that section you mentioned), but I'm not prompted for authentication.

var output = Utils.run({"pacman", "-Qi", package});
return "Install Reason" in output;

**Comment by tkashkin** [comment]
@twisty1
I need full output of `pacman -Qi` and `pacman -Qqi`.
It may be affected by locale, so test it if you can.

**Comment by twisty1** [comment]
The output of -Qqi is below. I imagine any output will definitely be affected by locale.

```
$ pacman -Qqi steam
Name            : steam
Version         : 1.0.0.54-3
Description     : Valve's digital software delivery system
Architecture    : x86_64
URL             : http://steampowered.com/
Licenses        : custom
Groups          : None
Provides        : None
Depends On      : bash  desktop-file-utils  hicolor-icon-theme  curl  dbus  freetype2  gdk-pixbuf2  ttf-font  zenity
                  lib32-libgl  lib32-gcc-libs  lib32-libx11  lib32-libxss  lib32-alsa-plugins
Optional Deps   : steam-native-runtime: steam native runtime support [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 2.76 MiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Wed 06 Dec 2017 07:44:27 AEST
Install Date    : Wed 27 Jun 2018 21:04:39 AEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by LeandroStanger** [comment]
@tkashkin  https://wiki.archlinux.org/index.php/Steam

**Comment by twisty1** [comment]
@tkashkin 

Okay no worries, removing it might be better from a cross distro point of view anyway especially if you are already checking for the .steam home directory.

The output from that command is:

```
$ lsb_release -ds 2>/dev/null || cat /etc/*release 2>/dev/null | head -n1 || uname -om
"Arch Linux"
```

**Comment by tkashkin** [comment]
@twisty1
Are these correct on Arch:
* Steam is installed in `~/.steam`
* `~/.steam/steam/config/loginusers.vdf` exists after signing in in Steam client
* SteamApps path is `~/.steam/steam/steamapps/`
* `~/.steam/steam/steamapps/libraryfolders.vdf` exists

**Comment by twisty1** [comment]
@tkashkin 

- Steam is installed to /usr etc.  However `~/.steam` exists after running it as the user
- `~/.steam/steam/config/loginusers.vdf`  exists after signing into the Steam client
- `~/.steam/steam/steamapps/` exists and has stuff in it, but my library folder is set to `~/.local/share/Steam` (not sure if this matters)
- `~/.steam/steam/steamapps/libraryfolders.vdf` does exist. Also this file exists in the .local/share/Steam path too.

**Comment by tkashkin** [comment]
@twisty1 

Try https://github.com/tkashkin/GameHub/releases/tag/0.5.5

Edit PKGBUILD to pass `arch` as distro:
```sh
meson build --prefix=/usr -Ddistro=arch
```

While there's no Arch-specific code now, there may be in future.

**Comment by twisty1** [comment]
@tkashkin not sure if I have to do something special such as wipe the config again from scratch but although it's now detecting Steam its not showing me any of my Steam games.

**Comment by twisty1** [comment]
@tkashkin 

A combination of your suggestions and the updated package seems to have sorted it out and now all 3 services including Steam are working great. Incidentally although my Steam profile was public my games were not, so I set those as public too to on a hunch.

Thanks for all your help! I've updated the Arch package to the latest version as well.

**Comment by tkashkin** [comment]
@twisty1

Maybe it should be somehow shown in the app. Few months ago Steam added more privacy options, but set them to `private` by default without notifying users. Many people may still not know about recent changes.

**Comment by ethchest** [comment]
I had the same issue with gamehub installed via flatpak, but steam installed normally. Now trying the normal way again, even with API key it wouldn't work, maybe some flatpak thing.

**Comment by tkashkin** [comment]
@ethchest is it not finding Steam or something else is happening? It should be possible to set Steam path in settings.

**Comment by ethchest** [comment]
I think I set the right path and even the API key, but the button at the gui/start still was showing as if steam was not configured. There was also no error in terminal or something, so not sure what to check. I will try again soon maybe then it will work or a better error appears.

**Comment by tkashkin** [comment]
@ethchest check #74, should be the same issue. Flatpak version expects flatpak Steam to be installed.

**Comment by ethchest** [comment]
Thanks. Now with 0.11.1 and non-flatpak gamehub it works. Just one thing, should it detect already installed steam games?

**Comment by tkashkin** [comment]
@ethchest Yes, it should detect installed games.
Check if [`steamapps` and `libraryfolders` paths](https://github.com/tkashkin/GameHub/blob/master/src/utils/FSUtils.vala#L61-L62) are correct and games are installed in `steamapps` folder or in one of the folders listed in `libraryfolders.vdf`.
