### ISSUE TITLE
Not all games from accounts are detected

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#210]
###### Expected behavior
All games in library would be detected.

###### Actual behavior
Some games aren't detected from GOG. Currently only Fallout Classic that I know. Both Fallout 2 and Fallout Tactics are detected though.

###### Steps to reproduce
Connect to account. Search.

###### Version and environment
Version: 0.13.1-e1d8f5c-dev
Branch:  dev
Commit:  e1d8f5c (e1d8f5c71c833568714b3c21b383a721cf35f0c2)
Distro:  Ubuntu 18.04.2 LTS
DE:      KDE

**Comment by tkashkin** [comment]
There was a problem in database query which resulted in `Fallout Classic` games on GOG to be treated as merged while there were not. It should be fixed in db1b38a.
