### ISSUE TITLE
Disappearance of custom installed wine games from library

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#211]
###### Expected behavior
New custom installed wine game would be added and stay in library.

###### Actual behavior
Once installed the custom installed wine game disappears upon restarting GameHub.
Note: I have a Linux native game that works fine (Starsector).

###### Steps to reproduce
Using GOG Fallout Classic installer (setup_fallout_2.1.0.18.exe). 
Install game using the interface. Click on game to start and select wine64.
Run game (game runs).
Exit GameHub.
Restart GameHub (game is gone).

###### Version and environment
Version: 0.13.1-e1d8f5c-dev
Branch:  dev
Commit:  e1d8f5c (e1d8f5c71c833568714b3c21b383a721cf35f0c2)
Distro:  Ubuntu 18.04.2 LTS
DE:      KDE

**Comment by neuromancer** [comment]
Maybe the executable isn't correctly detected? (in that case the game will show as uninstalled)

**Comment by tkashkin** [comment]
It should be fixed in db1b38a (same problem as in #210).
