### ISSUE TITLE
Double click to start games

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#213]
Problem:
Currently games are started with one click. This can sometimes cause problems when a game gets clicked accidentally as it wastes times starting a game or starting Steam.

Solution:
Require double click to start game. Change the graphic after the first click to show that the second click will activate with the graphic returning to normal if not clicked again after a few seconds. If there is a second click, change the graphic again to show that the game is booting up.

**Comment by neuromancer** [comment]
There is some discussion about the initial implementation of clicking on games [here](https://github.com/tkashkin/GameHub/issues/92).
