### ISSUE TITLE
Add a recent games screen

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#215]
Steam is showing a preview of their "recent games" screen: 

![Image of Steam](
https://www.gamingonlinux.com/uploads/articles/article_media/12890080651553200229gol1.png
)

I think it could be nice to have this kind of initial screen in GameHub. Its useful to continue playing games that you recently used. Additionally, since it will only show a very limited amount of them,  it will be loaded quickly while GameHub parses the rest of the games.

**Comment by tkashkin** [comment]
I don't think that this screen will differ from current grid sorted by launch time. There's no additional info to show on this screen.

**Comment by tkashkin** [comment]
Closing for now. May be reopened in future if there are actual ideas for that screen.
