### ISSUE TITLE
In grid names with long titles affect the ability to mouse select other tiles

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#219]
###### Expected behavior
To be able to mouse select all titles in grid.

###### Actual behavior
Some games with long titles interfere with the ability to mouse select the tiles above them. For some it completely stops selection, for some this reduces the selectable area. This does not affect keyboard selection.

Game examples: 
Star Wars Knights of the Old Republic II: The Sith Lords # complete
Warhammer 40,000: Dawn of War II - Chaos Rising # partial
Broken Sword 1 - Shadow of the Templars: Director's Cut # partial
Broken Sword 2 - The Smoking Mirror: Remastered # partial
Chronicles of Riddick: Assault on Dark Athena, The # partial

###### Steps to reproduce
Use games grid. Place mouse on long name tile and then move to the tile above it. Sometimes if the tile is mouse selected before from the side or top it can be selected, but when pointed over from the bottom (the long name tile) it becomes non-selectable and stays so.

###### Version and environment
Version: 0.13.1-41d8c8f-dev
Branch:  dev
Commit:  41d8c8f (41d8c8f2d6bbc04731ee627ad418016b9a814fd4)
Distro:  Ubuntu 18.04.2 LTS
DE:      KDE

**Comment by tkashkin** [comment]
Fixed.
