### ISSUE TITLE
GOG Query does not appear to recieve all pages

### ISSUE THREAD

**Issue by MessedUpHare** [tkashkin/GameHub#22]
The GOG Query does not appear to recieve more than 1 page from the API.

The GOG API paginates more than 100 results by default, but i assume it's configurable via productsPerPage.

Pages are indicated via:
{
page: 1
...
totalPages: 4
...
}

Further pages can be accessed via the URI
https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=1
https://embed.gog.com/account/getFilteredProducts?mediaType=1&page=2

**Comment by tkashkin** [comment]
@MessedUpHare Thanks for reporting, fixed.
