### ISSUE TITLE
Improve search functionality

### ISSUE THREAD

**Issue by cafehaine** [tkashkin/GameHub#223]
Hi, great project!
I really like the gui, however one thing that is lacking compared to Steam's gui is a shortcut (ctrl+f) to select the "search" widget, and starting the first game when pressing return while searching.

**Comment by tkashkin** [comment]
@cafehaine try 5bf5bdd.

**Comment by cafehaine** [comment]
@tkashkin works great to focus the search bar

**Comment by tkashkin** [comment]
@cafehaine `Enter` in search entry should now run first matching game.

**Comment by cafehaine** [comment]
Works perfectly, thanks a lot!
