### ISSUE TITLE
Merge error with 'Mark of the Ninja: Remastered'

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#224]
Mark of the Ninja: Remastered does not show when library is merged. Mark of the Ninja has two Steam icons possibly for related reasons. Likely related to issue #210.

###### Version and environment
Version: 0.13.1-f9fd217-dev
Branch:  dev
Commit:  f9fd217 (f9fd2173758dbf09991ce47affaffdcba8d3d767)
Distro:  Ubuntu 18.04.2 LTS
DE:      KDE

**Comment by tkashkin** [comment]
It should probably be fixed now.

**Comment by tkashkin** [comment]
@glaere is this solved? Both games should be shown as tabs in game details when merged.

There is another related problem with merged games. List and grid game widgets will always show/run first game of merged games list and will not switch automatically when source tab changes.

I will try to fix it later, but it probably will not handle cases like this when both games are from same source.
