### ISSUE TITLE
Add installed game list to right click on desktop icon

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#225]
I use KDE with a dock. Many items in that dock allow additional functionality directly through a right click (open file, move to folder, etc). It might be useful to add all installed games to the GameHub icon on the dock to make it easy to see and start all installed games straight from the desktop. The most recently played game could be right at the top separated by a spacer for easy access.

**Comment by tkashkin** [comment]
3084beb implements `libunity` dynamic quicklist as well as `libunity` progressbar.

It should show favorite games in menu while GameHub is running.

**Comment by tkashkin** [comment]
I can't think of a way to show and update recents list without additional database queries and I don't think that recents list is really necessary.

Favorites list should be good enough (at least for now).
