### ISSUE TITLE
Steam-native support

### ISSUE THREAD

**Issue by Jimi-James** [tkashkin/GameHub#226]
Steam-native is a project to make Steam use Native Runtime--all of the native versions of libraries installed on a Linux system--rather than its own Steam Runtime. Depending on your distro, it can work quite well--even almost universally better than Steam Runtime.

But I'm noticing that all the features of GameHub that involve launching the Steam client, from installing a game, to running a game, to configuring things--even the API key generation link in the settings--opens in Steam Runtime, rather than Native.

Instead of forcing me to do `ln -s /usr/bin/steam-native /usr/local/bin/steam`, which I'd rather avoid, can we have a toggleable option in GameHub that makes it use `steam-native` as its Steam binary, rather than just `steam`?

**Comment by tkashkin** [comment]
GameHub does not run `steam` binary directly. Instead it does everything via `steam://` URL protocol.

You need to set steam-native as `steam://` protocol handler if it comes with a separate `.desktop` file or edit `.desktop` file of Steam to use `/usr/bin/steam-native`.

**Comment by Jimi-James** [comment]
Oh, does `steam://` call the default `.desktop` file, then? If so, that sounds like I can just set `~/.local/applications/steam.desktop` to the Native Runtime? That would work.

**Comment by tkashkin** [comment]
`.desktop` file override seems to be the right solution. Anyway I don't think anything can be done on GameHub side, except maybe calling actual binaries instead of opening an URL.

**Comment by Jimi-James** [comment]
Oh, it looks like I've actually already had the `.desktop` file in .local/share/applications overridden to Native Runtime this whole time, and it hasn't been enough. I'm going to do more research on this later, either how to choose a binary with the URL, or how to otherwise override what the URL opens up, whether it's a binary, a `.desktop` file, or something else.

**Comment by tkashkin** [comment]
@Jimi-James try https://github.com/tkashkin/GameHub/issues/117#issuecomment-435633519

**Comment by Jimi-James** [comment]
You helped me figure it out! The entire time, an extremely outdated `~/.local/share/applications/mimeinfo.cache` file from countless years ago was *prioritizing steam-runtime.desktop over steam.desktop*. Fixing that fixed this issue.
