### ISSUE TITLE
GameHub may fail to recognize installed Steam games on a case-sensitive filesystem

### ISSUE THREAD

**Issue by Jimi-James** [tkashkin/GameHub#227]
###### Expected behavior

GameHub sees which Steam games are actually installed.

###### Actual behavior

GameHub sees all of my Steam games, but lists every single one as Not installed.

###### Steps to reproduce

1. Run a case-sensitive filesystem (in other words, run Linux).

2. Have a Steam client installed that decided to name its steamapps folder "SteamApps", with a capital S and A, instead of "steamapps".

3. Be unable to change anything about that situation, because Steam actually automatically creates and deletes a symbolic link that covers that case sensitivity problem when it needs to--meaning I can't make my own, as Steam will just delete it whenever it decides it should.

It seems that GameHub is probably only checking `~/.steam/steam/steamapps`, and not *also* checking `~/.steam/steam/SteamApps`. I'm pretty sure of that because this bug was actually gone when I tried temporarily making a symlink to cover the case sensitivity. Should be an easy fix to make it check both?

###### Version and environment

```
$ com.github.tkashkin.gamehub -v
Version: 0.13.1-f9fd217-makepkg
Branch:  makepkg
Commit:  f9fd217 (f9fd2173758dbf09991ce47affaffdcba8d3d767)
Distro:  Arch Linux
DE:      XFCE
```

**Comment by tkashkin** [comment]
> It seems that GameHub is probably only checking `~/.steam/steam/steamapps`, and not also checking `~/.steam/steam/SteamApps`.

Yes.

> Should be an easy fix to make it check both?

Not as easy as I would want, because `GLib.File` API does not have a way to work with case-insensitive paths.
However there is already a code to find directories ignoring case so it shouldn't be too hard.

> I'm pretty sure of that because this bug was actually gone when I tried temporarily making a symlink to cover the case sensitivity.

Wouldn't it work if you rename `SteamApps` to `steamapps` manually instead of creating a symlink?

**Comment by Jimi-James** [comment]
I've read about users trying that and ending up with their entire libraries deleted by some other bug. That might be all fixed by now, but I'd definitely rather not risk it.

**Comment by tkashkin** [comment]
@Jimi-James try f6b77e8. Now GameHub should find Steam directories ignoring case.

**Comment by Jimi-James** [comment]
I'm suddenly getting a missing build-dep when I try this new commit?

```
==> Making package: gamehub-git 0.13.1.1.master.r0.g1f713f3-1 (Fri 29 Mar 2019 09:52:24 AM PDT)
==> Retrieving sources...
  -> Updating GameHub git repo...
Fetching origin
==> Validating source files with sha256sums...
    GameHub ... Skipped
==> Cleaning up...
==> Making package: gamehub-git 0.13.1.1.master.r0.g1f713f3-1 (Fri 29 Mar 2019 09:52:24 AM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating GameHub git repo...
Fetching origin
==> Validating source files with sha256sums...
    GameHub ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of GameHub git repo...
Cloning into 'GameHub'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Updated version: gamehub-git 0.13.1.48.dev.r0.gf6b77e8-1
==> Sources are ready.
==> Making package: gamehub-git 0.13.1.48.dev.r0.gf6b77e8-1 (Fri 29 Mar 2019 09:52:26 AM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
The Meson build system
Version: 0.49.2
Source dir: /home/jimi/Backup/Computers/Linux/pkg/AURBUILD/gamehub-git/src/GameHub
Build dir: /home/jimi/Backup/Computers/Linux/pkg/AURBUILD/gamehub-git/src/GameHub/build
Build type: native build
Project name: com.github.tkashkin.gamehub
Project version: 0.13.1
Appending CFLAGS from environment: '-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/home/jimi/Backup/Computers/Linux/pkg/AURBUILD/gamehub-git/src=/usr/src/debug -O0'
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Appending CPPFLAGS from environment: '-D_FORTIFY_SOURCE=2'
Native C compiler: ccache cc (gcc 8.2.1 "cc (GCC) 8.2.1 20181127")
Appending LDFLAGS from environment: '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
Native Vala compiler: valac (valac 0.44.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring com.github.tkashkin.gamehub.policy using configuration
Found pkg-config: /usr/bin/pkg-config (1.6.0)
Configuring ProjectConfig.vala.in.in.in using configuration
Dependency granite found: YES 5.2.3
Dependency gdk-3.0 found: YES 3.24.7
Dependency webkit2gtk-4.0 found: YES 2.24.0
Dependency glib-2.0 found: YES 2.60.0
Dependency json-glib-1.0 found: YES 1.4.4
Dependency gee-0.8 found: YES 0.20.1
Dependency sqlite3 found: YES 3.27.2
Dependency libxml-2.0 found: YES 2.9.9
Dependency polkit-gobject-1 found: YES 0.116
Found CMake: /usr/bin/cmake (3.14.0)
Dependency unity found: NO (tried pkgconfig and cmake)

src/meson.build:25:0: ERROR:  Dependency "unity" not found, tried pkgconfig and cmake
```

Which unity? I just searched and found many packages with "unity" in their name, and none of them seemed like obvious build dependencies to me. I really hope this isn't suddenly depending on the Ubuntu DE that I'm not using.

**Comment by tkashkin** [comment]
@Jimi-James it now depends on [`libunity`](https://aur.archlinux.org/packages/libunity/) (#225). It provides features like progressbars, counters and quicklists. It's not Unity DE and it works on multiple DEs.

**Comment by Jimi-James** [comment]
Oh, OK cool. I was a little confused because that one almost seemed like a winner when I saw it, except its description (at least on Arch) only says it's for interacting with something I don't have installed (Unity shell). Sounds like that description wasn't entirely accurate.

**Comment by tkashkin** [comment]
@Jimi-James does it work? Reopen if it doesn't or if you find related bugs.

**Comment by Jimi-James** [comment]
Oh, right, sorry! I had just finished successfully compiling and was about to test it when something else suddenly demanded my attention all day. Testing now, and... yup, it worked!
