### ISSUE TITLE
Battlenet error

### ISSUE THREAD

**Issue by jatin-cbs** [tkashkin/GameHub#229]
I tried to install battlenet for overwatch but i dont think normal wine is able to run it, it may need wine tkg builds which are created by lutris and esync would be great to improve performance Esync and tk builds + DXVK lutris provides everything I dont know for what I use gamehub.

**Comment by neuromancer** [comment]
Battlenet works fine with latest release of wine-staging. If you install it in your distro, GameHub should be able to use it. You can also try Proton (which has the Esync patches already applied) if you have steam installed.

**Comment by jatin-cbs** [comment]
How can i add DXVK to it for overwatch ?

**Comment by jatin-cbs** [comment]
And i am unable to find BattleNet. Its not on the game list how to add it ?

**Comment by jatin-cbs** [comment]
please a good documentation or video is needed for custom emulators, its just confusing setting up directories and all..

**Comment by jatin-cbs** [comment]
We need a documentation or video for this too confusing, lutris is just 1 click install..

**Comment by jatin-cbs** [comment]
and do i have to set everything executable and everything myself ?

**Comment by jatin-cbs** [comment]
and on my non debian machine (fedora) flatpak is not even installing 
![Screenshot from 2019-04-01 18-33-25](https://user-images.githubusercontent.com/40650341/55329677-d4a1ea80-54ac-11e9-989f-01b651a21fe6.png)

no documentation and not even able to install a flatpak. I think i have to go back to lutris gamehub wont work for me

**Comment by Lucki** [comment]
[This describes what you probably want.](https://github.com/tkashkin/GameHub/issues/106#issuecomment-435629437)
Use Proton, it has DXVK and esync built in.

**Comment by jatin-cbs** [comment]
But by any means i cant get gamehub running on centos or fedora (rpm based). Deb package wont work, git package the dependencies for rpm are not mentioned, flatpak not working at all.. What to do ?

**Comment by neuromancer** [comment]
@jatin-cbs let's keep one bug for each issue. Please open another issue with your installation error in centos/fedora. Also, keep in mind that GameHub is not Lutris. These are programs created with two different features in mind. If you want a one click installation of third-party launchers using custom wine builds, you should use Lutris.

**Comment by neuromancer** [comment]
> How can i add DXVK to it for overwatch ?

You can use winetricks for that (that's integrated in GameHub using the button in games using wine)
