### ISSUE TITLE
Fix Games window size

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#23]
![captura de tela de 2018-07-20 19-23-23](https://user-images.githubusercontent.com/26097419/43028037-d2eb27aa-8c53-11e8-92cc-e5c0eaf100f2.png)

**Comment by tkashkin** [comment]
@LeandroStanger Game is controlling its windows, not launching app. Most games have fullscreen option or react to some hotkey like `Alt + Enter`.
