### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by tim77** [tkashkin/GameHub#234]
#### Not issue, just info:

📦 GameHub RPM package in [COPR](https://copr.fedorainfracloud.org/coprs/atim/gamehub/)

#### How to install:
```shell
sudo dnf copr enable atim/gamehub -y && sudo dnf install gamehub -y
```
#### Run:
```
com.github.tkashkin.gamehub
```

**Comment by lewellyn** [comment]
Packages are being tracked in #156. There are a few of us working on various distros' packages. @hogarthj has been working on COPR packaging for a while. It might be worthwhile for you two to join forces. :)

**Comment by tim77** [comment]
Wow nice indeed. I [searched](https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=gamehub) and didn't found any COPR repo. Now GameHub in official repos and [ready for testing](https://bodhi.fedoraproject.org/updates/gamehub-0.13.1.77-1.fc29).

**Comment by lewellyn** [comment]
I'd suggest taking into account [https://github.com/tkashkin/GameHub/issues/156#issuecomment-481709822](the suggestion made for my package to include debugging symbols) as well as #162. It'd also be more useful in general if you discussed on #156 so that everyone working on packaging has one place to look for information on making their packages better.

Additionally, I'd suggest building against libmanette. I don't know if you tried to or not, as I only looked at the build log. Getting to the actual .spec from a bodhi/koji page always gets me lost. :(

**Comment by PanagiotisS** [comment]
> I'd suggest taking into account [the suggestion made for my package to include debugging symbols](https://github.com/tkashkin/GameHub/issues/156#issuecomment-481709822) as well as #162. It'd also be more useful in general if you discussed on #156 so that everyone working on packaging has one place to look for information on making their packages better.
> 
> Additionally, I'd suggest building against libmanette. I don't know if you tried to or not, as I only looked at the build log. Getting to the actual .spec from a bodhi/koji page always gets me lost. :(

Following the above I changed the `%meson` macro in the `.spec` file as follows and I do not encounter the compatibility run issue anymore:

```spec
%build

CFLAGS="$CFLAGS -O0" meson \
    --buildtype=debug \
    --prefix=%{_prefix} \
    --libdir=%{_libdir} \
    --libexecdir=%{_libexecdir} \
    --bindir=%{_bindir} \
    --sbindir=%{_sbindir} \
    --includedir=%{_includedir} \
    --datadir=%{_datadir} \
    --mandir=%{_mandir} \
    --infodir=%{_infodir} \
    --localedir=%{_datadir}/locale \
    --sysconfdir=%{_sysconfdir} \
    --localstatedir=%{_localstatedir} \
    --sharedstatedir=%{_sharedstatedir} \
    --wrap-mode=%{__meson_wrap_mode} \
    --auto-features=%{__meson_auto_features} \
    %{_vpath_srcdir} %{_vpath_builddir} \
    %{nil}

%meson_build
```

Explanation:

Looking at the file `/usr/lib/rpm/macros.d/macros.meson` you can see how the `%meson` macro expands. Therefore I copied the macro and changed `--buildtype=debug` which was `--buildtype=plain`, and included the `CFLAGS="$CFLAGS -O0"`.

My system:
```bash
$lsb_release 
Distributor ID: Fedora
Description:    Fedora release 29 (Twenty Nine)    
Release:        29
Codename:       TwentyNine
$ uname
5.0.7-200.fc29.x86_64
```

**Comment by PanagiotisS** [comment]
> Additionally, I'd suggest building against libmanette. I don't know if you tried to or not, as I only looked at the build log. Getting to the actual .spec from a bodhi/koji page always gets me lost. :(

Libmanette is not part of Fedora 29
The .spec includes the following

```
%if 0%{?fedora} >= 30
BuildRequires:  pkgconfig(manette-0.2)
%endif
```

**Comment by tkashkin** [comment]
Closing this issue in favor of #156.
