### ISSUE TITLE
Feature request: integrate the support for frame limiting using libstrangle

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#235]
Some old games requires to limit the amount of frames per seconds to play it (e.g Sim City 3000 when you try to scroll the map). Fortunately, [libstrange](https://gitlab.com/torkel104/libstrangle) provides a solution for Linux. It could be useful to integrate this into GameHub to allow users to specify the rate limiting if necessary.

**Comment by tkashkin** [comment]
I think it's too specific feature to add and I don't think many users need is. 

You can do this with custom script or maybe custom emulator.
