### ISSUE TITLE
Two different games with the same title: King's Quest

### ISSUE THREAD

**Issue by lewellyn** [tkashkin/GameHub#236]
###### Expected behavior

Two entries for King's Quest, as Steam and GOG have listings for the same game as different versions. Perhaps label the GOG version as "King's Quest 1 - Quest for the Crown" so that it's obviously part of the rest of the GOG collection?

* https://www.gog.com/game/kings_quest_1_2_3
* https://store.steampowered.com/app/345390/Kings_Quest/

###### Actual behavior

One entry, with two quite different games.

![image](https://user-images.githubusercontent.com/658826/55850379-1b818700-5b22-11e9-9b09-f2b3ca1eb79a.png)
![image](https://user-images.githubusercontent.com/658826/55850397-25a38580-5b22-11e9-9069-7443e4e70911.png)

###### Steps to reproduce

1. Have the Steam King's Quest (not the King's Quest Collection, which gets its own entry) and the GOG King's Quest in your library.

###### Version and environment

```
Version: 0.13.1--
Branch:  
Commit:   ()
Distro:  openSUSE Tumbleweed
DE:      XFCE
```

Package information: (see #156)
```
Information for package gamehub:
--------------------------------
Repository     : home:lewellyn:gamehub                 
Name           : gamehub                               
Version        : 0.13.173dev+0_642e452-4.1             
Arch           : x86_64                                
Vendor         : obs://build.opensuse.org/home:lewellyn
Installed Size : 1.8 MiB                               
Installed      : Yes                                   
Status         : up-to-date                            
Source package : gamehub-0.13.173dev+0_642e452-4.1.src 
```

**Comment by tkashkin** [comment]
I don't think it's a bug or that something can be done in GameHub.

Both games are named "King's Quest" so they will be merged together if merging is enabled.

**Comment by lewellyn** [comment]
This is unfortunate. I suppose that there aren't likely enough games with the same name but different content across the supported platforms to make it worthwhile to make a merging exception list. A user-generated "don't merge these titles, please" list would probably be hellish to troubleshoot performance issues with, too. I could see a situation where someone has different DLC for the same game across the services.

**Comment by tkashkin** [comment]
I don't think that's a common issue and the only idea I have is to add a "don't merge this game" flag. It's possible, but IMO it will add even more unnecessary clutter to UI and it may also affect performance.

Wontfix for now.
