### ISSUE TITLE
Snap package of gamehub

### ISSUE THREAD

**Issue by thefenriswolf** [tkashkin/GameHub#24]
I've packaged gamehub as a snap, the snapcraft.yaml is available at: https://github.com/thefenriswolf/snaps/blob/master/gamehub/snapcraft.yaml

A test version of the snap is available in the edge channel 

`sudo snap install gamehub-fenriswolf --edge`

**Comment by tkashkin** [comment]
@thefenriswolf Thanks, I wanted to do this myself initially, I've tried with flatpak with some success.

The main issues with flatpak are:
* Games must be in sandbox, some sort of runtime must be bundled (maybe Steam Runtime, but I'm not sure it helps)
* Ideally there should be basic integration with Steam client: app should be able to read Steam configs, library folders and interact with client through `steam://` uri scheme

Are snaps as strictly sandboxed as flatpaks? How well can it be integrated with the system?

**Comment by thefenriswolf** [comment]
Snap sandboxing is done via apparmor confinement, more info [here](https://docs.snapcraft.io/reference/confinement).
I've put gamehub in strict confinement and gave it explicit access to the users home folder so it can see files in /home/$user/.steam

**Comment by tkashkin** [comment]
@thefenriswolf Your snap contains nothing but snap metadata (it's the case at least for `sudo snap install gamehub-fenriswolf --edge`).

I've tried to do snap package and got it to launch at least. It's still broken as hell and I'm not sure if it makes any sense to try to improve it.

https://github.com/tkashkin/GameHub/blob/master/snap/snapcraft.yaml

It builds on Ubuntu 16.04 VM, but needs newer `valac` and some updated libs.
