### ISSUE TITLE
Suggestion: apply to an Epic MegaGrant to improve the integration of Epic Store

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#240]
Recently Tim Sweeney (from Epic) suggested that Lutris should [apply for an Epic MegaGrant](https://twitter.com/TimSweeneyEpic/status/1118757975529803778) since they keep the Epic Store running in Linux using a custom version of Wine (which is not required anymore, btw). I was wonder if @tkashkin is interested in applying for a grant to improve the integration with the Epic Launcher in Linux using GameHub.

**Comment by tkashkin** [comment]
I don't like what Epic is currently doing, don't support it, don't (and won't) use EGS myself and I don't want to implement anything directly EGS-related in GameHub.
