### ISSUE TITLE
Trouble when try to connect to humble with google account

### ISSUE THREAD

**Issue by dracomen** [tkashkin/GameHub#243]
I download gamehud 09/05/2019. Today I try to connect with my humble account (with google), but when I try they told me :
"PLEASE REFRESH AND RETRY. CONTACT SUPPORT IF PROBLEM PERSISTS."

If someone already got this problem please help me to found way out.

thanks.

**Comment by tkashkin** [comment]
It should work if you can sign into Humble account in browser and access library. If you can sign in in browser but can't in GameHub, try solutions from #9.
