### ISSUE TITLE
Folder compatibility with hb-downloader for downloaded installers

### ISSUE THREAD

**Issue by qlonik** [tkashkin/GameHub#244]
Thank you for awesome game manager! :smile: 

I was wondering if it is possible to add compatibility in folders for downloaded installers between this Application and [hb-downloader](https://github.com/talonius/hb-downloader) script? It seems that GameHub stores installers for different platforms in the same folder. For example for game A, installers for windows and linux will all be in `gameA/` folder. However hb-downloader will store those in `gameA/linux` and `gameA/windows`. Can GameHub store those installers by platform?

Additionally, hb-downloader seems to lower case all of the game names. Maybe we can ask them to keep original capitalization, to make it also compatible with GameHub?

**Comment by tkashkin** [comment]
You can use new variables in Collection settings:

| Variable | Expands to |  |  |
| --- | --- | --- | --- |
| `$platform` | linux | windows | mac |
| `$platform_name` | Linux | Windows | macOS |

Platform will be expanded when possible.

**Comment by qlonik** [comment]
Awesome thank you!

Is there a list of all such variables? Is there one which says which HumbleBundle each particular game comes from?

**Comment by tkashkin** [comment]
Variables are listed in Collection settings:

![image](https://user-images.githubusercontent.com/2003017/58362044-b1d3f700-7e9b-11e9-8c6c-6ff52821b626.png)

You can check tooltip for entry to see how it expands.

You can also see how they expand in code for [GOG](https://github.com/tkashkin/GameHub/blob/dev/src/utils/FSUtils.vala#L132-L185) and [Humble](https://github.com/tkashkin/GameHub/blob/dev/src/utils/FSUtils.vala#L132-L185).

**Comment by qlonik** [comment]
I've compiled from dev and tried this patch. It seems that the platform works well. 

However, for some games, the name of the game that is used is not correct. I found that for few games, the `$game` variable expands to "Download", and I end up having paths like `<root>/Humble Bundle/Download/linux/game.tar.gz` and when I download windows version, it ends up being downloaded into `<root>/Humble Bundle/Download/windows/game.exe`.

Is it related to the change from this commit?

**Comment by tkashkin** [comment]
Fixed.

> Is it related to the change from this commit?

Yes, it was a copy-paste error. It was using installer name instead of game name.

**Comment by qlonik** [comment]
Hello, sorry I took long time to reply.

This change worked for me pretty well. I've adjusted hb-downloader script to use `human_name` field of the game, to match that of GameHub.

Last thing that I wanted to figure out: for some games the saved file is the same between hb-downloader and GameHub, but for some it is mismatching. I was wondering which field does GameHub uses for the filename of downloaded file? It seems that hb-downloader is using `current_download.download_structs[i].filename`. Is it the same for GameHub?

**Comment by tkashkin** [comment]
There is no `filename` property in download struct. hb-downloader [extracts](https://github.com/talonius/hb-downloader/blob/72573b00ed1d20caae1b9c131dd3c2bc9f71e4e6/hb_downloader/humble_api/model/download_struct.py#L49-L72) filename from download URL and replaces `/` with `_` because filenames can have subdirectories.

GameHub tries to detect filename in this order:
* Basename of URL (last path part)
* If filename is specified in `Content-Disposition` header, it will be used instead
* Else it will fallback to generic name (`"humble_" + game.id + "_" + installer.id` for Humble games)

https://github.com/tkashkin/GameHub/blob/aa0c1c4ff51676e348a5b273df3b1b9de9c03ca9/src/utils/downloader/SoupDownloader.vala#L180-L242
