### ISSUE TITLE
Only shows the game platform from one store when a game from two sources are added

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#247]
###### Expected behavior
In case of having the same game from more than one store, for example: Humble Bundle and Steam, it should show the platform available from all stores.

###### Actual behavior
The game **Machinarium** is available on steam for the Windows and Mac platforms, but on Humble Bundle its also have the Linux version, the GameHub shows Windows and Mac only on the platform grid:

![image](https://user-images.githubusercontent.com/11244067/59549656-2f3cd580-8f37-11e9-8d69-d470506426cc.png)

###### Steps to reproduce
Just need to have the same game from the different stores with different platforms available on the stores.

However I tested only with this game, because I don't have other that match the criteria.

###### Version and environment
Version: 0.14.0-164e55c-makepkg
Branch:  makepkg
Commit:  164e55c (164e55c87614657b6a9345b919cefc844a44bf53)
Distro:  NAME=Arch Linux
DE:      GNOME

**Comment by Lucki** [comment]
Can confirm with Greed Corp:
![Bildschirmfoto-20190615143108-383x182](https://user-images.githubusercontent.com/1408843/59551482-51a41280-8f7a-11e9-82b8-32cc8aeb2dc6.png)
![Bildschirmfoto-20190615143132-125x60](https://user-images.githubusercontent.com/1408843/59551480-510b7c00-8f7a-11e9-8271-f9143b4da55c.png)![Bildschirmfoto-20190615143123-248x65](https://user-images.githubusercontent.com/1408843/59551481-51a41280-8f7a-11e9-9437-e0768775941b.png)

**Comment by tkashkin** [comment]
Now game cards and list rows should update when source filter changes.

**Comment by hlechner** [comment]
Is it possible to when using a default view (no source filtered) it shows all platform supported (by all sources)?

I tested the last commit and I see when I click on humble bundle filter I can see the the humble bundle as first source and it displaying the linux as platform:
![image](https://user-images.githubusercontent.com/11244067/59557749-1e807400-8fb8-11e9-9515-b1f22ebe7daa.png)
![image](https://user-images.githubusercontent.com/11244067/59557745-014ba580-8fb8-11e9-86d0-37f183a660fb.png)

If I return to the default filter, it shows only the platforms supported by steam:
![image](https://user-images.githubusercontent.com/11244067/59557757-6c957780-8fb8-11e9-9c00-fdb55152ebd1.png)
![image](https://user-images.githubusercontent.com/11244067/59557762-81720b00-8fb8-11e9-81ae-8cd1793456c0.png)

Thanks

**Comment by tkashkin** [comment]
@hlechner Now it should work like you suggested. I'm not sure if I have games to test that though.

As another small QoL improvement game context menus now show merged games as submenus.

**Comment by hlechner** [comment]
It worked, now it shows on the default filter all the platforms:
![image](https://user-images.githubusercontent.com/11244067/59562506-fa4a8480-9003-11e9-88db-75be7000fb2a.png)

I found out that I have a second game on that situation (not having linux on steam but does have on humble), I recognize it because the order change, if the linux platform is not at the start of the grid (but the last in this case) its because the game itself doesn't have the linux game on the first source. but not a bug to me.

To further test I discover that if I disable the options to not show the non-native games and consider windows game compatible:
![image](https://user-images.githubusercontent.com/11244067/59562629-4ba74380-9005-11e9-9f59-c8fdd4ab627b.png)

The game disappear from the default list but still can be seen on the source filter where it does have the linux client.

Also I found out the spacing on the new submenus does not respect the spacing from checkbox to the text itself:
![image](https://user-images.githubusercontent.com/11244067/59562702-43033d00-9006-11e9-99f7-d0d3c873b6ea.png)

I tested on Yaru-dark and also on Adwaita to make sure its not a GTK3 theme related.

**Comment by tkashkin** [comment]
> To further test I discover that if I disable the options to not show the non-native games and consider windows game compatible:
image
The game disappear from the default list but still can be seen on the source filter where it does have the linux client.

This should be fixed, but I don't have games to test that.

I have removed mentioned settings as part of settings rework and added platform filters instead. It may have broke something, testing is needed.

> Also I found out the spacing on the new submenus does not respect the spacing from checkbox to the text itself

Fixed.

**Comment by hlechner** [comment]
I can confirm that the submenu spacing issue is fixed.

Also I really enjoyed the new platform filter:
![image](https://user-images.githubusercontent.com/11244067/59570283-46c9aa80-906c-11e9-9168-18ea1abc3cd0.png)

But it still not displaying the game Machinarium when I filter by Linux platform, only if I click on Humble Bundle button (which is the store that has the linux support for the game).
![image](https://user-images.githubusercontent.com/11244067/59570331-fc94f900-906c-11e9-91cd-5888f838b3e0.png)
![image](https://user-images.githubusercontent.com/11244067/59570345-1afaf480-906d-11e9-91c3-2776bf3b5d3c.png)

If further tests needed just let me know

**Comment by tkashkin** [comment]
Weird, works fine for me.

![image](https://user-images.githubusercontent.com/2003017/59570516-01c06b00-90a2-11e9-9ca0-258a3ee9f8dd.png)
![image](https://user-images.githubusercontent.com/2003017/59570517-0f75f080-90a2-11e9-892c-4427a300830e.png)
![image](https://user-images.githubusercontent.com/2003017/59570519-1ac91c00-90a2-11e9-97e7-58fc90eed204.png)

**Comment by hlechner** [comment]
The Limbo game has linux support on steam, you can notice that the steam logo is the first on the game: 
![image](https://user-images.githubusercontent.com/11244067/59570557-7aa6cf00-9070-11e9-9328-840d54503a43.png)

it seems to matter, from what I suspect the gamehub just filter the platforms from the first source.

In the case of limbo from your screenshot, it shows linux because linux is supported on steam, if was the opposite case it maybe not be shown.

I have an example here, Outcast (steam) and Outcast: Wistleblower (humble bundle), it does work as espected because it has linux support on steam.

![image](https://user-images.githubusercontent.com/11244067/59570637-b8f0be00-9071-11e9-98fc-3cc74e57eab2.png)
![image](https://user-images.githubusercontent.com/11244067/59570644-cad26100-9071-11e9-9b50-1a87a3c78dca.png)

But the Machinarium is the opposite: it does have on humble but not on steam (steam is always the first source)

**Comment by tkashkin** [comment]
Does it work now?

**Comment by hlechner** [comment]
It does! your last commit solved the issue.

Thanks
