### ISSUE TITLE
Unable to add vulkan (DXVK) (not user friendly)

### ISSUE THREAD

**Issue by jatin-cbs** [tkashkin/GameHub#248]
I tried to install battle net (overwatch) using gamehub, I am unclear on how to add DXVK ? By simply selecting wine version it will just run using wine, how to enable vulkan, do I have to wine tricks and add everything myself ? if thats the case this is not at all user friendly. Please help thanks !

**Comment by jatin-cbs** [comment]
And also there may be other things required using wine tricks for overwatch, a game like overwatch which runs using lutris, Play on linux, crossover.. its strange Gamehub doesnt have a DXVK wrapper for it.

**Comment by Lucki** [comment]
You can install dxvk in the prefix using winetricks. Even easier is the use of proton since dxvk is already built in.

**Comment by tkashkin** [comment]
GameHub does not have install scripts for every game like Lutris has. If you want this, maybe you should use Lutris.

I don't plan to do something similar in GameHub right now.
However it may be possible to implement an integration and use GameHub as a frontend to Lutris.

**Comment by jatin-cbs** [comment]
@Lucki so if i simply select proton instead of wine version would that be enough?

**Comment by jatin-cbs** [comment]
@tkashkin that will also be great if it can be front end for lutris or better to integrate it with yaml scripts that lutris uses.

**Comment by Lucki** [comment]
> so if i simply select proton instead of wine version would that be enough?

Yes

**Comment by jatin-cbs** [comment]
@Lucki why they are aweful tho? We can get soo many wrappers then its a good thing..
