### ISSUE TITLE
Search results for SteamGridDB are missing

### ISSUE THREAD

**Issue by Lucki** [tkashkin/GameHub#249]
###### Expected behavior
Grid images from SteamGridDB are shown as well as JinxSGVI results.

###### Actual behavior
Only JinxSGVI results are shown if there are any.

###### Steps to reproduce
Click in any games settings dialog on the download button next to the image-url entry field.
Let's take a popular one for testing: [Diablo III](https://www.steamgriddb.com/game/35619)
![grafik](https://user-images.githubusercontent.com/1408843/59552072-96cc4280-8f82-11e9-83df-bdd7f0a8d3c2.png)

###### Version and environment

```
Version: 0.14.0-164e55c-makepkg
Branch:  makepkg
Commit:  164e55c (164e55c87614657b6a9345b919cefc844a44bf53)
Distro:  Arch Linux
DE:      GNOME
```

###### Bonus feature request:
Bring back the clickable links to quickly adjust the search or try further if the search result for that service is missing. (steamgriddbs main page, jinxsgvi since it's very picky about the name, and the google search was useful in the past too)

**Comment by tkashkin** [comment]
`GET https://steamgriddb.com/api/v2/search/autocomplete/<anything>`:
```json
{
	"success": false,
	"errors": ["Authentication Required"]
}
```

It seems SteamGridDB suddenly [started to require authentication](https://steamgriddb.com/api/v2). There were nothing about API keys a few days ago when I was implementing this :confused:.

**Comment by tkashkin** [comment]
It should be fixed.

> Bring back the clickable links

Links are readded.

> jinxsgvi since it's very picky about the name

You can change game name in preferences dialog and reopen popup. It should search for images with new name. (SteamGridDB doesn't use name for Steam games and searches by appid)

**Comment by Lucki** [comment]
That's great!
I've noticed the top of the popup gets cut off from the window on small settings pages (usually on games provided by steam):
![grafik](https://user-images.githubusercontent.com/1408843/59557196-31a13d00-8fd4-11e9-97fa-42812855f162.png)

**Comment by tkashkin** [comment]
@Lucki

> popup gets cut off

It should be fixed, let me know if not.

**Comment by Lucki** [comment]
@tkashkin I'm sorry but now it's cut off at the bottom.
![grafik](https://user-images.githubusercontent.com/1408843/59562857-1ebd5580-9032-11e9-8ecf-af7942006a28.png)

**Comment by tkashkin** [comment]
@Lucki now it should be fixed.

**Comment by Lucki** [comment]
It is!
