### ISSUE TITLE
IPv6 DNS error

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#250]
I'm getting lot's of `[GLib-GIO] IPv6 DNS error` failing to resolve domains such as `media.steampowered.com` when I run the latest revision of GameHub in debug mode. I noticed these some time ago (using GOG), but using Steam causes a lot of them. 

(my internet connection does not support ipv6 at all, so maybe this will be difficult to reproduce in other settings)

**Comment by tkashkin** [comment]
That's a GLib debug message and there's no way to hide it.

Does it happen if you completely disable IPv6?

**Comment by neuromancer** [comment]
Same result after [disabling ipv6](https://wiki.archlinux.org/index.php/IPv6#Disable_IPv6). If you are sure GameHub is not opting (or forcing?) ipv6 connections, feel free to close the issue, since it will be most likely, not related.

**Comment by tkashkin** [comment]
2713b16 has additional filtering in log messages handler.
Messages from `GLib` and `GLib-GIO` domains should be hidden by default unless GameHub is launched with `--log-no-filters` option.
