### ISSUE TITLE
Is there anyway to import GOG games not lied to the curent account ?

### ISSUE THREAD

**Issue by awsms** [tkashkin/GameHub#252]
Hi devs, I own plural (4) GOG accounts
I would like to know if I can add several accounts to Gamegub, or if I can directly importy the GOG games I own to the "GOG" section on Gamehub (so I can find the games more easily and grab infos like icons of games).

**Comment by tkashkin** [comment]
GameHub currently does not support multiple accounts per source. Most likely it will not change in future.

You can try to use Logout button in settings, restart GameHub and sign into another account. GameHub should load games from this account.
However some information require additional requests and is fetched when game's details page is opened. You may need to manually open game details to fetch all info.

**Comment by awsms** [comment]
> GameHub currently does not support multiple accounts per source. Most likely it will not change in future.
> 
> You can try to use Logout button in settings, restart GameHub and sign into another account. GameHub should load games from this account.
> However some information require additional requests and is fetched when game's details page is opened. You may need to manually open game details to fetch all info.

Thanks, will give it a try later
