### ISSUE TITLE
Option to disable the overlay

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#254]
I have enabled the overlays feature to test, but without needing it, however I don't see how I can disable it.
![image](https://user-images.githubusercontent.com/11244067/59571170-98783200-9078-11e9-98c1-8fcd7572b615.png)

However since I clicked the overlays on some games now, it does mount 10x when the gamehub starts, but not umount on exit, as a side effect, the gnome-files (a.k.a nautilus) display all mounted places:
![image](https://user-images.githubusercontent.com/11244067/59571191-bfceff00-9078-11e9-98df-662f17666ea2.png)

I would like to have an option to disable it, can be for all games or individually.

**Comment by hlechner** [comment]
@tkashkin I find out that you have mentioned it on the following issue: https://github.com/tkashkin/GameHub/issues/120#issuecomment-471778790

Should I close this one and keep it just there?

**Comment by tkashkin** [comment]
> it does mount 10x when the gamehub starts, but not umount on exit

There are two reasons for this behavior:
* It allows to close GameHub while keeping overlay mounted. This may be useful if you want to run game manually or keep it running while GameHub is closed.
* It may be unnecessarily complicated to track all mounted overlays and umount them on exit.

Overlay removal is also complicated:
* Should it remove files when overlay is removed?
* Should it move files back from `base` overlay when there's no other overlays and `base` is being removed?

> the gnome-files (a.k.a nautilus) display all mounted places

I don't know if it's possible to hide them. But nautilus `3.32.1-stable` on Ubuntu 19.10 doesn't seem to show overlays (in fact it doesn't show any mountpoints in sidebar unless run as `root`; in my case everything is setup in `/etc/fstab`):

| user | root |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/2003017/59572107-82d42e00-90b3-11e9-9d34-ef7b2e95b9e5.png) | ![image](https://user-images.githubusercontent.com/2003017/59572147-cf1f6e00-90b3-11e9-97e7-fb100fd8e06a.png) |

**Comment by hlechner** [comment]
> There are two reasons for this behavior:
> 
> * It allows to close GameHub while keeping overlay mounted. This may be useful if you want to run game manually or keep it running while GameHub is closed.
> * It may be unnecessarily complicated to track all mounted overlays and umount them on exit.

You're right, now I believe GameHub shouldn't umount it.

> 
> Overlay removal is also complicated:
> 
> * Should it remove files when overlay is removed?
> * Should it move files back from `base` overlay when there's no other overlays and `base` is being removed?
> 
I believe the ideal is to move the files back for the origin, if it's not possible, just tell the user.

But I must to explain that maybe I don't fully understand the overlay features in the first place, here what happens:

I was looking all GameHub features to see how it works, so, I clicked on "overlays" on a manually added snes game, it asked to be activated the first time, so I thought "Ok, I will deactivate it after try what is it for", since the directory have other files too (not related to the game) it was not suppose to be moved.

Trying to disable I enabled the overlay in other games as well by accident, because I thought it would asked me to enable for the next game like the first time I activated the overlays. 

Of course, most the problem was about my misunderstanding of the feature itself, but I believe it can be improved so this case can be minimized at least:

- [per game] Ask to enable overlays per game  (avoid to click on overlay accidentally and have the games files moved because the overlays was activated on a different game)
- [one time only] Inform the user that the files will be moved by enabling the overlays and ask if the user wants to proceed

Of course, it's just simple ideas.

> > the gnome-files (a.k.a nautilus) display all mounted places
> 
> I don't know if it's possible to hide them. But nautilus `3.32.1-stable` on Ubuntu 19.10 doesn't seem to show overlays (in fact it doesn't show any mountpoints in sidebar unless run as `root`; in my case everything is setup in `/etc/fstab`):
> 
> user	root
> ![image](https://user-images.githubusercontent.com/2003017/59572107-82d42e00-90b3-11e9-9d34-ef7b2e95b9e5.png)	![image](https://user-images.githubusercontent.com/2003017/59572147-cf1f6e00-90b3-11e9-97e7-fb100fd8e06a.png)

Interesting, because here is the opposite, I can see the mounts on my user, but not running on root, I believe it's not possible to fix on GameHub anyway, in my case maybe it show all mounts except the ones included on /etc/fstab (just a guess)

**Comment by hlechner** [comment]
Just to complement, the examples do not have dlc, just the game as base:
![image](https://user-images.githubusercontent.com/11244067/59653687-7e6a4c80-9169-11e9-9391-221805c82794.png)

**Comment by tkashkin** [comment]
That's how it works:

* Game has `executable` and `install_dir`. `install_dir` is parent of `executable` by default.
In case of overlays it's assumed that there's no non-game-related files in `install_dir`.
I'll call `install_dir` `.` below.
* When overlays are enabled `./_gamehub/overlays/base` is created and everything from `.` is moved to `./_gamehub/overlays/base`.
* Additional overlays are stored in `./_gamehub/overlays/<overlay_id>`.
Overlays can be added by user or created by GameHub for GOG DLCs.
* When overlays are mounted `./_gamehub/_overlay/merged` is created.
It is equivalent to copying everything from `base` overlay and then copying other overlays on top of `base` replacing conflicts.

Simplified example: https://github.com/tkashkin/GameHub/issues/120#issuecomment-463629764

**Comment by hlechner** [comment]
Thanks for the explanation.

My previously ideias were about the erroneous assumptions of how overlay works, since I tested many games with the same base dir, that's why I thought that once I enable overlay on one game all games on gamehub would be affected by this.

I was thinking about it and here my 3 ideas:

1. **Do not allow the overlay to be created if the base dir is on blocked list.**
Imagine the following situation: you do add a game on GameHub installed by distro's packaged manager on `/usr/bin`, I really do believe it will be really problematic if all content of this directory be moved from this base directory by the user's mistake. of course to add a really comprehensive list will not be viable. however I think just 3 paths will be ok: `/usr/bin` and `/bin` which is a common place where the binares were called and also `~/` which I believe is a common place for users to keep general files. However I didn't tested if GameHub does allow that since I didn't want to mess with my files.
2. **Option to remove the additional overlay (all except base)**
Maybe a button on the left side of "Open Directory" button, it just work if the directory itself is empty, otherwise it will not allow the removal.
3. **Delete the Overlay (base)**
To be removed: It must do not contain any additional overlays just the base, it ask if user wants to proceed if it does accept then the content of `./_gamehub/overlays/base/` will be moved to `.`, after that, it should be unmounted (to delete the files) and the directory `./_gamehub` can be deleted.

What do you think? Feel free disagree with any (or all) ideas I had, I'm just trying to help elaborate a way to disable the overlay.

**Comment by tkashkin** [comment]
* Overlays can now be removed. When `base` is removed all files are moved back to the `install_dir`.
* Overlays can not be created if `install_dir` is outside of `/home/`, `/mnt/`, `/media/` and `/run/media/`. Error will be shown in this case.
* Warning will be shown if `install_dir` is outside of GOG and Humble games paths.

**Comment by hlechner** [comment]
From my tests everything seems to work properly, nice idea with the warning outside gog/humble btw.

Thanks, I'm closing the issue since to me it's fixed.
