### ISSUE TITLE
Not able to open gamehub (Pop OS)

### ISSUE THREAD

**Issue by jatin-cbs** [tkashkin/GameHub#257]
I recently installed gamehub using pop shop on Pop OS, I want to skip this screen so i can go to gamehub its not letting me click on skip. Why is it mandatory to sign up using GOG steam or HB ? 
![Screenshot from 2019-06-21 03-57-48](https://user-images.githubusercontent.com/40650341/59885486-0c983a00-93d9-11e9-8daa-983a9cb9073a.png)
I cant click on skip button ? why ?

**Comment by tkashkin** [comment]
Initially there was no support for custom games so it made sense to require at least one enabled and authenticated source.

Now, since it's possible to add custom games, this restriction is removed.
