### ISSUE TITLE
Custom Emulator: game file patterns also match directories as executable

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#258]
###### Expected behavior
When a pattern is defined on the following textbox:
![image](https://user-images.githubusercontent.com/11244067/59925479-957d9880-940e-11e9-9f06-e2fdf897f4bc.png)
The expected behavior is that only **files** will match this pattern

###### Actual behavior
It's actually matching the folders as well.

###### Steps to reproduce
I'm using Higan (emulator), and this emulator copy the roms on that directory structure:
`<name of the console>/<name of the rom>/program.rom`

In this example:
`Super Famicom/Aladdin (USA).sfc/program.rom`

`Aladdin (USA).sfc` is a folder but recognized as executable:
![image](https://user-images.githubusercontent.com/11244067/59926184-286b0280-9410-11e9-9a87-e068d430682c.png)

###### Version and environment

```
Version: 0.14.0-1543581-makepkg
Branch:  makepkg
Commit:  1543581 (154358158a1e1200a69ed3b35fbf338f68f29d13)
Distro:  NAME=Arch Linux
DE:      Yaru:ubuntu:GNOME
```

**Comment by tkashkin** [comment]
It should be fixed.

**Comment by hlechner** [comment]
It's fixed.
