### ISSUE TITLE
Filter by source shows games from different sources when merge games is disabled

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#259]
###### Expected behavior
Filter by source (steam, gog, humble, local) should only display the games from that source selected.

###### Actual behavior
By disabling the `Merge games from different sources` option, seems that it still shows same games as merged, so, it shows as duplicated:
![image](https://user-images.githubusercontent.com/11244067/59932806-65d68c80-941e-11e9-87c5-cdbdc4de4dc1.png)
![image](https://user-images.githubusercontent.com/11244067/59932759-463f6400-941e-11e9-84d5-5290b3c522d2.png)

The reason for that, seems to be related to the fact that the steam games do not lose the merged icons:
![image](https://user-images.githubusercontent.com/11244067/59932944-bf3ebb80-941e-11e9-9aaf-b19dd7ab9efc.png)
![image](https://user-images.githubusercontent.com/11244067/59932913-ac2beb80-941e-11e9-9567-1889de7e4cd4.png)

###### Steps to reproduce
With the GameHub with merged games on it, go to: Settings > Behavior

- Disable the `Merge games from different sources`
- Restart the GameHub to the changes take effect
- Filter the source (GOG or Humble)

And will see that the previously merged game from steam is there too

###### Version and environment

```
Version: 0.14.0-4f32825-makepkg
Branch:  makepkg
Commit:  4f32825 (4f3282591552a3930c8c696b5c4f46b3135e771e)
Distro:  NAME=Arch Linux
DE:      Yaru:ubuntu:GNOME
```

**Comment by tkashkin** [comment]
It should be fixed.

**Comment by hlechner** [comment]
Also fixed.
