### ISSUE TITLE
Game DLC not properly filtered

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#260]
###### Expected behavior
- The DLC should display the correct platforms available for it.
- DLC should not count as additional game on the bar `Humble Bundle: X games` (maybe: except if it will be displayed as a different game on list)

###### Actual behavior
- Humble Bundle game [outlast](https://www.humblebundle.com/store/outlast) is displaying the correct platforms for the game (Lin/Win/Mac) but the game DLC: [outlast: whistleblower](https://www.humblebundle.com/store/outlast-whistleblower) doesn't, it does have the same platforms but only shows Windows as platform:
![image](https://user-images.githubusercontent.com/11244067/59937383-b226ca00-9428-11e9-8b7e-bfb6c24c8380.png)
- On the window bar it shows 15 games on Humble Bundle, If the `Merge games` is disabled, it's ok, since it display game and DLC as separated games on the list (totalizing 15), but when the `Merge games` is enabled, the DLC and the game itself are merged and only 14 games are displayed but still showing 15 on the window bar:
![image](https://user-images.githubusercontent.com/11244067/59937502-f7e39280-9428-11e9-86f4-634481074e0e.png)

###### Steps to reproduce
- Make sure the option `Merge games from different sources` is disabled on Settings > Behavior.
- With a game [outlast](https://www.humblebundle.com/store/outlast) and it's DLC [outlast: whistleblower](https://www.humblebundle.com/store/outlast-whistleblower), it's possible to see the DLC only display windows as platform instead of Lin/Win/Mac
- The number of the games on the window bar will contain the DLC even if the Merge games option is enabled.

###### Version and environment

```
Version: 0.14.0-4f32825-makepkg
Branch:  makepkg
Commit:  4f32825 (4f3282591552a3930c8c696b5c4f46b3135e771e)
Distro:  NAME=Arch Linux
DE:      Yaru:ubuntu:GNOME
```

**Comment by tkashkin** [comment]
Humble doesn't have a DLC concept and doesn't provide any info except game's name, icon and downloads.

**Comment by hlechner** [comment]
Probably not easy to implement: but since there is no info about DLC from humble bundle, is it possible to not merge games from the same source?

Both from Humble Bundle:
![image](https://user-images.githubusercontent.com/11244067/59953517-da2d2200-9456-11e9-885d-51bea58e532b.png)

For some reason it shows the second one as windows-only and uses it when both are merged, so it tries to install through proton.

The problem in the other hand will be how to know which game from these two will be merged from the same game from other source:
![image](https://user-images.githubusercontent.com/11244067/59954578-c3d59500-945b-11e9-8df1-5ee17b6237b8.png)

**Comment by hlechner** [comment]
Additional information:
The windows-only seems to be a humble bundle fault.

The store page show as Lin/Win/Mac but If I go to their webpage library to download:
![image](https://user-images.githubusercontent.com/11244067/59958599-ad413500-947f-11e9-9157-8fffe0e2426c.png)
![image](https://user-images.githubusercontent.com/11244067/59958613-deba0080-947f-11e9-82d0-d2a1e263019f.png)

But since the windows-only is the selected to show on the merged, it asks to install through proton :
![image](https://user-images.githubusercontent.com/11244067/59958711-170e0e80-9481-11e9-83f1-3788715ca7d6.png)
