### ISSUE TITLE
Download all installers?

### ISSUE THREAD

**Issue by Ezwen** [tkashkin/GameHub#262]
For people who want to download their complete GOG and/or Humble game collection for later use, it would be nice to have the possibility to trigger the "Download Only" action on a selection of games, possibly all of them.

thanks for GameHub, great work!

**Comment by tkashkin** [comment]
Now you can switch to list view and select multiple games by pressing `Ctrl` and clicking (`Ctrl + A` works too).

It will show available actions for selected games.

And it also allows to edit tags for all selected games at once.

**Comment by Ezwen** [comment]
Indeed! thanks for the tip and apologies for the unnecessary feature request!

**Comment by tkashkin** [comment]
But it's not unnecessary, it was just implemented.
