### ISSUE TITLE
"Run" only opens steam, it does not launch the game

### ISSUE THREAD

**Issue by Hunanbean** [tkashkin/GameHub#263]
###### Expected behavior
When I press run, or any other option to lauch an installed steam game from within the gamehub gui i expect it to open steam and launch the game. i can launch the game directly through steam with no issues

###### Actual behavior

When i press run, or any other option to launch an installed steam game from within the gamehub gui it launches steam to the last page/location i was at in steam, but never launches any game. i can launch the game directly through steam with no issues

###### Steps to reproduce
Open gamehub, try to launch steam game

###### Version and environment
Linux Mint 19.1

```
Version: 0.14.0-371a9c9-dev
Branch:  dev
Commit:  371a9c9 (371a9c9ed92a898f4e3ef0b8b2958f509fb0a01d)
Distro:  Linux Mint 19.1 Tessa
DE:      X-Cinnamon
```

**Comment by tkashkin** [comment]
Problem is probably in Steam's `.desktop` files. See #227 and #117.

**Comment by Hunanbean** [comment]
Thanks for the input. I followed the instructions in posts, [#226](https://github.com/tkashkin/GameHub/issues/226) and [#117](https://github.com/tkashkin/GameHub/issues/117), to no avail. I can say however that even when i try `steam steam://install/<appid>` directly, it too only opens steam and does not launch the game referenced by appid. For example, 237850 for Dreamfall Chapters. It does report,

"Running Steam on linuxmint 19.1 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!" as a response in terminal

I have previously resolved the missing theme Gtk errors.
Again, I have followed the troubleshooting instructions on the previous posts and the settings are as they should be, based on that information.
If there is any other information i could offer, please let me know. Thanks again.

**Comment by tkashkin** [comment]
* Run `steam -dev` in terminal.
* Open console tab in Steam client.
* Try to run `steam steam://install/<appid>` and `steam steam://rungameid/<appid>` in other terminal.

Does it show following messages in console?
```
ExecCommandLine: "'<path to steam binaries>/steam' 'steam://install/<appid>'"
ExecuteSteamURL: "steam://install/<appid>"
ExecCommandLine: "'<path to steam binaries>/steam' 'steam://rungameid/<appid>'"
ExecuteSteamURL: "steam://rungameid/<appid>"
```

**Comment by Hunanbean** [comment]
When I type `steam steam://install/35700` in xterminal, the steam terminal reports 
`ExecCommandLine: "'<path to steam binaries>/steam' 'steam://install/35700'"
ExecuteSteamURL: "steam://install/35700"` and does not execute the game

When I type `steam steam://rungameid/35700` in xterminal, the steam terminal reports
```
ExecCommandLine: "'<path to steam binaries>/steam' 'steam://rungameid/35700'"
ExecuteSteamURL: "steam://rungameid/35700"
```
and properly executes the game. in this case Trine

**Comment by tkashkin** [comment]
@Hunanbean it seems to work correctly. I guess Steam doesn't do anything if you are trying to install already installed game. Try it with some uninstalled game.

Does GameHub detect installed games as installed?

**Comment by tkashkin** [comment]
Closing since it doesn't seem to be a GameHub issue.
