### ISSUE TITLE
Unchecking "Merge games from different sources" has no effect with the Appimage

### ISSUE THREAD

**Issue by Kabouik** [tkashkin/GameHub#264]
Pretty much what the title says. I have restarted Gamehub, but the list still merges all sources together in a single alphabetically sorted list. I tried only the AppImage, but this may have nothing to do with it.

###### Expected behavior
Sources should be separated.

###### Actual behavior
Sources are not separated.

###### Steps to reproduce
- Uncheck "Merge game from different sources" in Settings/Behavior.
- Restart Gamehub.
- Profit.

###### Version and environment
```
Version: 0.14.0-371a9c9-dev
Branch:  dev
Commit:  371a9c9 (371a9c9ed92a898f4e3ef0b8b2958f509fb0a01d)
Distro:  [AppImage] Solus
DE:      Budgie:GNOME
```

**Comment by tkashkin** [comment]
I think you have misunderstood this option. When it's enabled, GameHub will merge games with same name from different sources. For example, if you have some game on Steam and GOG, it will merge them together.

You can filter by source using buttons in headerbar: 
![image](https://user-images.githubusercontent.com/2003017/60304998-cea09600-9943-11e9-8f33-98e454dd7c1a.png)

**Comment by Kabouik** [comment]
Oh, then I surely did misunderstand, thank you for clarifying. Merging duplicates occurring in several sources is a great feature! Could this option be disambiguated with a rewording like: "Merge games occurring in several sources", or "Avoid duplicate games occurring in several sources"?

I misunderstood that the option was meant to distinguish source subcategories in the list when set to show all sources (leftmost icon). I know about the filters, but filtering is a bit different than sorting within the full list. I guess what I was looking for was more of a sorting option (nesting `Game title` into `Source` in ascending order) for the "All sources" filter, with headers showing source subcategories to help readability when scrolling.

I know source subcategories kind of go against the whole "unification" idea but some people want to have all their games in the same place while keeping track of what's what. And while filtering is great, being able to distinguish games in the full list can be nice too.
