### ISSUE TITLE
Suggestions to improve readability of the full game list

### ISSUE THREAD

**Issue by Kabouik** [tkashkin/GameHub#265]
The full game list (leftmost filter icon) can be hard to read through, even without compact mode, because there is no obvious visual assistance to distinguish sources in the blink of an eye, and uninstalled games can clutter the view. It is true that there are source filters and a `Not installed` tag to hide them, but some may like to use the exhaustive list of their games with some visual cues to ease readability, even show all uninstalled games to occasionally reinstall stuff they would forget if not displayed.

Steam actually does a pretty good job at it with some minimalism:

![Screenshot from 2019-06-27 23:47:08](https://user-images.githubusercontent.com/7107523/60306214-add64180-993f-11e9-8c0d-665f9767d8a7.png)

There are simple changes that could help in Gamehub:

**1. Add a `Source` toggle to sorting options that could be combined with the existing sorting options.** Toggling it on would show source subcategory names alphabetically sorted, and result in something like:
```
GOG # Different font
Game 1
Game 2
Game n
      # Some tiny space here
STEAM
Game 1
Game 2
Game 3
...
```

**2. In the tag/sorting pop-up, add a "Show as header" checkbox to each tag.** Though it might cause issues on how to sort games when multiple tag headers are shown in the list, or would display some tags multiple times when games are not sorted accordingly. Not sure how to make this work. 

**3. Allow collapsing/expanding all headers that explicitly appear in the list** (_i.e._, source subcategory names, `Installing`/`Installed`/`Not Installed`/`Favorites` tags). This would be a useful yet simple improvement to declutter the list without completely hiding tags (and possibly forgetting about them).

**4. Grey out games that are currently not installed.** At the moment they take up just as much space as installed games, and are shown with the same font color, bold title, and background:

![Screenshot from 2019-06-27 23:41:56](https://user-images.githubusercontent.com/7107523/60302832-2be11b00-9935-11e9-87dd-fda576b75680.png)

This makes it hard to distinguish them from others when scrolling long lists. Many users won't want to show those games anyway, but again others prefer exhaustive lists that are easy to read (like the Steam screenshot above). Having uninstalled games showing up in grey (which would work both in light and dark mode by the way) would perhaps even allow removing the "Installed" or "Not installed" text below game names.

**5. Add a "minimalist" option on top of the compact mode to hide icons and remove the bold font.**

Of course not all suggestions may be deemed relevant or useful, but I hope some will!

**Comment by tkashkin** [comment]
I have added more options for list style.
It's now possible to set icon/status visibility and title font separately for installed and not installed games.

List headers now should adapt to different GTK themes better and be more visible.

Groups in list are not changed yet and I'm not sure I want to change it now since it will require significant rewrite.

**Comment by Kabouik** [comment]
Wow, it is great to such fast development. Thanks a lot, I'll try all this as soon as possible!

**Comment by tkashkin** [comment]
@Kabouik now it's possible to:
* disable grouping completely
* group by source
* group by status (previous behavior)

Favorite games will be sorted on top anyway and will have separate groups if grouped by source.

**Comment by Kabouik** [comment]
Excellent, thanks. 

Do you think it could be further improved by allowing combining both source grouping and status grouping? 

"Do not group" should be exclusive and toggle off other groups whenever selected. However, "Source" and "Status" could be more permissive: first toggle on "Source" and then "Status" to group according to both parameters, or on "Status" then "Source" to invert the hierarchy. 

Do you think this would work? I'm not sure how straightforward it would be for a user who doesn't know about the feature, without visual hints of the hierarchy, but maybe looking at the list being updated would be self-explanatory enough?

**Comment by Kabouik** [comment]
By the way, regarding the previous commit, I noticed that the line height is decreased when hiding the status of the game, which is really great. I can't be smaller because otherwise the icons would be tiny. But how about decreasing it a little more when icons are disabled?

![](https://0x0.st/z_Bw.png)

There is a lot of room between list items. It's not a bad thing per se, but the scroll bar could be more compact when no icons are shown, and readability would still be good.

**Comment by tkashkin** [comment]
> What do you think about further improving it by allowing combining both source grouping and status grouping?

I think it will be unnecessarily complicated to implement and to use.

**Comment by Kabouik** [comment]
Understood. Thanks for the other commit on padding!
