### ISSUE TITLE
Custom tag deletion

### ISSUE THREAD

**Issue by Kabouik** [tkashkin/GameHub#266]
Custom tags can't seem to be deleted yet. I now regret having created this `test` tag. :>

![Screenshot from 2019-06-28 01:37:37](https://user-images.githubusercontent.com/7107523/60307540-5c30b580-9945-11e9-9dcc-793c483c103e.png)

**Comment by tkashkin** [comment]
Now tags can be removed via a context menu.

**Comment by Kabouik** [comment]
Great, thanks.
