### ISSUE TITLE
Option to install games by command instead of needing an executable

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#269]
One of my favorite features of GameHub is a great way to catalog my games, because it does allow me to even catalog not installed non-store games, that's amazing.

![image](https://user-images.githubusercontent.com/11244067/60400782-1cd5b500-9b4f-11e9-81be-d12d99009bdb.png)

There is an improvement that could be awesome to have on GameHub: possibility to install games by a command instead needing to have an executable/script.

For example: Let's say that I want to add the game OpenTTD, there will be no game installer to select since I want to install it through distro's package manager (pacman, apt-get, etc).

The command of the example above would be:
`gnome-terminal -e "sudo pacman -S openttd openttd-opensfx openttd-opengfx"`

Just by add the ability of install game by command will be very handy to not need to create shell scripts for every game on that situation. I'm just not sure how GameHub would transition from `not installed` to `installed`, maybe it need's to ask the executable after the install?

The basic idea can be even improved:
- Have a checkbox to "run on terminal", so no need to call `gnome-terminal -e` on every command.
- Have an option to add a script (similar to custom script on compatibility layer), it would allow to add complex procedures but still without need to manually create shell script files.

**Comment by tkashkin** [comment]
I think proper way is to install games outside of GameHub and then add executables.

You can even input executable name and it will be expanded if there is an executable with this name somewhere in `$PATH`.

**Comment by Lucki** [comment]
This could probably be implemented through [packagekit](https://www.freedesktop.org/software/PackageKit/pk-faq.html#session-methods) but I'm not sure if it's the purpose of this app to install system software and if it makes sense to implement a [sinking ship](https://blogs.gnome.org/hughsie/2019/02/14/packagekit-is-dead-long-live-well-something-else/).
