### ISSUE TITLE
The images with white border

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#27]
<div align=center>

![captura de tela de 2018-07-22 19-37-51](https://user-images.githubusercontent.com/26097419/43050895-c7ea128c-8de6-11e8-9939-1f170e04f487.png)
![captura de tela de 2018-07-22 19-38-46](https://user-images.githubusercontent.com/26097419/43050936-4cd1a870-8de7-11e8-9265-7ae022f6da38.png)
![captura de tela de 2018-07-22 19-38-46](https://user-images.githubusercontent.com/26097419/43050987-349078e4-8de8-11e8-9e3d-1eb4d825af61.png)
</div>

**Comment by tkashkin** [comment]
@LeandroStanger, thanks, it should be fixed for the next release.

| elementary | Adwaita |
| :---: | :---: |
| ![elementary](https://user-images.githubusercontent.com/2003017/43063929-1c19d7fa-8e66-11e8-9637-453045069bb1.png) | ![adwaita](https://user-images.githubusercontent.com/2003017/43063935-213838f8-8e66-11e8-93d4-ca3169bad8be.png) |
| Numix | Materia |
| ![numix](https://user-images.githubusercontent.com/2003017/43064139-c2c27c6a-8e66-11e8-8a9a-024bf9193355.png) | ![materia](https://user-images.githubusercontent.com/2003017/43064148-cb49d3ec-8e66-11e8-98e6-d83de008252c.png) |
