### ISSUE TITLE
Build Issue probably because of Vala. 

### ISSUE THREAD

**Issue by Ergo0** [tkashkin/GameHub#271]
I'm having some issues building the gamehub package from source. 
latest versions of the dependencies are currently installed. 
This occurs with the latest release from master with the latest release from vala. 

build log here : 
http://dpaste.com/35XM647

**Comment by tkashkin** [comment]
9d0ff03 should probably fix it. Vala 0.45.1 added this error.

**Comment by Ergo0** [comment]
I take it this fix is only available in the master tree of the git repo.
this isn't pushed too the latest release yet am i right?

**Comment by tkashkin** [comment]
It is available in [dev](https://github.com/tkashkin/GameHub/tree/dev) branch.
