### ISSUE TITLE
Humble login screen blank

### ISSUE THREAD

**Issue by Teal1500** [tkashkin/GameHub#272]
###### Expected behavior
Getting an email and password box when clicking the humble login option

###### Actual behavior
Getting a top bar with humble logo and a blank page

###### Steps to reproduce
Click the humble login button on the app starting screen

###### Version and environment

```
Version: 0.14.1-984f26f-master
Branch:  master
Commit:  984f26f (984f26fee5f9d9f43b648e587337e1c05cc3a4f0)
Distro:  Manjaro Linux
DE:      GNOME
```

**Comment by tkashkin** [comment]
They have changed login page layout a bit and it broke because GameHub injects CSS to hide everything except login form itself.
