### ISSUE TITLE
Adding DOS games to run in DOSBox using only executable files

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#273]
After reviewing the [DOSBox documentation in the wiki](https://github.com/tkashkin/GameHub/wiki/DOSBox-support), I think GameHub could automatically create a minimalist .conf file to run with DOSBox when you select a MSDOS EXE, BAT or COM file when adding a game. Btw, you can know if the binary is for DOS or Windows, using `file`:

```
$ file jill1.exe 
jill1.exe: MS-DOS executable, MZ for MS-DOS
$ file MDK3DFX.EXE 
MDK3DFX.EXE: PE32 executable (GUI) Intel 80386, for MS Windows
```

**Comment by tkashkin** [comment]
@neuromancer, @hlechner

Now DOSBox can also be used if executable is a DOS executable.

If there is no configs GameHub will run `dosbox -c 'mount c .' -c 'c:' -c '<file>'`.

**Comment by neuromancer** [comment]
It works!. A few things to improve:

* After the game ended, it could be useful to close dosbox. Useing `-c exit` should do the trick.
* The "disable fullscreen" checkbox have no effect (since dosbox will not enable fullscreen by default).

**Comment by tkashkin** [comment]
> After the game ended, it could be useful to close dosbox

`-exit` option is already used.

**Comment by neuromancer** [comment]
I believe the `-exit` switch only works if you specify a single executable to run in dosbox, without using `-c`

**Comment by hlechner** [comment]
From my tests, it's not working if I use a `.bat`.

The game binary itself is `PT.EXE` but to runs the audio on it I must execute the file `PIZZA.BAT` instead.

If I choose the `PIZZA.BAT` it do not allow me to select DOSBox as compatibility layer.

I tried to choose first an EXE to shows a DOSBox on compatibility layer and then switch to BAT but it just fallback to custom script.

```
$ file PIZZA.BAT 
PIZZA.BAT: DOS batch file, ASCII text, with CRLF line terminators
```

**Comment by neuromancer** [comment]
I think it should be [extended](https://github.com/tkashkin/GameHub/commit/e4b9623e5352b2f22f949702b233fd6707c783b9#diff-d2530196fcc51349f6364f7871bcc37dR89) to work with BAT and COM files.

**Comment by tkashkin** [comment]
Now it should work for any file if `file` output contains `DOS`.

**Comment by hlechner** [comment]
Worked here!

**Comment by hlechner** [comment]
Just to add about the `exit`: It just work if you choose an executable, if you choose a `.BAT` instead it will go back to DOSBox console.

I believe the reason is the same as I faced by configuring the `dosbox.conf` for the first time:
If you just do that:
```
PIZZA.BAT
EXIT
```
The `PIZZA.BAT` probably will be executed on a different process then the EXIT do not take effect.

However if I change to:
```
CALL PIZZA.BAT
EXIT
```

it does work.

**Comment by hlechner** [comment]
I think i found the solution:
- add `call` before the filename
- change `-c exit` to `-exit`

Before:
`/usr/bin/dosbox -c "mount c ." -c "c:" -c \PIZZA.BAT -c exit -conf /usr/share/com.github.tkashkin.gamehub/compat/dosbox/windowed.conf`

After:
`/usr/bin/dosbox -c "mount c ." -c "c:" -c call \PIZZA.BAT -exit -conf /usr/share/com.github.tkashkin.gamehub/compat/dosbox/windowed.conf`

at least it worked for me, I tested with `BAT` and `EXE` files.

**Comment by hlechner** [comment]
`src/data/compat/DOSBox.vala`:
``` vala
				cmd += "-c";
				cmd += "call";
				cmd += runnable.executable.get_path().replace(runnable.install_dir.get_path(), "").replace("/", "");
				cmd += "-exit";
```
In this case, the backslash before the name causes the command to fail, so I edited the `replace` to remove the backslash, of course it's a stupid workaround but it's just to show a working scenario.

**Comment by neuromancer** [comment]
Maybe `call` should be used only if it is a BAT file?

**Comment by tkashkin** [comment]
Does it work better in c6bb7a8?

Other improvements in this commit:
* Now GameHub passes game's arguments to game. Example:
```
dosbox -c 'mount c .' -c 'c:' -c 'call \GAME.EXE <game.arguments>' -c 'exit' [-conf '<conf>'...]
```
* Now GameHub reads all additional configs from data directories and shows them as checkboxes. See [windowed.conf](https://github.com/tkashkin/GameHub/blob/c6bb7a85da856331381086bf0841886228ca534e/data/share/compat/dosbox/windowed.conf) as example.
You can place your configs in
  * `/usr/share/com.github.tkashkin.gamehub/compat/dosbox/`
  * `~/.local/share/com.github.tkashkin.gamehub/compat/dosbox/`
  * `<Any of $XDG_DATA_DIRS>/com.github.tkashkin.gamehub/compat/dosbox/`

**Comment by neuromancer** [comment]
c6bb7a8 is somehow triggering a call to wine (I can see the wine update window the first time). Is that expected?

**Comment by tkashkin** [comment]
@neuromancer no, it shouldn't happen. Does game have DOSBox selected as compat tool and is there anything unexpected in log?

**Comment by hlechner** [comment]
https://github.com/tkashkin/GameHub/commit/c6bb7a85da856331381086bf0841886228ca534e It's working here

**Comment by hlechner** [comment]
I can't add any game with a `.EXE`, `.BAT`, `.COM` files, it does not show any error and also no message on debug as well.

If the game is already added I can change the executable, but I can't add a new game with those file types.


Files tested:
```
$ file TWINSEN.EXE 
TWINSEN.EXE: PE32 executable (GUI) Intel 80386, for MS Windows
$ file DOS4GW.EXE 
DOS4GW.EXE: MS-DOS executable, LE for MS-DOS, DOS4GW DOS extender (embedded)
$ file PIZZA.BAT 
PIZZA.BAT: DOS batch file, ASCII text, with CRLF line terminators
$ file MUSIC.COM 
MUSIC.COM: DOS executable (COM)
$ file CounterStrikeSource.exe 
CounterStrikeSource.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```

None of those files worked.

**Comment by tkashkin** [comment]
@hlechner weird, I can't reproduce it. Try to restart GameHub. Try to change filters or find game in search.

**Comment by hlechner** [comment]
Oh Gosh, how stupid I'm... I thought it wasn't selected any platform filter but in reality it was selected `Linux`.

If other file-types are added it receives `Linux` as platform but if those files are added as executable it receives `Windows` platform, which Is expected I think.

Sorry about that.
