### ISSUE TITLE
IGDB information not updated when you change the name of a game

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#274]
In the latest `dev` revision of GameHub, manually changing the name of the game won't update the IGDB information (not even after re-start). You are forced to remove the game and re-add it with the corrected name. 

To reproduce:
1. Manually add one game, with some name.
2. Check the fetched IGDB information.
3. Rename the game.
4. Re-check the IGDB information. It is not updated.

**Comment by tkashkin** [comment]
IGDB cache should be cleared when game is renamed.

**Comment by neuromancer** [comment]
Fixed!
