### ISSUE TITLE
DOSBox re-open when "exit" is executed on DOSBox window

### ISSUE THREAD

**Issue by hlechner** [tkashkin/GameHub#275]
###### Expected behavior
With a DOSBox game without exit on `.conf` file is executed: when the game is finished it will go back to a DOS terminal, when you type: `exit`, the DOSBox should be closed. 

###### Actual behavior
The moment you type: `exit`, the DOSBox closes, but GameHub re-open it.

The only way to actually closes it is by clicking on the close button of window border.

From debug messages it just repeat the `[DEBUG]  [Utils.run] {'/usr/bin/dosbox'...` as the first time it executed it.

###### Steps to reproduce
- Add a DOSBox game on GameHub (without `.conf` file or with a `.conf` file without an exit on it)
- Execute the game
- Exit the game by using the game's interface (returning to the DOSBox console)
- On DOSBox console type: `exit`

It will close and re-open again.

###### Version and environment

```
Version: 0.14.1-b286d46-makepkg
Branch:  makepkg
Commit:  b286d46 (b286d467b67cae2f727105ae7a356a6bceec63c1)
Distro:  NAME=Arch Linux
DE:      Yaru:ubuntu:GNOME
```

**Comment by tkashkin** [comment]
GameHub did process Enter key press and it restarted selected game. 1 second timeout is added after game finishes to prevent restarts like this.

**Comment by hlechner** [comment]
I can confirm the fix worked
