### ISSUE TITLE
Gamehub not seeing retroarch

### ISSUE THREAD

**Issue by PRAEst-76** [tkashkin/GameHub#283]
Gamehub isn't seeing retroarch on my system. I've installed retroarch from flatpak. Is this likely the issue? I've added the dirs for the cores and info but GameHub still says retroarch is not installed.  

Where is it looking for retroarch?

**Comment by tkashkin** [comment]
GameHub expects `retroarch` executable somewhere in `$PATH`.
As a workaround you can create `retroarch` script and place it somewhere in `$PATH`:

```bash
#!/bin/sh
flatpak run com.retroarch.flatpak.id.here "$@"
```

**Comment by PRAEst-76** [comment]
Geneius. That's done the trick.

**Comment by thulsa18** [comment]
Sorry, I'm quite new to all this but could someone explain this in more detail? I guess it is like a bat file for windows but how do I create it and where and what exactly do I need to put in (it seems that I have to put a flatpak ID, where do I get that from)?
