### ISSUE TITLE
cannot login to Humble Bundle

### ISSUE THREAD

**Issue by loaderini** [tkashkin/GameHub#284]
Is it possible that Humble Bundle changed something in their API? I tried to login via the latest stable version but so far, no success. Only the HB logo is showing, no login textboxes at all, as you can see in the screenshot. Does anyone else have this problem?
![Screenshot from 2019-07-12 15-08-58](https://user-images.githubusercontent.com/46679913/61127158-1af8e380-a4b7-11e9-96f3-4d0893cf0289.png)

**Comment by cafehaine** [comment]
duplicate of #272 ?

**Comment by loaderini** [comment]
ah yes, this is duplicate. delete then, it is not needed!
