### ISSUE TITLE
Gamehub fails to detect Steam Proton

### ISSUE THREAD

**Issue by digital-idiot** [tkashkin/GameHub#287]
The `Gamehub` fails to launch steam when linking `Steam`. Consequently, it fails to detect `Proton`. The `Steam` along with games on `Proton` works fine when launched independently, and `STEAM_RUNTIME` is being used. Below is the verbose log of `Steam` when launched separately from terminal:

```
Running Steam on manjarolinux 18.0.4 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
...
```

###### Expected behavior
It should open the option to link Steam

###### Actual behavior
It states:
```
Fatal error: Failed to load steamui.so
```

###### Steps to reproduce
Open `Gamehub` -> choose `Steam (Authentication Required.)`

###### Version and environment

```
[INFO]   Version: 0.14.2--
[INFO]   Branch:
[INFO]   Commit:   ()
[INFO]   Distro:  Manjaro Linux
[INFO]   DE:      KDE
Running Steam on manjarolinux 18.0.4 64-bit
STEAM_RUNTIME is disabled by the user
Error: You are missing the following 32-bit libraries, and Steam may not run:
libgtk-x11-2.0.so.0
libgdk_pixbuf-2.0.so.0
libbz2.so.1.0.6
Error:
You are missing the following 32-bit libraries, and Steam may not run:
libgtk-x11-2.0.so.0
libgdk_pixbuf-2.0.so.0
libbz2.so.1.0.6
Press enter to continue: Installing breakpad exception handler for appid(steam)/version(1563346602)
Installing breakpad exception handler for appid(steam)/version(1563346602)
Failed to load steamui.so - dlerror(): libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

```
Strangely, all the files reported missing in the  above log are actually present at their respective locations. Since these files are part of `gtk2` package, I also checked if these files are modified using `sudo pacman -Qkk gtk2` and below is the output:

```
gtk2: 819 total files, 0 altered files
```

**Comment by tkashkin** [comment]
As far as I know Steam runtime currently ships development version of some library and it doesn't work with `steam-native` runtime.

In your case it seems that `steam-native` launches from GameHub instead of `steam`.

GameHub doesn't launch Steam binaries directly. It uses [`steam://`](https://developer.valvesoftware.com/wiki/Steam_browser_protocol) protocol.

`steam-native` is probably set as a URL handler. See #226 and #117.

**Comment by digital-idiot** [comment]
I do not have `steam-native` installed. However, I tried to open the `steam url` using `xdg-open steam://store` as suggested in #117 and it is trying to access `steam-native` as you suspected. Also, when accessing the same from browser it is trying to open it in `LSI Steam`. I think the problem is related to `MIME types`. Do you have any idea how to fix this?

**Comment by digital-idiot** [comment]
The problem was the `linux-steam-integration` where `steam-native` was enabled. Switching to `steam-runtime` from `linux-steam-integration` fixed the issue.

![linux-steam-integration](https://user-images.githubusercontent.com/10576475/61844743-21775a00-aebe-11e9-96f6-8656ae233e24.png)
