### ISSUE TITLE
Installer Backup Management

### ISSUE THREAD

**Issue by MessedUpHare** [tkashkin/GameHub#29]
Feel free to take this or leave it, depending on what you feel the scope of your app is.

But.. If I could:
* provide a directory to be recursively indexed where I store my DRM free installers
* Use information gained from files to match to identifying data provided by the relevant APIs (hashes are the best go-to here)
* bonus points would be given if it could obtain updates and allow me to download them to my existing archive.

Obveously I *could* use your existing .installers structure to recreate this, but it would mean me renaming the files I have already received to your naming convention.

Taking a tertiary look at the Humble payload, it appears to provide sha hashes which could be used to verify if these downloads already exist - the downside of this is that the hashes would need to be obtained from all files in the provided directory.
Unfortunately, GOG only seem to provide bytesize which *could* be a good indicator, but obviously less ideal, perhaps these could be verified by checking bytesize against filename (as it would be unusual to rename the files after download) to provide a more fuzzy match.

**Comment by tkashkin** [comment]
Interesting idea.

Matching existing files to API data will be the most difficult part.

---

###### GOG
GOG API does not give much useful information except size.
Original filename is not available also. It should be possible to extract from redirect headers, but it would require another request just to fetch filename.

<details><summary>GOG installer info example</summary>

```json
{
	"id": "installer_linux_en",
	"name": "VVVVVV",
	"os": "linux",
	"language": "en",
	"language_full": "English",
	"version": null,
	"total_size": 67108864,
	"files": [
		{
			"id": "en3installer1",
			"size": 67108864,
			"downlink": "http://api.gog.com/products/1207659753/downlink/installer/en3installer1"
		}
	]
}
```

</details>

###### Humble
Humble API gives more useful info like filesize, timestamp, hashes(md5 and/or sha1).
Original filename can be extracted from URL.

<details><summary>Humble installer info example</summary>

```json
{
	"machine_name": "outlast_linux",
	"platform": "linux",
	"download_struct": [
		{
			"human_size": "2.9 GB",
			"name": "Download",
			"url": {
				"web": "https://dl.humble.com/Outlast-1.01.sh?gamekey=...",
				"bittorrent": "https://dl.humble.com/torrents/Outlast-1.01.sh.torrent?gamekey=..."
			},
			"timestamp": 1428010088,
			"file_size": 3082157623,
			"small": 0,
			"md5": "742777ae1a994d9ce145fd686806e504"
		}
	],
	"options_dict": {},
	"download_identifier": null,
	"android_app_only": false,
	"download_version_number": null
}
```

</details>

---

Maybe the easiest way would be to just check if filename contains parts of game name.

@MessedUpHare can you give an example of how do you store your installers collection?

**Comment by MessedUpHare** [comment]
@tkashkin I tend to store all my "purchased" items on a backup drive / NAS.
It's hard to store them without some storage logic conflicts when you start collecting things from various sources. Especially as I back up files for things such as windows installers, purchased ebooks, video tutorial series' and music.
Equally, this gets tricky with the likes of  humble bundle, when they have the concept of a "purchased bundle" separate from a purchased item.. so i might have more than one item with the same human readable name.
But I usually do something simple like.
./$supplier/$product_name/$installer_filename_as_downloaded
e.g.
./GOG/Dead\ Cells/dead_cells_en_v9_2_21849.sh

**Comment by MessedUpHare** [comment]
All-in-all - it's probably a loss-leader to use anything but hash matching for this feature.
Some would even argue md5sum / sha1 provided by humble isn't good enough.

In saying this, GOG *must* provide hashes for some files over an api somewhere - or their GOG Galaxy product wouldn't work very effectively - as it's able to "verify" installs.

**Comment by tkashkin** [comment]
> GOG must provide hashes for some files over an api somewhere

Problem is that APIs are not documented. There are [unofficial docs](https://gogapidocs.readthedocs.io/en/latest/) for GOG API, maybe there are hashes somewhere.

**Comment by neuromancer** [comment]
According to the documentation, it seems to include installers:
```

.. http:get:: /products/(int:product_id)/(str:dl_url)

    Returns secure url and chunklist for a file.

    **Example request**:

    .. sourcecode:: http

        GET /products/1207658691/downlink/installer/en1installer3 HTTP/1.1
        Host: api.gog.com

    **Example response**:

    .. sourcecode:: json

        {
          "downlink": "https://cdn.gog.com/secure/unreal_tournament_2004_ece/pc/setup_ut2004_2.0.0.6.exe?a3c669cc2530fcf96b5599c0b5ceeb6a8179fe593c36d93e3396d982826ae9b366853042adc7efdeed599f74be21ec6615c731f9d25fc1e95c2711d7782b7beb2686dcd53a64440c04be87da3549947b72d90f5365ffaf1efcd51b633fc6c621ab3394540348f5b669f30782673bcc251a965dc82f33148b7e852070027e20b5eb56e05c460bd099cf17db03e4a9bdc01255ffe32bfd4f41019e8e7150694a5c&fileExtForIe=.exe",
          "checksum": "https://cdn.gog.com/secure/unreal_tournament_2004_ece/pc/setup_ut2004_2.0.0.6.exe.xml?a3c669cc2530fcf96b5599c0b5ceeb6a8179fe593c36d93e3396d982826ae9b366853042adc7efdeed599f74be21ec6615c731f9d25fc1e95c2711d7782b7beb2686dcd53a64440c04be87da3549947b72d90f5365ffaf1efcd51b633fc6c621ab3394540348f5b669f30782673bcc251a965dc82f33148b7e852070027e20b5eb56e05c460bd099cf17db03e4a9bdc01255ffe32bfd4f41019e8e7150694a5c&fileExtForIe=.exe"
        }

    **Example chunklist**:

    .. sourcecode:: xml

        <file name="gog_tis_100_2.0.0.3.sh" available="1" notavailablemsg="" md5="8acedf66c0d2986e7dee9af912b7df4f" chunks="4" timestamp="2015-07-30 17:11:12" total_size="36717998">
            <chunk id="0" from="0" to="10485759" method="md5">7e62ce101221ccdae2e9bff5c16ed9e0</chunk>
            <chunk id="1" from="10485760" to="20971519" method="md5">b80960a2546ce647bffea87f85385535</chunk>
            <chunk id="2" from="20971520" to="31457279" method="md5">5464b4499cd4368bb83ea35f895d3560</chunk>
            <chunk id="3" from="31457280" to="36717997" method="md5">0261b9225fc10c407df083f6d254c47b</chunk>
        </file>
```

but you are right. It most likely won't work for Linux games since Galaxy is not supported there. At least it can help to identify and download games from other platforms.

**Comment by MessedUpHare** [comment]
I also found this when I had a look, issuing queries against linux builds returns a "no support" response.

I've found the following "wishlist" petitions for the feature, but they don't seem to have much traction:
https://www.gog.com/wishlist/site/add_hashes_to_the_files
https://www.gog.com/wishlist/site/display_sha1_md5_or_crc32_hashes_to_verify_the_downloaded_parts
https://www.gog.com/wishlist/site/add_a_public_list_of_hashes_for_all_game_files_and_installers
https://www.gog.com/wishlist/site/return_hashchecksum_checking_to_single_file_installers

I guess we could start building our own database of these hashes using this system (and looking around the web some people have started trying) - but also provide this as a separate web service...

**Comment by tkashkin** [comment]
There are checksums for Linux installers.

```json
<file name="gog_amnesia_the_dark_descent_2.0.0.3.sh" available="1" notavailablemsg="" md5="272b9e4ca2028d90d6b41557e46d5473" chunks="131" timestamp="2015-07-01 18:47:57" total_size="1368076038">
    <chunk id="0" from="0" to="10485759" method="md5">7069c5ee794b93e3a5b3eb7135c01df7</chunk>
    ...
    <chunk id="130" from="1363148800" to="1368076037" method="md5">2e4c21d8fc00dac44525980cf35d87ff</chunk>
</file>
```

**Comment by tkashkin** [comment]
Commit 42816ef allows to implement simple form of collection quite easy.
It will download installers/dlc/bonuses in user-specified directory and skip download if file already exists. It already user original filenames with latest commit.

For collection directory structure I'm thinking about something like this:
![image](https://user-images.githubusercontent.com/2003017/44310007-f47e1580-a3d7-11e8-96f3-61a5f20f8e9b.png)
It should probably cover any sane collection structure I can think of. Let me know if I've missed some useful variables or options.

**Comment by tkashkin** [comment]
With 055c51a simple form of collection management works. You can hover on the fields in settings to preview how variables will expand.

**Comment by neuromancer** [comment]
Are the button to download bonus content clickable?

**Comment by tkashkin** [comment]
Downloading is not implemented yet.

**Comment by neuromancer** [comment]
Anyway, installers are correctly placed in the (GOG/HumbleBundle) folder inside the collection folder.

**Comment by tkashkin** [comment]
GOG bonus content downloading is now implemented.
