### ISSUE TITLE
Install option is grayed out on some GOG games.

### ISSUE THREAD

**Issue by burdebc** [tkashkin/GameHub#296]
###### Expected behavior
The install button below the title of the game to not be grayed out and to react when moused over.  

###### Actual behavior
The install button is grayed out and not clickable.  I have built both versions of gamehub in the AUR and used the appimage as well.  No matter what version I use I seem to have the same problem with the same games.  I ended up launching GameHub from a terminal to get some idea what was happening and keep getting the following error messages:

[FATAL]  [Json] json_object_get_object_member: assertion 'node != NULL' failed
[FATAL]  [Json] json_object_get_string_member: assertion 'object != NULL' failed

The first error message appears immediately when I click on one of the affected games and the second occasionally shows several seconds after clicking on a game.  I have also checked some of the affected games on other systems and they seem to have no issues.

I have tried to find where GameHub saves my login credentials and user preferences so I could delete that and cause the program to recreate those files the next time I launch the program.  If you can tell me where that file is I will delete it and see if that fixes the issue.

![gamehub_screenshot](https://user-images.githubusercontent.com/11868400/63232404-40cb8380-c1ed-11e9-8635-b4dd19f9b694.png)

###### Steps to reproduce
The problem happens every time I launch the program and requires no other action to cause.

###### Version and environment
[INFO]   - GameHub
[INFO]       Version: 0.14.2-4bb1b7f-master
[INFO]       Branch:  master
[INFO]       Commit:  4bb1b7f6779b8498e15c4a5a02b20a1377dd70b1
[INFO]   - Environment
[INFO]       Distro:  Manjaro Linux
[INFO]       DE:      KDE
[INFO]       GTK:     3.24.10
[INFO]       Themes:  Arc-Darker | Flat-Remix-Blue-Dark

```
PASTE VERSION INFO HERE
```

**Comment by tkashkin** [comment]
It looks similar to #294. Does it happen with games that have icon?

If this is same issue, it should be fixed in dfab162. Update to latest dev version.

You'll need to remove affected games from database.
Select all affected games in list and use `Refresh` action or remove the entire database (`~/.cache/com.github.tkashkin.gamehub/gamehub.db`).

**Comment by burdebc** [comment]
It only happened to games that didn't have an icon, but a few games that didn't have an icon next to them still acted normally otherwise.  After looking at issue #294 it may very well be the same or a similar issue happening.

I was able to build the latest dev version and refresh the games that were affected to fix the issue as you suggested.  Thanks for the quick response.

**Comment by nickcorona** [comment]
This issue isn't fixed.
