### ISSUE TITLE
Install option for Gwent (GOG) is grayed out

### ISSUE THREAD

**Issue by HarryPhoon** [tkashkin/GameHub#298]
###### Expected behavior
I expect Gwent to be installable.

###### Actual behavior
Gwent cannot be installed. The install option is grayed out.

###### Steps to reproduce
Open GameHub, add GOG account, click on Gwent, try to click Install.

###### Additional info
My system is specifically Fedora Silverblue.

###### Version and environment
- GameHub
    Version: 0.14.2-dfab162-dev
    Branch:  dev
    Commit:  dfab162dccde12b7c7d5f58f5c7f6384c86c5e80
- Environment
    Distro:  [Flatpak] Fedora release 30 (Thirty)
    DE:      GNOME
    GTK:     3.22.30

**Comment by tkashkin** [comment]
Initially I have thought it's the same issue as #294 and #296, but it's not.

GOG API doesn't return any downloads for Gwent:

https://api.gog.com/products/1971477531?expand=downloads
```json
"downloads": {
    "installers": [],
    "patches": [],
    "language_packs": [],
    "bonus_content": [
        {
            "id": 81937,
            "name": "soundtrack (MP3)",
            ...
        },
        {
            "id": 81940,
            "name": "soundtrack (WAV)",
            ...
        }
    ]
}
```

Is it even possible to install it via Galaxy? I think it was distributed as a separate installer on release.

**Comment by HarryPhoon** [comment]
From what I know you install and play Gwent through Galaxy (but I may be wrong). It has been a long time since I played it on Windows and on Linux it never worked out really.

**Comment by nickcorona** [comment]
Closed for what reason? It's not solved.

**Comment by tkashkin** [comment]
@nickcorona Try reading next time:

> GOG API doesn't return any downloads for Gwent

There's nothing to install therefore install option is disabled.

**Comment by nickcorona** [comment]
But you do install Gwent from Galaxy. There isn't a separate installer.

**Comment by tkashkin** [comment]
@nickcorona go ahead and try to find any installer in [API response](https://api.gog.com/products/1971477531?expand=downloads).
Or try to find a DRM-free Gwent installer which does not require or install Galaxy.

<details>
<summary>...</summary>

_Gwent is a CDPR game which uses Galaxy for multiplayer and is available exclusively through Galaxy._

</details>
