### ISSUE TITLE
$root_dir variable not respected for GOG games installation

### ISSUE THREAD

**Issue by killruana** [tkashkin/GameHub#299]
#### Expected behavior
The GOG games should be installed in the directory specified by the $root_dir, /home/killruana/opt/games for my case.

###### Actual behavior
The GOG games are installed in the default directory,  /home/killruana/Games for my case. However, the games installer are downloaded at the good place.

###### Steps to reproduce
Modify the $root_dir variable ("Collection directory" in the settings)

###### Version and environment

```
- GameHub
    Version: 0.14.2-3821042-dev
    Branch:  dev
    Commit:  382104204f084547534530c0519a53635af089f5
- Environment
    Distro:  Ubuntu 19.04
    DE:      XFCE
    GTK:     3.24.8
```

**Comment by tkashkin** [comment]
Collection is where installers, DLC and bonus content are stored.
Games installation directory is configured in GOG/Humble tabs in settings.
