### ISSUE TITLE
Games don't run

### ISSUE THREAD

**Issue by haytham-med** [tkashkin/GameHub#316]
###### Expected behavior
Games open and run

###### Actual behavior
Games don't run, native or not

###### Steps to reproduce
Right click and select run, I'm using kde

###### Version and environment
0.14.2

```
- GameHub
    Version: 0.14.2-4693bf5-dev
    Branch:  dev
    Commit:  4693bf508267feff52e0ac7205b80796f1330a75
- Environment
    Distro:  Ubuntu 18.04.1 LTS
    DE:      KDE
    GTK:     3.22.30
    Themes:  Breeze | breeze
```

**Comment by haytham-med** [comment]
I get this error When launching gamehub from terminal and trying to open games

[WARN]   The specified location is not supported

**Comment by neuromancer** [comment]
Are you using a FAT/NTFS partition or something like that?

**Comment by tkashkin** [comment]
Run `com.github.tkashkin.gamehub -d --verbose, try to run a game and copy full log here.

**Comment by haytham-med** [comment]
Here: https://pastebin.com/EDr93YCk

**Comment by tkashkin** [comment]
There's nothing interesting in log.

Are you trying to run a Steam game? If this case it's most likely related to Steam .desktop files. See #263, #226, #117.

If you are trying to run a non-Steam game it may not be configured properly. Attach a screenshot of game's properties.

> `Version: 0.14.2-be55ac0-master`
`Branch:  master`
`[Database.migrate] Latest db version: 8, current: 9`

You have tried recent versions from `dev` branch, but now are using older version from `master` branch without removing games database. While it may work fine, it may as well cause unexpected problems.

**Comment by haytham-med** [comment]
I do have games installed on multiple partitions.

**Comment by tkashkin** [comment]
Closing until more information is provided.

**Comment by haytham-med** [comment]
Here, found this in terminal:

```
hay207@hay207-Lenovo-G50-70:~$ com.github.tkashkin.gamehub --run steam:380840
[FATAL]  uint64_parse: assertion 'str != NULL' failed
[FATAL]  game_hub_utils_fs_utils_find_case_insensitive: assertion 'root != NULL' failed
[INFO]   Starting `Teeworlds`
[WARN]   [Utils.open_uri] Error while opening 'steam://rungameid/380840': The specified location is not supported
[INFO]   `Teeworlds` finished
hay207@hay207-Lenovo-G50-70:~$ 

```

**Comment by haytham-med** [comment]
This solved it 
`update-mime-database $HOME/.local/share/mime`
And
`update-desktop-database $HOME/.local/share/applications`
