### ISSUE TITLE
Adding a shortcut to steam deletes all existing shortcuts

### ISSUE THREAD

**Issue by Lucki** [tkashkin/GameHub#319]
###### Expected behavior
Adding a shortcut to steam adds the shortcut to steam without removing existing ones.

###### Actual behavior
All previous existing shortcuts are deleted.

###### Steps to reproduce
* Have some custom shortcuts in your steam library.
* Click the "add to steam" button to let gamehub create a shortcut into your steam library.
* See every previous shortcut removed.

###### Version and environment

```
$ gamehub -v
- GameHub
    Version: 0.14.2-cf641ac-makepkg
    Branch:  makepkg
    Commit:  cf641ac8e795f8906bf359b34c4fcb66e7076fdd
- Environment
    Distro:  Arch Linux
    DE:      GNOME
    GTK:     3.24.12
```

**Comment by tkashkin** [comment]
Most likely something has changed with new Steam Library.
