### ISSUE TITLE
Missing Humble Bundle games

### ISSUE THREAD

**Issue by saward** [tkashkin/GameHub#325]
Hi,

I seem to have some games missing from the list.  Investigating into it, it appears that the website uses the same URL as GameHub, but with an additional parameter: `all_tpkds=true`

If I include that, then the games that were missing from GameHub appear in the API response, but without it they do not.

I don't really know what all_tpkds is for, or why some games are excluded, so I understand you may be aware of this.

Thanks!

**Comment by tkashkin** [comment]
It seems Humble returns platform keys with `all_tpkds=true` in addition to Humble games.
GameHub only shows games available to download from Humble directly.

Reopen if you can download game directly from Humble, but it is not shown in GameHub.

**Comment by saward** [comment]
Ah yes, that makes sense.

One of the reasons I use something like GameHub is to keep track of which games I've obtained across platforms.  Sometimes that means games that have keys available on Humble Bundle that I haven't yet redeemed.

Do you think there's any possibility of GameHub helping play that role?  For example, another mode that lists everything, not just downloadable games?
