### ISSUE TITLE
Non-Linux games support

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#33]
The [nebula goglib scripts repository](https://gitlab.com/yancharkin/games_nebula_goglib_scripts) contains some scripts to integrate additional games that are marked as Windows only, but can work in other platform (e.g. using dosbox or wine).

Related: https://github.com/tkashkin/GameHub/issues/15#issuecomment-407053603

**Comment by tkashkin** [comment]
Right now I want to focus on native Linux games, but it may be reopened later.

**Comment by neuromancer** [comment]
Non-Linux games can be easily downloaded, this is great! Can you please add an option to decompress InnoSetup installers using [innoextract](http://constexpr.org/innoextract/) (`innoextract -g -d <outdir>` should be enough). After that, we can close this issue.

**Comment by tkashkin** [comment]
Ok, I'll add that.
What mime-type do GOG Windows binaries usually have? What mime-type do data files have? (not implemented yet, check #50)

**Comment by tkashkin** [comment]
> (downloading is not implemented yet, check #50)
> Some of them seem to be working (e.g. Dangerous Dave Pack)

I was talking about [this](https://github.com/tkashkin/GameHub/issues/50#issuecomment-416069545), it's not implemented yet, it will download only first file.

**Comment by tkashkin** [comment]
@neuromancer It's implemented now. It should extract GOG installers with `innoextract`.

I've tested it with a few games and for most of them it resulted in working unpacked game which can be run with wine.

If installer contains some files in `tmp` or any other subdir except `app`, only `app` contents will be kept. Such installers (e.g. Age of Wonders) should be executed with wine or on Windows to get game files.

After extraction you can create `start.sh` wrapper script to be able to run game directly from GameHub.
In many cases something simple will work.
```bash
#!/bin/sh
wine <GameBinary>.exe
```

**Comment by neuromancer** [comment]
This is absolutely great!, I will be able to test this in a few days, but thanks a lot for implementing this feature!
