### ISSUE TITLE
Units (Megabytes vs Mebibytes)

### ISSUE THREAD

**Issue by hibes** [tkashkin/GameHub#335]
It would be nice to be able to control whether units are displayed in Mebibytes or Megabytes.  Currently, it looks like the application is displaying in Megabytes.

Probably not necessary, but in case it's helpful:
https://en.wikipedia.org/wiki/Mebibyte

**Comment by tkashkin** [comment]
It's possible, but is it really important enough to add a switch to Settings? There's already enough options there.

I can add a dconf option without showing it in UI, but then no one would know about it.

Are there any global settings used by DEs or file managers? If there are, GameHub could read them and adjust automatically.

**Comment by tkashkin** [comment]
Also GLib documentation is against this.

https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#GFormatSizeFlags:

> **G_FORMAT_SIZE_IEC_UNITS** - use IEC (base 1024) units with "KiB"-style suffixes. IEC units should only be used for reporting things with a strong "power of 2" basis, like RAM sizes or RAID stripe sizes. Network and storage sizes should be reported in the normal SI units.

**Comment by hibes** [comment]
Interesting, I didn't know that.  The only reason I even really noticed or cared was because the actively downloaded file sizes in the GUI didn't match the file sizes of files I already had on disk from a different GoG client.

I agree it's probably not worth a settings switch in the main settings menu.  Given GLib's stance, I wouldn't really care if you closed this and chose not to implement it.  

Very cool client you (et al?) have built, thanks for sharing it!

**Comment by tkashkin** [comment]
Closing now, will possibly reopen in future if there are more requests for this.
