### ISSUE TITLE
Define Libretro cores default location

### ISSUE THREAD

**Issue by tim77** [tkashkin/GameHub#336]
Hello. Would be nice to define Libretro cores default location in Meson during build process since some of them packaged in some distros.

**Comment by tkashkin** [comment]
Now it's possible with
```bash
meson ... -Dlibretro_core_dir=/usr/lib/libretro -Dlibretro_core_info_dir=/usr/share/libretro/info
```

**Comment by tim77** [comment]
@tkashkin thank you a lot.
