### ISSUE TITLE
Steam game do not start.

### ISSUE THREAD

**Issue by leucome** [tkashkin/GameHub#338]
When I try to launch a Steam game I get an error like this

[WARN]   [Utils.open_uri] Error while opening 'steam://rungameid/346110': The specified location is not supported

I wonder what is causing this.  I already tried reinstalling steam.  I tried the latest Gamehub appimage and also the the two version of gamehub available on AUR. 

Other launcher and common link are able to launch the games as expected.  The game also start properly if I add them manually pointing  to /usr/bin/steam  and an argument steam://rungameid/457140

I'm using Manjaro and and there is multiple game library one a SSD in F2fs on an a HDD in Ext4 an other on a NTFS HDD.  Last one is library in the system root a Nvme in F2fs.  Not sure it's relevant but since the error is about location I thought it may be related.  Or maybe it's about the location of the steam executable or about the access right.

**Comment by tkashkin** [comment]
See #263, #226, #117.

**Comment by leucome** [comment]
Yes thanks, I found the issue.
There was nothing set for  "MimeType="  in my steam.desktop
