### ISSUE TITLE
Multiple selection tagging and search

### ISSUE THREAD

**Issue by Willdrick** [tkashkin/GameHub#344]
With a large library, generating the tags for games is really cumbersome, It'd be nice if in list mode you could ctrl+click or shift+click to select multiple titles and apply tags to them, like the new library on Steam.

Also it'd be a nice extra feature if tags were not relegated only to the filters on top but searchable. Instead of having to turn off all tags first, and then select the one you want, you could just search, even adding some operations (like using a - to signify "not" before a search term).
For example, search for "racing -rally" would show all racing games, excluding the rally titles.

**Comment by tkashkin** [comment]
> It'd be nice if in list mode you could ctrl+click or shift+click to select multiple titles and apply tags to them

It's already possible. You can use <kbd>Ctrl + click</kbd> to select individual games or <kbd>Ctrl + A</kbd> to select all filtered games. <kbd>Shift + click</kbd> currently is not supported.

![image](https://user-images.githubusercontent.com/2003017/75612622-66d7c600-5b36-11ea-9cb4-5deddaf14f12.png)

**Comment by Willdrick** [comment]
Sorry there must have been something on my end that was preventing me to doing so, I just tried and works! Thanks a lot for the help (and for your awesome software :smile: )

**Comment by tkashkin** [comment]
> What about the search? is it feasible?

Should be feasible. No ETA now as I'm currently refactoring large part of code and it will take some time to finish.

**Comment by Willdrick** [comment]
I never ask for ETAs, it's utterly annoying. Thanks again for your time
