### ISSUE TITLE
Removal of GOG games require to click on "Uninstall" button

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#35]
It will be nice to have completely automatic removal of games, without requiring the user to interact with the uninstaller.

**Comment by tkashkin** [comment]
Fixed for next release.
It will execute uninstaller with `--noprompt --force` parameters if it exists or fallback on directory removing if not.
Uninstaller won't show confirmation dialog and will automatically close after uninstallation. Progress window will still be visible if uninstallation is long enough.

**Comment by neuromancer** [comment]
Tested it in the last git revision and it works great!
