### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Dhop84** [tkashkin/GameHub#356]
Hi, is this just for Linux or can it work on windows 10?

**Comment by hanaral** [comment]
Sorry my dude, it's SteamOS+Linux. You could try it on a bootable usb, but if you want to actually play games on it you could install it on a Pop!_OS partition.

**Comment by tkashkin** [comment]
GameHub is Linux-only right now, but it can be ported to Windows (and maybe macOS) with some time and effort.
No plans for it currently and it's unlikely, especially when other good alternatives already exist for Windows. See #176.
