### ISSUE TITLE
Steam authentication required, config file not found.

### ISSUE THREAD

**Issue by manderso7** [tkashkin/GameHub#357]
###### Expected behavior
Steam & steam games are seen and linked into library.

###### Actual behavior
Steam shows "Authentication required. Steam config file not found. Login into your account in Steam client and return to GameHub.

Opened gamehub from cli, no errors, get the following when I click the steam portion in the "lets get started" window:
```
gamehub
[INFO]   - GameHub
[INFO]       Version: 0.15.0-ae21180-dev
[INFO]       Branch:  dev
[INFO]       Commit:  ae211801176f60fb4d99e1753f236496f872838f
[INFO]   - Environment
[INFO]       Distro:  Ubuntu 19.10
[INFO]       DE:      ubuntu:GNOME
[INFO]       GTK:     3.24.12
[INFO]       Themes:  Yaru | Yaru
Running Steam on ubuntu 19.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/manderso/.local/share/Steam/ubuntu12_32/steam steam://

(gamehub:3376): Gtk-WARNING **: 07:59:27.663: gtk_window_set_titlebar() called on a realized window
```
###### Steps to reproduce
Install GameHub and Steam, login to steam client, set installation directory to $HOME/.local/share/Steam. Neither GameHub nor Steam are flatpak's or snaps. 
I've also tried using a Steam API key, and still not seeing steam library in gamehub. 

Do I need to uninstall the dev version and try the prod version?

###### Version and environment

```
- GameHub
    Version: 0.15.0-ae21180-dev
    Branch:  dev
    Commit:  ae211801176f60fb4d99e1753f236496f872838f
- Environment
    Distro:  Ubuntu 19.10
    DE:      ubuntu:GNOME
    GTK:     3.24.12
    Themes:  Yaru | Yaru
```

**Comment by Lucki** [comment]
Gamehub expects the (legacy?) steam root folder as location so try `$HOME/.steam`.

**Comment by tkashkin** [comment]
Currently GameHub expects [`${steam_home}/steam/config/loginusers.vdf`](https://github.com/tkashkin/GameHub/blob/dev/src/utils/FSUtils.vala#L95-L108) to read user id.
I'll improve Steam paths detection in future.

**Comment by manderso7** [comment]
I have steam installed in my home dir, w/ loginusers.vdf in ~/.steam/steam/config/, I've uninstalled and reinstalled Gamehub as well as uninstalled, deleted cache and reinstalled. I've installed the latest stable version from the website as well as from your repo, still seeing the same error, Authentication required, steam config file not found, login to your account in steam client...
```
manderso@wtfnix:~/.steam/steam/config$ cat loginusers.vdf 
"users"
{
	"76561197993022522"
	{
		"AccountName"		"manderso"
		"PersonaName"		"manderso"
		"RememberPassword"		"1"
		"MostRecent"		"1"
		"Timestamp"		"1585396785"
	}
}
```

**Comment by manderso7** [comment]
> Gamehub expects the (legacy?) steam root folder as location so try `$HOME/.steam`.

This worked like a charm, thank you good person!
