### ISSUE TITLE
Wrong workdir when using proton

### ISSUE THREAD

**Issue by Lucki** [tkashkin/GameHub#359]
Workaround used for #358: By restarting GameHub the correct workdir gets set for that game.

When using proton the wrong workdir is used compared to wine directly or a **custom script invoking the proton command by itself**. To get the working directory used by a process you can use `readlink -f /proc/$pid/cwd`.

###### Expected behavior

The process spawned with Proton has the correct working directory.

###### Actual behavior

The process spawned with Proton has the working directory set to `$gamedir/_gamehub/compat/proton_latest/pfx/drive_c/windows`.

###### Steps to reproduce

1. Set up a game that needs the correct working directory.
    1. Don't touch the workdir setting to prevent #358 or restart gamehub to reset the value.
    1. Run the game using wine or a custom script…
    1. And verify the set working directory is correct with `readlink -f /proc/$(pgrep game.exe)/cwd`
1. Change the compat tool to Proton (latest)
1. Run the game, my example hangs forever so it's easy to…
1. Run `readlink -f /proc/$(pgrep game.exe)/cwd` to recognize the wrong workdir.

###### Version and environment

```
- GameHub
    Version: 0.15.0-6d20061-makepkg
    Branch:  makepkg
    Commit:  6d200618bb16a16cab849767d7381584f7ff440f
- Environment
    Distro:  Arch Linux
    DE:      GNOME
    GTK:     3.24.14
    Themes:  Numix-ArchBlue | Numix-Circle
```

**Comment by Lucki** [comment]
Not sure why but it looks like the issue is in the called function https://github.com/tkashkin/GameHub/blob/ae211801176f60fb4d99e1753f236496f872838f/src/utils/Utils.vala#L230
The `_dir` is correct but the game executable always has the workdir in `$gamedir/_gamehub/compat/proton_latest/pfx/drive_c/windows`. Changing `_dir` to `null` which inherits the parent workdir the game executable has the correct workdir of the location I started gamehub from. So when starting gamehub from the games folder the game starts successfully.

**Comment by cyan-lime** [comment]
![image](https://user-images.githubusercontent.com/54386705/79062695-ca314800-7cdf-11ea-9506-1bfd9cddfc9d.png)

Same problem here using the latest version from the Fedora repository, confirmed using the readlink command from the OP. The incorrect workdir causes a great deal of Windows games to fail to start. Interestingly, for me the issue only occurs when using Proton 5.0 to launch a game. Using Proton 4.11 instead uses the correct workdir and provides a seemingly flawless work-around.

```
- GameHub
    Version: 0.15.0-8a88b07-master
    Branch:  master
    Commit:  8a88b0796857fa6c30bca4eabd7da44e192cf1ad
- Environment
    Distro:  Fedora release 32 (Thirty Two)
    DE:      GNOME
    GTK:     3.24.17
    Themes:  Materia-light-compact | Adwaita
```

**Comment by Lucki** [comment]
Thanks! Comparing both versions I've found the problematic part. There's one suspicious line missing in the working log file:
~~~
wine: could not open working directory L"D:\\_gamehub\\_overlay\\merged\\", starting in the Windows directory.
~~~

`D:` is a [symlink created by gamehub](https://github.com/tkashkin/GameHub/blob/0d595257eeeb0da5e65b6b0529ff6a492ee90c4d/src/data/compat/Proton.vala#L175) which seems to be missing at the actual run besides many times deleted and recreated beforehand. Creating the symlink manually and removing permissions on the folder makes the symlink stay for the program run and it works like it should.

So there are to questions now:
1. Why is the symlink deleted before the program can run. (This also happens with the older proton)
1. Why is this only important for the recent proton version.
