### ISSUE TITLE
Custom script does not get install dir

### ISSUE THREAD

**Issue by gatl** [tkashkin/GameHub#360]
When calling a custom launch script gamehub does not pass the game's path as an argument (`$2` or `GH_INSTALL_DIR`). Instead it passes the game ID (the numeric value of `$GH_GAME_ID`), which is of little use to launch the game.

You can verify this by adding `echo $GH_INSTALL_DIR` to the end of the custom script template and checking its output when run.

I was unable to sidestep this issue by adding `$game_dir` to the arguments field of the executable.

**Comment by Lucki** [comment]
This was already mentioned in https://github.com/tkashkin/GameHub/issues/278#issuecomment-605073550 and https://github.com/tkashkin/GameHub/issues/278#issuecomment-605078601 which causing issue is probably #358 

As a workaround try restarting gamehub without touching the folder setting in game configuration window.
