### ISSUE TITLE
vkBasalt

### ISSUE THREAD

**Issue by MadMagnetic** [tkashkin/GameHub#380]
Could you consider adding vkBasalt https://github.com/DadSchoorse/vkBasalt ?
I think it can provide some good feautures.

**Comment by Blaster84x** [comment]
Paste this into your `.config/tweaks` folder as vkbasalt.json, try if it works. (Guess can't break anything with this kind of program)
```javascript
{
	"id": "vkbasalt",
	"name": "vkBasalt",
	"description": "Vulkan post processing layer to enhance the visual graphics of games",
	"url": "https://github.com/DadSchoorse/vkBasalt",
	"command": "ENABLE_VKBASALT=1 ${command}"
}
```

**Comment by Lucki** [comment]
I guess it's better to use "env" here. 
~~~ json
{
	"id": "vkbasalt",
	"name": "vkBasalt",
	"description": "Vulkan post processing layer to enhance the visual graphics of games",
	"url": "https://github.com/DadSchoorse/vkBasalt",
	"env": {
		"ENABLE_VKBASALT": "1"
	}
}
~~~

**Comment by MadMagnetic** [comment]
> I guess it's better to use "env" here.
> 
> ```json
> {
> 	"id": "vkbasalt",
> 	"name": "vkBasalt",
> 	"description": "Vulkan post processing layer to enhance the visual graphics of games",
> 	"url": "https://github.com/DadSchoorse/vkBasalt",
> 	"env": {
> 		"ENABLE_VKBASALT": "1"
> 	}
> }
> ```

It works! Thank you. Can please tell me - is there some "skeleton" to add custom tweaks (like this one)?

**Comment by Lucki** [comment]
https://github.com/tkashkin/GameHub/tree/master/data/share/tweaks
