### ISSUE TITLE
Renaming .tar.gz files is causing file-roller to fail the unpacking

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#39]
Some Humble Bundle games are distributed as tar.gz files (e.g. World of Goo, Crayon Physics). If you rename the file to remove the extension, file-roller will fail to uncompress it (I'm using file-roller 3.28.1 but other versions could be affected as well).

**Comment by tkashkin** [comment]
I did plan to use original file names as part of #29 and/or GOG/Humble download refactoring.

**Comment by tkashkin** [comment]
42816ef should use original filenames

**Comment by neuromancer** [comment]
I tested the last revision: the filenames are preserved and the extraction works, but GameHub stores the game in the `.installer` folder.

**Comment by tkashkin** [comment]
Do you mean game is extracted into `.installers`? Does your `file-roller` version support `-e` option?
```
$ file-roller --help
Usage:
  file-roller [OPTION…] — Create and modify an archive
  ...
  -e, --extract-to=FOLDER Extract archives to the specified folder and quit the program

$ file-roller --version
file-roller 3.28.0, Copyright © 2001-2012 Free Software Foundation, Inc.
```

**Comment by neuromancer** [comment]
> Do you mean game is extracted into .installers?

Yes, sorry!. For instance, `~/Games/HumbleBundle/.installers/crayon_physics_deluxe-linux-release55.tar.gz` is extracted to `~/Games/HumbleBundle/.installers/crayon_physics_deluxe-linux-release55`. The `~/Games/HumbleBundle/Crayon_Physics` folder is created, but it is empty. 

> Does your file-roller version support -e option?

Yes:
```

$ file-roller --help
Usage:
  file-roller [OPTION?] ? Create and modify an archive
  ...
  -e, --extract-to=FOLDER     Extract archives to the specified folder and quit the program

$ file-roller --version
file-roller 3.28.1, Copyright © 2001-2012 Free Software Foundation, Inc
```

**Comment by tkashkin** [comment]
Interesting. What happens if you execute `file-roller archive.tar.gz -e ~/some/path`?

**Comment by neuromancer** [comment]
```
$ file crayon_physics_deluxe-linux-release55.tar.gz 
crayon_physics_deluxe-linux-release55.tar.gz: gzip compressed data, last modified: Mon Aug 27 10:37:54 2012, from Unix, original size 4634624
$ file -i crayon_physics_deluxe-linux-release55.tar.gz 
crayon_physics_deluxe-linux-release55.tar.gz: application/x-gzip; charset=binary
$ xdg-mime query filetype crayon_physics_deluxe-linux-release55.tar.gz 
application/x-compressed-tar
```

**Comment by tkashkin** [comment]
So `application/x-compressed-tar` needs to be added. Do you have some other archives of different formats to test?

**Comment by neuromancer** [comment]
This one is also failing to install: 

```
$ file retrocityrampage-1.55-linux.x86_64.bin 
retrocityrampage-1.55-linux.x86_64.bin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=6a4c9b24c8fcd8a7fab0abd997f6cc0d6da21d73, not stripped
$ file -i retrocityrampage-1.55-linux.x86_64.bin 
retrocityrampage-1.55-linux.x86_64.bin: application/x-executable; charset=binary
$ xdg-mime query filetype retrocityrampage-1.55-linux.x86_64.bin 
application/octet-stream
```

**Comment by tkashkin** [comment]
Probably `GLib.File.query_info` outputs same type as `xdg-mime query filetype` and it differs from `file -i`.
The best way to solve this would probably be to fallback on `file -i` and then fallback on guessing type by extension.

Btw are all humble executables using MojoSetup or can they be anything?

**Comment by neuromancer** [comment]
> Btw are all humble executables using MojoSetup or can they be anything?

I think all (or most) of them are MojoSetup (but some could be based on very old versions of it). I can report any failing installation here from my library.

**Comment by neuromancer** [comment]
It works! Thanks!
