### ISSUE TITLE
Fix executable permissions for some games (distributed in zip files)

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#42]
Some lazy game developers in Humble Bundle distribute their games in zip files, which do not preserve the executable permissions (e.g. Cubemen) . A quick fix is to execute `chmod +x` in the the selected executable file once the installation is over.

**Comment by neuromancer** [comment]
According to the that code, the previous line calls file-roller (or the MojoSetup installer) and could be taking a little longer than expected to install. Maybe a race condition is causing that the `chmod +x` is not applied to all the files?

**Comment by tkashkin** [comment]
`yield` will stop execution of this method while command runs. But it's probably a good idea to move chmod a bit lower after next `try/catch` block since it's moving files from `game/some_unwanted_dir/*` to `game/*`.

**Comment by tkashkin** [comment]
Try 8dc569a.

**Comment by neuromancer** [comment]
Fixed!
