### ISSUE TITLE
[UI] [GRID] Disable game titles

### ISSUE THREAD

**Issue by Willdrick** [tkashkin/GameHub#422]
Issue: when setting up grid mode, most of the game boxart include the game title, making the text overlay redundant. This becomes even more aparent when you decide to use smaller box sizes.
![imagen](https://user-images.githubusercontent.com/2455158/90287856-125ba500-de4f-11ea-80ab-1fb7801a630a.png)

Suggested solution: add a button under preferences - Appearance to disable game titles when using GRID mode.
![imagen](https://user-images.githubusercontent.com/2455158/90288136-9d3c9f80-de4f-11ea-9fff-524eed6a4bf5.png)

**Comment by tkashkin** [comment]
Added for the next release.
I don't know when it will be stable since there's a lot of changes in [refactoring](https://github.com/tkashkin/GameHub/tree/refactoring) branch.

![image](https://user-images.githubusercontent.com/2003017/90296190-8029c000-de93-11ea-9239-e8205d766e0f.png)

**Comment by Willdrick** [comment]
Amazing, looks super clean, thanks a lot for your time!

**Comment by ccrowles** [comment]
Sorry to bother, but has this been implemented yet? I've apparently installed the latest dev version ([deb package 0.16.0-84-dev](https://elixi.re/i/zx7c.jpg), even though oddly in the "about" section of the software it says 0.16.0-47f1a86-dev) but I cannot find this option anywhere.
