### ISSUE TITLE
gamehub doesn't prevent monitor sleep

### ISSUE THREAD

**Issue by nergdron** [tkashkin/GameHub#426]
###### Expected behavior
When I game, monitor idle sleep behaviour is disabled.

###### Actual behavior
When I game using gamehub, at least for things using wine64, my monitor goes into sleep mode after 5m (per my gnome prefs), even though I'm actively playing a game.

###### Steps to reproduce
Play a game under gamehub with wine-staging from the winehq ppa on ubuntu 20.04.

###### Version and environment

```
- GameHub
    Version: 0.16.0-86365ee-dev
    Branch:  dev
    Commit:  86365eee80eb3e5fc38dac63bb165703bbed8fe5
- Environment
    Distro:  Ubuntu 20.04.1 LTS
    DE:      ubuntu:GNOME
    GTK:     3.24.20
```

**Comment by tkashkin** [comment]
Added for the next release.
