### ISSUE TITLE
Run games using their path as the working directory

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#43]
Some games require to run their executables from the installed directory to execute properly (e.g. Retro City Rampage). So, it will be useful to change the working directory (`chdir`) before execute them.

**Comment by tkashkin** [comment]
What path do such games usually need? Game dir or executable dir? What if executable is in some subdir?

**Comment by tkashkin** [comment]
Try 8dc569a.

**Comment by neuromancer** [comment]
Fixed!
