### ISSUE TITLE
Use HdyWindow for round window corners in preperation for elementary 6

### ISSUE THREAD

**Issue by hanaral** [tkashkin/GameHub#432]
Seems to be a consistency thing the elementary folk are pushing, I presume it will not be that difficult to implement.

**Comment by tkashkin** [comment]
I don't think there's currently any reason to migrate to `libhandy`:

* Round window corners don't seem to be worth adding a new dependency. Also they are achievable with regular CSS in most cases.
* I've considered using some of `Hdy*` widgets, but GameHub already has similar custom widgets with required behavior.
* `HdyHeaderBar` could be useful if GameHub did something weird with headerbars, but regular `GtkHeaderBar` is enough for now.
