### ISSUE TITLE
itch.io authentication error stdout jsonrpc "apiKey: cannot be blank."

### ISSUE THREAD

**Issue by sparr** [tkashkin/GameHub#445]
###### Expected behavior

Clicking "itch.io Authentication required" leads to an authentication prompt

###### Actual behavior

Clicking the button has no visible effect in the GUI, but produces the following output on stdout:

```
[WARN]   [ButlerClient: err 2] {"jsonrpc":"2.0","id":2,"error":{"code":-32603,"message":"apiKey: cannot be blank.","data":{"butlerVersion":"v15.20.0, built on Aug 28 2020 @ 03:35:05, ref b3c579dc115e3326e9a283a10f9b6712e017a3b7","stack":"apiKey: cannot be blank."}}}
```

(all the details and numbers remain the same when this message repeats on future clicks)

###### Steps to reproduce

Clicking "itch.io Authentication required"

###### Version and environment

```
- GameHub
    Version: 0.16.0-3ff389e-master
    Branch:  master
    Commit:  3ff389ea589076815256435971f5a99d593d9448
- Environment
    Distro:  Manjaro Linux
    DE:      XFCE
    GTK:     3.24.23
    Themes:  Matcha-sea | Papirus-Maia
```

**Comment by sparr** [comment]
This is a known problem, requires api key in settings. https://github.com/tkashkin/GameHub/issues/65

**Comment by emorrp1** [comment]
Can this be re-opened? I think the actual issue should focus on "Clicking the button has no visible effect in the GUI".

The startup page has reasonable feedback for if the app is not yet installed and it would be good if it could say "Missing api-key". I don't know if there's a message other api settings use for invalid/expired/revoked but maybe something generic like "Invalid api key" would be better.
