### ISSUE TITLE
Manually installing patches/language packs in overlays?

### ISSUE THREAD

**Issue by Tokariew** [tkashkin/GameHub#446]
Probably newbie question, but how to install manually patches and language packs for games from gog, because for example Witcher 3 Goty don't have dlc available in gamehub gui, but on gog page there is patch from 1.31 -> 1.32 and (gamehub install 1.31 version) and all installers for this game are english only, and after that you should manually install language pack…

Or is there option to install any executuble as mod?

**Comment by tkashkin** [comment]
Currently there's no such option. I plan to implement it some time in the future.

You can try to create an overlay manually and install patch there with Wine, Proton or InnoExtract.
