### ISSUE TITLE
Refactoring branch: Itch.io settings page is blank and cannot be enabled

### ISSUE THREAD

**Issue by ccrowles** [tkashkin/GameHub#451]
###### Expected behavior
Settings page for itch.io should stay enabled if I enable it, and show settings.

###### Actual behavior
Settings page for itch.io starts as disabled, I can toggle it to enable but stays blank, and when I return to that option tab/reopen settings it's disabled again and completely blank.
![image](https://user-images.githubusercontent.com/12866474/103211194-d01b9780-4907-11eb-9400-d163670e9428.png)

###### Steps to reproduce
Open settings page. Go to itch.io settings. Enable. Switch tab/close settings. Recheck itch.io settings tab.

###### Version and environment

```
- GameHub
    Version: 0.16.0-51dd7c8-refactoring
    Branch:  refactoring
    Commit:  51dd7c89416ca863ca3917581917350a8d63a036
- Environment
    Distro:  Ubuntu 20.04.1 LTS
    DE:      KDE
    GTK:     3.24.20
    Themes:  Breeze | candy-icons
```

**Comment by tkashkin** [comment]
This is expected. Refactoring branch is not ready and itch.io settings page is not implemented.

**Comment by ccrowles** [comment]
I see, thanks. But refactoring branch is the only one that has an option to disable game titles, right?

**Comment by tkashkin** [comment]
Yes. New features and fixes will be based on `refactoring` branch and will not be merged into `dev` or `master` branches until it's at least somewhat ready and usable.

**Comment by ccrowles** [comment]
Ok, thanks for the info!
