### ISSUE TITLE
[Feature Request] Being able to add environment variables and command prefixes for all games seperately and globally (like Lutris)

### ISSUE THREAD

**Issue by Toadfield** [tkashkin/GameHub#452]
I tried out gamehub for the first time and added all my Retroarch games,but I don't find any option to set Environment Variable and Command Prefixes for that game specifically or globally.

**Comment by tkashkin** [comment]
GameHub supports Tweaks that can change command line and environment variables globally or for selected games.

Tweaks are json files with self-explanatory syntax. See Tweaks page in Settings to get list of directories Tweaks are loaded from. Create a new file to add a new Tweak.

You can also change command line for a specific game using Arguments in game's properties. It works like launch options in Steam: it appends arguments to the end of command line unless there is a `${command}` variable.

There is no way to set environment variables without using tweaks in the current version, but it is already implemented in the `refactoring` branch.

**Comment by Toadfield** [comment]
Is there a way to create new tweaks directly in GameHub?
So by just setting the Environment Variable and name for that tweak in a gui Menu?

**Comment by Toadfield** [comment]
And for tweaks,how can I enable/disable them per game?
Cause I can't find anything [here](https://i.imgur.com/606HZbx.png).
And can I only set Environment Variables for tweaks or also command prefixes?

**Comment by Toadfield** [comment]
And do Tweaks work for Steam games?

**Comment by Toadfield** [comment]
thanks
