### ISSUE TITLE
[Feature Request] A GameHub Subreddit

### ISSUE THREAD

**Issue by Toadfield** [tkashkin/GameHub#454]
Sorry if that doesn't match "Feature Request",cause it isn't about the Gamehub client itself.
A Subreddit would be cool,cause people could ask many questions and ask for helping to setup specific games right etc.

**Comment by neuromancer** [comment]
You can always ask directly to [u/tkashkin](https://www.reddit.com/user/tkashkin).

**Comment by Toadfield** [comment]
Oh,that's cool,but I think a Subreddit would be cooler,cause then all developers and some users could ask questions there,so the developer you mentioned doesn't have to do everything.

**Comment by tkashkin** [comment]
I have enabled GitHub Discussions but haven't tried them yet. I think Discussions may be a good place for this and it should be easier to find than a subreddit.

**Comment by Toadfield** [comment]
I didn't even know that GitHub Discussions exists,I will do a test discussion and see if it works.

**Comment by Toadfield** [comment]
Yeah,[it works](https://github.com/tkashkin/GameHub/discussions/457),the question is,how can I close that discussion and is it visible to everyone and can you comment there?

**Comment by Toadfield** [comment]
Ok,you can comment to it,but can every user do that or only developers?

**Comment by tkashkin** [comment]
> how can I close that discussion

There are action on the right side of a discussion page:

![image](https://user-images.githubusercontent.com/2003017/103384447-87323180-4b07-11eb-81bf-ca6baa2ee452.png)

I'm not sure what can you do with your discussion, but I guess you can delete it there.

> is it visible to everyone and can you comment there, can every user do that or only developers

I guess so, it would be weird if no one could comment there.
