### ISSUE TITLE
[Feature Request] Being able to install more wine versions

### ISSUE THREAD

**Issue by Toadfield** [tkashkin/GameHub#455]
So the standard newest wine versions don't work for many games,so it would be cool to install other versions that many times work would be cool.
So I mean that adding wine versions should work like in Lutris.

**Comment by tkashkin** [comment]
Already implemented in the `refactoring` branch.

**Comment by Toadfield** [comment]
Has nothing to do with that feature here,so I will close it,but is Gamehub-git the refactoring branch?
Cause I can't see any other packages at the aur.
