### ISSUE TITLE
[Feature Request] Extra Categorie for every Compatibility Layer

### ISSUE THREAD

**Issue by Toadfield** [tkashkin/GameHub#480]
I mean [that](https://i.imgur.com/ShOH4C8.png).
It would also be cool if every Retroarch Core has it's own category.

**Comment by tkashkin** [comment]
I don't think that would be usable because there would be way too many buttons there.

I'm thinking about a different approach:
* Index more metadata for games
* Make it searchable (probably something similar to GitHub issue search)
* Remove existing filters and simplify UI

Related: #388

**Comment by Toadfield** [comment]
Yeah,that approach would be cooler.
