### ISSUE TITLE
Some games in GOG include images in their description (and they look very out of place)

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#49]
![game](https://user-images.githubusercontent.com/110782/44632341-61049180-a94f-11e8-9a00-3e74c1c2b18e.png)

**Comment by neuromancer** [comment]
Oh, then this is expected. It's the only game I saw with images in GOG, but one broken layout is fine. Feel free to close this.

**Comment by tkashkin** [comment]
Yes, I haven't seen games with images on GOG too (besides Carmageddon).

Still, something like this
```css
img
{
	display: block;
}
```
should fix this. But it may break some descriptions with inline images (I haven't seen such descriptions yet).

**Comment by tkashkin** [comment]
Fixed for next commit.
