### ISSUE TITLE
I suddenly can't see my steam games anymore

### ISSUE THREAD

**Issue by Toadfield** [tkashkin/GameHub#492]
###### Expected behavior
That I can see my steam games like normally

###### Actual behavior
That I can't see them.
It looks like [this](https://i.imgur.com/LbFoyE7.png)
That suddenly started to happen today

###### Steps to reproduce
Go into Gamehub

###### Version and environment

```
- GameHub
    Version: 0.16.0-3ff389e-master
    Branch:  master
    Commit:  3ff389ea589076815256435971f5a99d593d9448
- Environment
    Distro:  Manjaro Linux
    DE:      KDE
    GTK:     3.24.23
```

**Comment by tkashkin** [comment]
Do you have any filters active?

**Comment by Toadfield** [comment]
Oh,that was the problem lol
