### ISSUE TITLE
Scummvm enhacements

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#52]
A [good amount](https://www.gog.com/mix/games_compatible_with_scummvm) of GOG games are using scummvm. I wonder if we could have some special options to handle them, for instance to replace the bundled scummvm executable with the system one. This feature, combined with #33, will enable the automatic port of some games arbitrarily available for some platforms.

**Comment by neuromancer** [comment]
I recently revisited this issue. I tried to use some SCUMMVM games with the custom emulator feature. It's promising, but it won't work as expected with SCUMMVM since it requires to change the directory to the game directory, for every game. The custom emulator feature does not allow that (or at least, I don't know how to do it without creating a custom script). 

Moreover, maybe could be a good idea to remove the Dosbox/Wine/Proton code and re-add them as custom emulators.

**Comment by tkashkin** [comment]
> it requires to change the directory to the game directory, for every game. The custom emulator feature does not allow that

Yes, it currently uses `install_dir` of `Emulator` as a working directory.

Possible solutions:
* Use `install_dir` of `Game`
* Provide option to choose which directory to use (game or emu)

First solution can possibly break emulators if they require to be launched from their directory.
Second solution may be a bit harder (or may not). What should be default for that option if second will be implemented?

**Comment by neuromancer** [comment]
> Provide option to choose which directory to use (game or emu)

I think that's the best option. The default could be the `install_dir` of `Emulator`. I believe this is the most common configuration for `Emulators`.

> No. CompatTools and Emulators are different things and work differently.
> Also Emulators can depend on CompatTools itself.

Fair enough. So, do you think that SCUMMVM should be a `CompatTool` or an `Emulator`?

**Comment by tkashkin** [comment]
> So, do you think that SCUMMVM should be a CompatTool or an Emulator?

I don't know. ScummVM uses `*.ini` for configs, it's a bit harder to detect than `dosbox_*.conf` for DOSBox. Also I don't think that ScummVM is as popular as DOSBox.
User can add it as a custom emulator if needed.

**Comment by neuromancer** [comment]
Works great!. My last suggestion is to include the `scummvm` custom emulator if GameHub detects `scummvm` in the PATH. If you don't want to implement this feature, just close this issue.

**Comment by tkashkin** [comment]
How does `scummvm --auto-detect` work? Does it just launch game if detected? Is there a way to use that autodetection but without launching game?

**Comment by neuromancer** [comment]
> Does it just launch game if detected?

Yes.

> Is there a way to use that autodetection but without launching game?

Use `--detect` to show games in the current directory. Some examples:

```
$ scummvm --detect
ID             Description                                                Full Path
-------------- ---------------------------------------------------------- ---------------------------------------------------------
zak            Zak McKracken and the Alien Mindbenders (FM-TOWNS/English) /home/g/Games/GOG/Zak_McKracken_and_the_Alien_Mindbenders
$ scummvm --detect
ID             Description                                                Full Path
-------------- ---------------------------------------------------------- ---------------------------------------------------------
kyra2          The Legend of Kyrandia: The Hand of Fate (CD/DOS/English)  /home/g/Games/GOG/The_Legend_of_Kyrandia_Hand_of_Fate_Book_Two
kyra2          The Legend of Kyrandia: The Hand of Fate (CD/DOS/German)   /home/g/Games/GOG/The_Legend_of_Kyrandia_Hand_of_Fate_Book_Two
kyra2          The Legend of Kyrandia: The Hand of Fate (CD/DOS/French)   /home/g/Games/GOG/The_Legend_of_Kyrandia_Hand_of_Fate_Book_Two
$ scummvm --detect
WARNING: ScummVM could not find any game in /tmp
WARNING: Consider using --path=<path> *before* --add or --detect to specify a directory
WARNING: Consider using --recursive *before* --add or --detect to search inside subdirectories
```
