### ISSUE TITLE
Question: Why GameHub connects to three connections?

### ISSUE THREAD

**Issue by kajlando** [tkashkin/GameHub#544]
After opening GameHub I see three connections via "sudo netstat -anp | grep ESTABLISHED" called "com.github.t".
These IP addreses belong to Dropbox.
What's their purpose?!

**Comment by tkashkin** [comment]
https://github.com/tkashkin/GameHub/blob/3e2cb8a1e3b91e10fb244e7c6983ba49d934eb8f/src/data/compat/WineWrap.vala#L28

[WineWrap](https://gog.com/forum/general/adamhms_linux_wine_wrappers_news_faq_discussion/post1) wrappers list and wrappers are currently hosted on Dropbox. GameHub tries to load wrappers list on startup.

Maybe I'll make this optional in the future if it bothers more people.
You can block it for now if you don't plan to use WineWrap, nothing else should break if you block it.
