### ISSUE TITLE
AUR pkgbuild fail to package: com.github.tkashkin.gamehub.changelog.xml does not exist

### ISSUE THREAD

**Issue by FabioLolix** [tkashkin/GameHub#578]
###### Expected behavior

AUR pkgbuild builds

###### Actual behavior

AUR pkgbuild fail to build

###### Steps to reproduce

On Arch or Arch-based linux distro
```
sudo pacman -Syu --needed git base-devel
git clone https://aur.archlinux.org/gamehub-git.git
cd gamehub
makepkg -s
```

###### Version and environment
Latest dev branch commit

`data/meson.build:47:23: ERROR: File com.github.tkashkin.gamehub.changelog.xml does not exist.`

```
==> Starting build()...
The Meson build system
Version: 0.59.2
Source dir: /home/fabio/Dev/Github/PKGBUILD/gamehub-git/src/GameHub
Build dir: /home/fabio/Dev/Github/PKGBUILD/gamehub-git/src/GameHub/build
Build type: native build
Project name: com.github.tkashkin.gamehub
Project version: 0.16.1
C compiler for the host machine: cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
Vala compiler for the host machine: valac (valac 0.54.2)
Host machine cpu family: x86_64
Host machine cpu: x86_64
meson.build:6: WARNING: Consider using the built-in optimization level instead of using "-O0".
Configuring com.github.tkashkin.gamehub.gschema.xml using configuration

data/meson.build:47:23: ERROR: File com.github.tkashkin.gamehub.changelog.xml does not exist.

A full log can be found at /home/fabio/Dev/Github/PKGBUILD/gamehub-git/src/GameHub/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in build().
    Aborting...

```

com.github.tkashkin.gamehub.changelog.xml exist in the master branch

while in the [dev branch](https://github.com/tkashkin/GameHub/tree/dev/data) there is com.github.tkashkin.gamehub.changelog.xml.REMOVED.git-id with contenent "d20dfaa0823affae365c9d9b2067453ca4b9b5ec"

**Comment by tkashkin** [comment]
It should be fixed now.

I forgot to check other branches after running [bfg](https://rtyley.github.io/bfg-repo-cleaner) on the repo and deleting the changelog by doing that.
