### ISSUE TITLE
Humble Bundle library doesn't appear in GameHub

### ISSUE THREAD

**Issue by afettouhi** [tkashkin/GameHub#58]
I just installed GameHub on Arch Linux 64-bit with KDE Plasma from AUR (version 0.6.2 as of this writing). I set up both Steam and GOG and my library got populated but after setting up Humble Bundle nothing got added to that library. I have several games that are not only games that are Steam keys but games from the previous Humble Indie Bundles. Am I missing something or am I misunderstanding?

**Comment by tkashkin** [comment]
Have you installed [this package](https://aur.archlinux.org/packages/gamehub)? It's quite outdated. There's a [newer package](https://aur.archlinux.org/packages/gamehub-git) in AUR which should build latest version.

**Comment by afettouhi** [comment]
Yes I installed the package from the first link.

**Comment by afettouhi** [comment]
I just installed the other version from AUR. So I should have the latest version from git and my Humble Bundle library is still empty.

**Comment by tkashkin** [comment]
There was a bug (#9) which was fixed after 0.6.2.
You need to reset humble access token with `dconf reset -f /com/github/tkashkin/gamehub/auth/humble/`

**Comment by afettouhi** [comment]
Ahh... now it populates. Many many thanks :D.
