### ISSUE TITLE
Non-native games: Wine

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#59]
Not everyone want or can use SteamPlay/Proton. It will be nice to offer an alternative if wine is installed. I tested this feature using this code in Game.vala:

```vala
case InstallerType.WINDOWS_EXECUTABLE:
      cmd = {"env", "WINEPREFIX=" + game.install_dir.get_path() + "/.wine" , "wine", path}; // use wine
```

It will create a wine prefix to use and call the installer. Later, the user should properly select file to execute in the corresponding wine prefix.

**Comment by tkashkin** [comment]
Test 7752ad9.

**Comment by neuromancer** [comment]
This feature seems to be working, however, there are a few related issues:

* Once a game is installed using wine or wine64, the user should use the corresponding version to run the game. For instance, AFAIK, it does not make any sense to create a 32-bits wine prefix and them use wine64.
* Some games expect that you run the executable with wine from its directory (e.g. Hitman Codename 47 fails to find its data files).
* Some games require to modify a little the wine settings (this is the same for proton). Two small buttons to call `winecfg` and `winetricks` in the wine prefix should be enough for the 95% of the games that require tweaking..

**Comment by tkashkin** [comment]
I don't know of it's possible to detect if some random .exe is in fact innosetup installer.
But most installers should have some common (maybe slightly different) parameters.
It should be possible to pass many parameters to cover most of installers (assuming they won't break if unknown parameter is passed).

It may help with another issue if target directory can be passed.
Now it installs everything somewhere in `drive_c` inside wine/proton prefix

Is there a list of common installer parameters available somewhere?

**Comment by neuromancer** [comment]
I think we can assume that GOG uses innosetup, since the extraction works as expected. I don't know about HumbleBundle, maybe some could be [NSIS installers](http://nsis.sourceforge.net/Main_Page). Even some Window games are distributed using zip files. :disappointed:

**Comment by tkashkin** [comment]
Now there are buttons for `winecfg`, `winetricks` and `regedit`.
Last used compat tool is now saved for each game.

Also game tags dialog is now game preferences dialog with more options:

![image](https://user-images.githubusercontent.com/2003017/45343102-909ad700-b5a8-11e8-8f9b-b25c09e1db9c.png)

**Comment by neuromancer** [comment]
The game configuration dialog works fine!. Minor suggestion: when selecting the executable, it should start in `_gamehub/wine64/drive_c/` instead of using just `_gamehub`. 

Also, it should be easy to kill all the wine processes, in case something goes wrong (in fact, it can be automatically called every time a new game is launched). [This command](https://askubuntu.com/a/928094) works fine in Arch.

**Comment by tkashkin** [comment]
@neuromancer Does file/folder chooser actually start with correct default folder for you?
Doesn't work for me on elementary for some reason, it just ignores current_folder property and opens last opened directory.

**Comment by neuromancer** [comment]
A large number of games are failing because of the incorrect working directory (executable directory). I checked the code in [Wine.vala](https://github.com/tkashkin/GameHub/blob/dev/src/data/compat/Wine.vala#L67-L76) and the working directory is set. However, I think the issue here is that wine expect paths to be in the windows format (e.g `C:\`). Some programs like PlayOnLinux use [winepath](https://github.com/PlayOnLinux/POL-POM-4/blob/df9e090b4db5b7a41f72145877cc541b908c319b/python/lib/playonlinux.py#L9-L22) to convert from Unix to Windows paths.

**Comment by tkashkin** [comment]
Game directory is now (since b62ec93) passed to Windows installers (for now assuming all of them are InnoSetup) and games should not be installed somewhere inside prefix.
Check if that helps with working directories. You'll need to remove and reinstall Windows games to test it.

**Comment by neuromancer** [comment]
In revision b62ec93, most of the installers are failing to run, for instance Delta Force or Hitman (they don't install anything in the ` _gamehub/wine` prefix or in the game directory). Some others install the game in the game directory. I don't know if that's expected, but maybe it can produce a failure with some games that require to be run from an actual wineprefix (for instance, if they install some files in other directories?). Some others are not running correctly: Deus Ex still ask for it's CD (that's cause by starting the game from an incorrect working directory)

Also, another useful feature to implement: [disable the wine-gecko popup](https://superuser.com/questions/948508/how-to-disable-gecko-package-popup-for-wine).

**Comment by tkashkin** [comment]
Some installers just do nothing if `/SILENT` or `/VERYSILENT` args are passed. I don't know what's the problem here. Maybe it's related to license.

**Comment by neuromancer** [comment]
Confirmed! Deus Ex ask for to agree with its EULA.

**Comment by tkashkin** [comment]
Now (3cd2745) there's install options list for wine/proton. If silent install fails you can uncheck silent options. Install log is now saved in `c_drive` root of prefix.

**Comment by neuromancer** [comment]
Oh, I was going to post my diff to solve some of this issues (in particular, all the games are installed inside  the C drive, to avoid bizarre errors. I'm using a fixed directory: `C:\Game`. With this patch Hitman and Deus Ex are working as expected. 

```
diff --git a/src/data/compat/Wine.vala b/src/data/compat/Wine.vala
index 491f169..aa910bb 100644
--- a/src/data/compat/Wine.vala
+++ b/src/data/compat/Wine.vala
@@ -65,8 +65,8 @@ namespace GameHub.Data.Compat
 
                protected virtual async string[] prepare_installer_args(Game game)
                {
-                       var win_path = yield convert_path(game, game.install_dir);
-                       return { @"/DIR=$(win_path)", "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NOICONS", "/NOCANCEL", "/NORESTART", "/CLOSEAPPLICATIONS", "/FORCECLOSEAPPLICATIONS" };
+                       var win_path = yield convert_path(game, game.install_dir, "/_gamehub/wine/drive_c/Game");
+                       return { @"/DIR=$(win_path)", "/SUPPRESSMSGBOXES", "/NOICONS", "/NOCANCEL", "/NORESTART", "/CLOSEAPPLICATIONS", "/FORCECLOSEAPPLICATIONS" };
                }
 
                public override async void install(Game game, File installer)
@@ -84,6 +84,7 @@ namespace GameHub.Data.Compat
                public override async void run(Game game)
                {
                        if(!can_run(game)) return;
+                       debug("game.install_dir -> '%s'", game.install_dir.get_path());
                        yield exec(game, game.executable, game.install_dir);
                }
 
@@ -94,7 +95,7 @@ namespace GameHub.Data.Compat
                        {
                                foreach(var arg in args) cmd += arg;
                        }
-                       yield Utils.run_thread(cmd, dir.get_path(), prepare_env(game));
+                       yield Utils.run_thread(cmd, dir.get_path()+"/_gamehub/wine/drive_c/Game", prepare_env(game));
                }
 
                protected virtual File get_wineprefix(Game game)
@@ -115,6 +116,8 @@ namespace GameHub.Data.Compat
                        if(prefix != null && prefix.query_exists())
                        {
                                env = Environ.set_variable(env, "WINEPREFIX", prefix.get_path());
+                                env = Environ.set_variable(env, "WINEDLLOVERRIDES", "mscoree,mshtml=");
+
                        }
 
                        return env;
@@ -144,7 +147,7 @@ namespace GameHub.Data.Compat
                        yield Utils.run_thread({ "winetricks" }, game.install_dir.get_path(), env);
                }
 
-               public async string convert_path(Game game, File path)
+               public async string convert_path(Game game, File path, string s)
                {
                        var env = Environ.get();
                        env = Environ.set_variable(env, "WINE", wine_binary.get_path());
@@ -153,7 +156,7 @@ namespace GameHub.Data.Compat
                        {
                                env = Environ.set_variable(env, "WINEPREFIX", prefix.get_path());
                        }
-                       var win_path = (yield Utils.run_thread({ wine_binary.get_path(), "winepath", "-w", path.get_path() }, game.install_dir.get_path(), env)).strip();
+                       var win_path = (yield Utils.run_thread({ wine_binary.get_path(), "winepath", "-w", path.get_path() + s }, game.install_dir.get_path(), env)).strip();
                        debug("'%s' -> '%s'", path.get_path(), win_path);
                        return win_path;
                }


```

I will test 3cd2745 now..

**Comment by tkashkin** [comment]
I don't really want to install games inside prefix, because it will result in multiple copies of game if user wants to test it with both wine and proton (and multiple versions of it).
It probably can cause some problems if game install something somewhere except its directory and then run in another prefix, in which installer was not executed.
It probably can be implemented as another option.

**Comment by neuromancer** [comment]
The wine-gecko popup is gone and this feature works fine, so I can close this issue. 

In case you change your mind about the game installation in the (wine/proton) prefix, I have fork of GameHub with [some modifications](https://github.com/neuromancer/GameHub/commit/4f0489d2a754b01f30b4a2e5fe258c7e191bc5a4) to install games inside it. Some games are failing if you install them in directories like `Z:\..` outside the prefix directory.
