### ISSUE TITLE
Non-native games: select extract or install

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#60]
Non-native games should have two options: `extract` to extract using innoextract and `install` to install using SteamPlay/Proton or Wine. It is useful to have both options since some games should be run using native versions of SCUMMVM/Dosbox while others should be installed and played usine SteamPlay/Proton or Wine.

**Comment by HadetTheUndying** [comment]
Agreed pretty much none of my Gog Games are launching right now because they're not being installed just extracted.

**Comment by tkashkin** [comment]
Test 7752ad9.

**Comment by neuromancer** [comment]
This works as expected!
