### ISSUE TITLE
Flatpak version wont launch (0.9.0)

### ISSUE THREAD

**Issue by Saroufim** [tkashkin/GameHub#61]
Running it from the command line yields the following

```
bwrap: Can't mkdir parents for /app/lib/32bit/lib/GL: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by tkashkin** [comment]
I don't know much about flatpak (especially about video drivers).
You need to have correct video driver on your system and corresponding userspace libraries on flatpak side.
Libraries must have the same version as driver.

Usually libraries are distributed in packages like these (from flathub):
* org.freedesktop.Platform.Compat32
* org.freedesktop.Platform.GL
* org.freedesktop.Platform.GL32

You need to install libs for your specific driver and its version.

Try to get to run `com.valvesoftware.Steam` package from flathub first if you haven't already.

Then if you have Steam flatpak running, you probably have driver dependencies setup (unless something have changed recently).
