### ISSUE TITLE
Cannot discover how to install on the Valve Steam Deck

### ISSUE THREAD

**Issue by fire** [tkashkin/GameHub#620]
###### Expected behavior

A discover-able list of instructions to help a new gamer to install GameHub on the Valve Steam Deck.

###### Actual behavior

Lost.

> \<@akien> I tried and failed with GameHub, they have a flatpak but not on FlatHub and it seems somewhat broken. The AppImage doesn't run as it's Ubuntu-specific. 

###### Steps to reproduce

1. Turn on the steam deck
2. Lost.

###### Version and environment

1. n/a
2. Steam Deck
3. Arch Linux

**Comment by AeliusSaionji** [comment]
If you open the flatpak file in `discover`, it will give you a GUI option to install.

**Comment by fire** [comment]
Instructions to turn on the Steam Deck Arch desktop mode is not trivial. Probably a good thing to document or find a workaround.

**Comment by fire** [comment]
Exactly. I'm not the target audience for this instruction. So I opened the ticket.

Seems like there's not that much interest. So I will close.
