### ISSUE TITLE
enable jammy in ppa

### ISSUE THREAD

**Issue by noah1510** [tkashkin/GameHub#633]
At the moment the packages in the ppa are not built for ubuntu 22.04 (jammy) which is the latest lts release.
Can the jammy builds be enabled or are any changes needed to make it work?

**Comment by kankaristo** [comment]
Same here, can't use the PPA on Ubuntu 22.04.

I tried running the (unstable) AppImage, but that's failing to start with this issue: https://github.com/tkashkin/GameHub/issues/580

The (also unstable) Flatpak version at least starts, but the "Install Steam" button does nothing, and the GOG login doesn't work (and also looks very weird, like it's not loading CSS or something).

Guess I'll try GameHub again in a few months...

**Comment by tkashkin** [comment]
New packages are uploaded and [should be published soon](https://launchpad.net/~tkashkin/+archive/ubuntu/gamehub/+packages) for `kinetic`, `jammy`, `impish` and `focal`.

**Comment by noah1510** [comment]
seems to work fine :+1:
