### ISSUE TITLE
New 0.16.3-1-master fails to compile on Fedora 36

### ISSUE THREAD

**Issue by tim77** [tkashkin/GameHub#637]
###### Expected behavior

Build success the same as for older Fedoras, like Fedora 35.

###### Actual behavior

Full [build log](https://github.com/tkashkin/GameHub/files/8766538/build.log)

###### Version and environment

- GCC: `gcc-12.1.1-1`
- Vala: `0.56.1-1`

```
0.16.3-1-master
```

**Comment by tkashkin** [comment]
Should be fixed by 9327885.

**Comment by tim77** [comment]
Thanks for quick fix! It compiles fine with new Vala now.
