### ISSUE TITLE
Check if the database is created using an older version

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#64]
GameHub is tested and updated frequently changing its database schemes from time to time. This already caused some additional issues (crashes, etc) that can be frustrating for users. However, this can be solved including the git revision when the database is created and warning the user if there is an existing one created using an older version. GameHub can also ask to delete and re-create the database if the previous executing failed to run or took too long.

**Comment by tkashkin** [comment]
@HadetTheUndying

Database path is `~/.cache/com.github.tkashkin.gamehub/games.db`.
But before removing it please run `com.github.tkashkin.gamehub --debug` in terminal to see log and post it here.

**Comment by tkashkin** [comment]
Should be fixed by 6c48e09.
