### ISSUE TITLE
Missing Compatibility menu

### ISSUE THREAD

**Issue by UltraBlackLinux** [tkashkin/GameHub#645]
###### Expected behavior
There should be a compatibility menu somewhere.

###### Actual behavior
There doesn't appear to be. Is it even supposed to exist? #644 mentions it, so I would think it does. 
Not even `gamehub -c` seems to do anything at all

###### Steps to reproduce
1. Right click on a game (Steam games for me)
2. There is no compatibility menu option, just "Run with compatibility layer"
3. Open game Properties
4. There is also no way to configure proton or any other compatibility layer there

###### Version and environment

```
- GameHub
    Version: 0.16.3-9952b8f-makepkg
    Branch:  makepkg
    Commit:  9952b8f2633e18ca32bec3762ecfe8589bee7593
- Environment
    Distro:  Garuda Linux
    DE:      wayfire
    GTK:     3.24.34
```

**Comment by UltraBlackLinux** [comment]
For the record, not even the compatibility section as seen here exists: 
![](https://tkashkin.github.io/projects/gamehub/res/screenshots/light/properties.png)
It might be worth mentioning that I only have steam games in my library

**Comment by tkashkin** [comment]
Steam games are launched through Steam and GameHub compatibility options are not available for them.

It may be possible to implement some of GameHub features for Steam games but currently they are not implemented.
