### ISSUE TITLE
GameHub doesn't detect installed games

### ISSUE THREAD

**Issue by MaoDzeDun** [tkashkin/GameHub#66]
Hi,
I'm experiencing this weird problem where the client will download a game from GOG, install it, but then shows said game as not installed, even though it appears in the game menu of Linux Mint and is working. Tested it with Shadow Tactics and Tyranny - same things for either game.

**Comment by tkashkin** [comment]
What version are you using? master or dev branch? Does this issue appear with other branch?

Are these games native Linux games?

**Comment by MaoDzeDun** [comment]
Yes, native games. I'm using the master branch. So, upon further inspection - I've set the games directory in the settings as GOG - Linux, which is on my Linux game drive. However, when I try to install a game, an empty folder with the game name is created inside, while the game is actually installed in a folder called GOG that is at the same level as GOG - Linux. And if you try to install a second game, it starts to mess game files inside the said GOG folder. I can provide some screenshots, if you like.

**Comment by tkashkin** [comment]
Yes, screenshots will be helpful.

But I have an idea about what's wrong:
GOG installers are `mojosetup` packed in `makeself`. There's parameter escaping problem in either `makeself` or `mojosetup`.
Target directory is passed in `--destination` parameter, but there's no way to escape spaces.

It should work correctly if you remove spaces from paths.

**Comment by MaoDzeDun** [comment]
Yup - you were 100% spot on. Changed the name to one with no spaces and now it works. Had to restart the OS though (logout might also work). Seems soms cache is kept somewhere because simply renaming and restarting the client, with setting the new folder resulting in another folder with the old name appearing. Anyway, thank you for the tip and for the had work. I find it trully shameful there is no native GOG client. You offer the next best thing.
