### ISSUE TITLE
Escaped names allow colon (:)

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#70]
Some Windows installer will refuse to install to a directory with a colon in it's name (e.g. "Blood 2: The Blood Group"). Remove it from `escaped_name` to avoid this issue:

https://github.com/tkashkin/GameHub/blob/04e279992e64300d02ec794bdbbb9d69f895cccc/src/data/Game.vala#L222-L228

**Comment by tkashkin** [comment]
`Utils.strip_name` should strip chars, including `:`.
However I've found a bug. `continue` should be here instead of `break`:

https://github.com/tkashkin/GameHub/blob/master/src/utils/Utils.vala#L222

Fixed for next commit.
