### ISSUE TITLE
Allow to specify a startup script for non-native games

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#71]
Some games can be run using dosbox or scummvm (#51, #52). However, once a Window game is installed or extracted, there is no way to run it without using Wine/Proton. Allowing the user to specify a startup script is an easy way to solve this issue.

**Comment by tkashkin** [comment]
Doesn't `select executable` button in game properties dialog allow to select shell script?
Or is it trying to run it with wine/proton regardless of it being a shell script?

**Comment by neuromancer** [comment]
Yes. You can select a shell script, but it will try to execute it with Proton/Wine:

```
[DEBUG 15:05:05.697012] Utils.vala:59: [Utils.run] Running {'/usr/bin/wine' '/home/g/Games/GOG/Magic_Carpet_Plus™/start.sh'} in '/home/g/Games/GOG/Magic_Carpet_Plus™'
```

**Comment by tkashkin** [comment]
I think predefined script is better.
It will use `_gamehub/customscript.sh` and create it if it doesn't exist.
There's edit button which opens default editor.

It passes some variables to the script, template uses them:

```bash
#!/bin/bash
GH_EXECUTABLE="$1"
GH_INSTALL_DIR="$2"
GH_GAME_ID="$3"
GH_GAME_ID_FULL="$4"
GH_GAME_NAME="$5"
GH_GAME_NAME_ESCAPED="$6"
```

**Comment by neuromancer** [comment]
I agree that a predefined script is better if GameHub allows to edit it easily. Latest revision works great! Feel free to close this issue if there is no more commits to add.
