### ISSUE TITLE
GameHub on Solus

### ISSUE THREAD

**Issue by JonnyCodewalker** [tkashkin/GameHub#74]
OS: Solus 3.9999
Version: 0.9.0 (flatpak)

GameHub is not able to find steam. If you need anything for debugging just let me know.

**Comment by tkashkin** [comment]
Check if these paths are correct and exist:

https://github.com/tkashkin/GameHub/blob/master/src/utils/FSUtils.vala#L45-L62

**Comment by tkashkin** [comment]
I have assumed you have Steam flatpak if you use GameHub flatpak.

Regular (not flatpak) GameHub lets user to select Steam folder and uses `~/.steam` by default.

You should build it yourself or try to use Steam flatpak.

**Comment by JonnyCodewalker** [comment]
Interesting. I will see how building it goes tomorrow. Out of curiosity, what is the reasoning behind that altered behaviour for the flatpak version?

**Comment by tkashkin** [comment]
I just wasn't sure how to access files outside of flatpak sandbox when I was implementing flatpak support (and I'm still not sure).

I don't really suggest anyone to use flatpak version of GameHub (and Steam too). I agree with the arguments provided [here](https://github.com/flathub/flathub/pull/486).

**Comment by tkashkin** [comment]
@JonnyCodewalker I have implemented AppImage version and it even seems to work.
You can try it before building from source.

**Comment by JonnyCodewalker** [comment]
After installing keyutils the appimage worked flawlessly. Will try building from source now to see if any issues arise there.

**Comment by tkashkin** [comment]
@JonnyCodewalker
I guess I need to put `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/` inside of AppImage and patch `$APPDIR/usr/lib/libwebkit2gtk-4.0.so.37` (`/usr` -> `././`) to allow it to execute `WebKitWebProcess` from AppImage.

@probonopd Is there maybe some switch for `linuxdeployqt` so it would do this patching automatically?

**Comment by tkashkin** [comment]
@JonnyCodewalker Was it also requiring `keyutils`? What was the error? I'll need to test it on clean VMs.

**Comment by JonnyCodewalker** [comment]
~  opt  $  sol history
Password:          
 ~  opt  $  sol history -t 516
Following packages will be removed:
keyutils 
The following list of packages will be removed
in the respective order to satisfy dependencies:
keyutils 
Removing package keyutils
Removed keyutils
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
 [✓] Updating manpages database                                         success
 ~  opt  $  ./GameHub 
/tmp/.mount_GameHuIRxe0w/usr/bin/com.github.tkashkin.gamehub: error while loading shared libraries: libkeyutils.so.1: cannot open shared object file: No such file or directory
 ~  opt  $ 

**Comment by tkashkin** [comment]
It's in the [exclude list](https://github.com/AppImage/AppImages/blob/master/excludelist#L130) so it's expected to be present in the system.

**Comment by JonnyCodewalker** [comment]
I mean that is not a big issue, I would just note in the readme that for using the appimage on Solus one has to do `sudo eopkg it -y keyutils` to make sure that they are installed.

**Comment by tkashkin** [comment]
Try [this AppImage](https://github.com/tkashkin/GameHub/releases/download/0.11.1-1-master/GameHub-xenial-local-test-d50095c-x86_64.AppImage).

It should bundle patched `libwebkit2gtk` and its executables like `WebKitWebProcess` is so it should not try to execute `WebKitWebProcess` from system.

Also this AppImage can be interesting as it bundles GTK 3.18, but uses system libs if they are >= 3.22.

It's built on Ubuntu 16.04, seems to work in a clean 16.04 VM and on 18.04 (elementary OS). It uses system GTK on 18.04 so themes don't break.

It doesn't build in AppVeyor on 16.04 yet, but does on my 16.04 VM, the reason is that I may have upgraded `valac` on xenial build VM manually.

**Comment by probonopd** [comment]
> I guess I need to put `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/` inside of AppImage and patch `$APPDIR/usr/lib/libwebkit2gtk-4.0.so.37` (`/usr` -> `././`) to allow it to execute `WebKitWebProcess` from AppImage.

This only works if AppRun does `cd` to the corresponding directory.

**Comment by JonnyCodewalker** [comment]
@tkashkin the appimage works without /usr/lib/x86.... being present.
