### ISSUE TITLE
Support to add custom games

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#83]
It will be a really nice feature to let users to add custom games from their hard drive. It will require a different group (I'm not sure which name it should have..)

**Comment by tkashkin** [comment]
I'm thinking about this.

Do you think it should be implemented as a single source (e.g. "User games"?) or as multiple customizable sources (e.g. one source for open-source games from repos, another source for emulator1, another for emu2 etc.)?

**Comment by tkashkin** [comment]
Implemented in 0fad67c.

![user_games](https://user-images.githubusercontent.com/2003017/45947914-a1af0380-bffe-11e8-8f63-fb5c2fb0d8b1.png)

**Comment by neuromancer** [comment]
Great!. I saw some changes in the database in that commit. Should I reset it?

**Comment by tkashkin** [comment]
No, it should migrate properly.

**Comment by neuromancer** [comment]
It works!. A few suggestions:

* While you add game, it should be easier to select the directory picking the executable only (the directory is where the executable is). This should reduce one step.
* It should be possible to remove a custom game, without uninstalling it.

**Comment by neuromancer** [comment]
Well, the uninstall button is doing nothing. Also, it is impossible to rename a game (for instance, to correct a typo). Additionally, if you have installed versions of physical copies of GOG/Humble/Steam games (but not necessarily on your library), it could be nice to able to add them easily (fetching name, images and icon).

**Comment by tkashkin** [comment]
Implemented in fc62026:
> While you add game, it should be easier to select the directory picking the executable only (the directory is where the executable is). This should reduce one step.

> It should be possible to remove a custom game, without uninstalling it. Well, the uninstall button is doing nothing

Won't be implemented now (maybe later with some online game info database integration):
> Additionally, if you have installed versions of physical copies of GOG/Humble/Steam games (but not necessarily on your library), it could be nice to able to add them easily (fetching name, images and icon).

**Comment by neuromancer** [comment]
I tested this features and it seems to work as expected!

> Also, are there now any retail games which do not require Steam activation? (I assume most of GOG retail games are activated too).

I don't know. I was referring mostly to old games.
