### ISSUE TITLE
Wine gecko popup when creating a new wine prefix

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#86]
The gecko installation popup is still in issue when creating a new wine prefix. Fortunately, there is a patch [here](https://github.com/neuromancer/GameHub/commit/6d57885063322550b8656d497fc870e8131972c5). I think you will probably want to refactor a little that code before merging it. Otherwise let me know and I can create a proper PR.

**Comment by tkashkin** [comment]
It probably won't break anything, so you can create a PR.

**Comment by neuromancer** [comment]
This should be fixed now.
