### ISSUE TITLE
HumbleBundle

### ISSUE THREAD

**Issue by cassidyjames** [tkashkin/GameHub#9]
HumbleBundle.com has a concept of a library. I'm not sure what their API is like, but it'd be handy to be able to see and download my games there.

Installing might be tricky, as they're typically delivered as a zip or tarball, which is a lot less friendly for users.

**Comment by tkashkin** [comment]
Humble Bundle support is already implemented in 89968b4 and should work for archives and binaries (assuming they are MojoSetup).

Unfortunately I can't test many games as I have only 6 of them in Humble library.

**Comment by cassidyjames** [comment]
Oh, awesome! I have a large library of HumbleBundle games, so I can give it a test.

**Comment by cassidyjames** [comment]
@tkashkin it appears linking a HumbleBundle account opens the log in window with the website, then just shows me the library on the website instead of in GameHub. If I close the website, GameHub still doesn't  seem to know about my HumbleBundle account.

**Comment by tkashkin** [comment]
@cassidyjames have you received email with security code? If so did it show code prompt?

**Comment by cassidyjames** [comment]
@tkashkin I did, and it logged in successfully. But then it just logged in in the web browser. The GameHub UI never updated and showed it as logged in.

**Comment by tkashkin** [comment]
@cassidyjames ok, so it isn't working when security code is requested. I'll look into this tomorrow.

**Comment by tkashkin** [comment]
@cassidyjames it should be fixed by 2ba374a; [release](https://github.com/tkashkin/GameHub/releases/tag/0.3.1).

You may need to run `dconf reset -f /com/github/tkashkin/gamehub/auth/humble/
` for it to work properly.

**Comment by mgclabs** [comment]
[gamehub.log](https://github.com/tkashkin/GameHub/files/2153064/gamehub.log)
Does this help?

**Comment by tkashkin** [comment]
@mgclabs did it login in browser successfully? If so, my assumption that humble token can't be enclosed in `"` was wrong.

**Comment by mgclabs** [comment]
It did log in successfully in the browser, yes

**Comment by tkashkin** [comment]
@mgclabs try new [release](https://github.com/tkashkin/GameHub/releases/tag/0.3.1).

**Comment by mgclabs** [comment]
Just tried it, it shows the authorization as successful but isnt populating with games

**Comment by tkashkin** [comment]
@mgclabs I don't really know what's the problem in your case.

You can try to login in external browser and get `_simpleauth_sess` cookie value. In my testing it should never be enclosed in `"` (when it is user isn't fully logged in).

If you are logged in correctly (with 2FA), you should be able to get your order ids at https://www.humblebundle.com/api/v1/user/order?ajax=true

Then execute `dconf write /com/github/tkashkin/gamehub/auth/humble/access-token \'<token>\'` where `<token>` is cookie value.

**Comment by tkashkin** [comment]
@cassidyjames Just to be sure, have you waited long enough? Orders are loading sequentially and take some time to parse. There's no filtering so not all orders contain Linux-compatible games.

There may be some useful info in the log, run `com.github.tkashkin.gamehub --debug` in terminal.

You can also try to set access token from browser cookies, I'll add option in settings if that will work.

**Comment by MessedUpHare** [comment]
I've found on my system - using the UI GameHub supplies results in the auth token being saved into dconf as: '"$auth_token"' (note the extra inverted commas ("))
If I change this manually in dconf value to '$auth_token' - this issue is resolved.

**Comment by tkashkin** [comment]
@MessedUpHare
`_simpleauth_sess` cookie exists on humble site even if user is not authenticated. In this case token contains quotes. But after signing in new token should not contain quotes (that's for me, but it's not the case for others for some reason).

So do you think removing quotes helps?

**Comment by MessedUpHare** [comment]
@tkashkin 
for me, removing the double quotes from the humble/access-token dconf key worked.
GameHub now lists games from Humble, where it previously listed 0 (running it in debug, it reported an issue about null strings a JSON class was trying to parse before).
I do still get a segfault after *some* time - but it starts listing games from humble after this change.
(I'll do some investigation into the crash I get when I get some more spare time)

**Comment by MessedUpHare** [comment]
@tkashkin 
Building from tag 0.6.3 has resolved the authentication issue for me.
Others who have experienced this problem will need to be advised to reset their authentication credentials.

**Comment by cassidyjames** [comment]
This worked great for me on a fresh install. Nice work!
