### ISSUE TITLE
Single click launch mode for games using compatibility tools

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#92]
Once a game was installed with some compatibility mode and (and maybe configured to run properly), it could be nice to offer a **single click** launch mode to run it. Also, once the game started, it could be a good idea to disable the launch of other games because the compatibility tools can take a little longer to start (e.g. wine) and some impatient users could click several times :disappointed:

**Comment by Hedronmx** [comment]
Please do stop the launching of games after a game is already launched. I accidentally run my games multiple times...

**Comment by tkashkin** [comment]
Multiple games launch at the same time is now blocked.

**Comment by neuromancer** [comment]
This is working in `dev`.

**Comment by neuromancer** [comment]
For some reason, the single click launch mode is not working for non-native user games.

**Comment by tkashkin** [comment]
@neuromancer seems to work for me. Any info about game and used compat tool? Anything weird in log?

**Comment by neuromancer** [comment]
To reproduce with latest revision (4150ba2):

1. Download [UPlayInstaller.exe](https://uplay.ubi.com/).
2. Add it as a custom game and install it (latest wine works fine). Ignore the login screen, just close it.
3. Modify the custom game to use UPlay.exe as executable.

After that, clicking on the UPlay game will always bring the compatibility layer popup.

**Comment by tkashkin** [comment]
@neuromancer can't reproduce. May it be related to compiler optimizations too?

**Comment by neuromancer** [comment]
I tried without optimizations but it is still an issue. However, it is not a very important one, so feel free to close it. Other users will re-open it if they have the same issue.

**Comment by tkashkin** [comment]
@neuromancer check `compat_tool_settings` column in database.
It should contain `compat_options_saved` after game is launched at least once. Example:

```json
{
    "proton_961940": {
        "options": {
            "PROTON_NO_ESYNC": false,
            "PROTON_NO_D3D11": false,
            "PROTON_USE_WINED3D11": false,
            "DXVK_HUD": true
        }
    },
    "compat_options_saved": true
}
```

**Comment by neuromancer** [comment]
The `compat_options_saved` row is null for all the games I manually added and the `last_launch` column is 0 (despite I launched them many times).

**Comment by tkashkin** [comment]
@neuromancer try 75a5015. It should be fixed.

**Comment by neuromancer** [comment]
It's fixed. As efficient as always, thanks a lot!
