### ISSUE TITLE
SIGABRT after loading games while offline

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#94]
The last `dev` revision of GameHub crashes when it finishes to load the games while the system is offline. Here is the relevant part of the [log](https://github.com/tkashkin/GameHub/files/2443465/abort.txt) with a backtrace.

**Comment by tkashkin** [comment]
Pango warnings can occur sometimes due to race conditions during UI updates, but I haven't seen any noticeable effect of it and it should not crash the app entirely.

Are you sure you don't have `G_DEBUG` env variable set to something like `fatal-criticals`?

**Comment by tkashkin** [comment]
Closing this. Reopen if that happens again.
