### ISSUE TITLE
Can't install wmp10 via winetricks

### ISSUE THREAD

**Issue by afettouhi** [tkashkin/GameHub#98]
I have Giana Sisters: Twisted Dreams in Humble Bundle library and I an trying install it via GameHub. The game itself installs just fine but for it to run it needs xact and wmp10. When I try to install wmp10 via winetricks using the menus it complains about my prefix not being 32 bit (WINEARCH) because wmp10 is only 32 bit? But I choose wine as install tool and not wine64? So I am confused here...

**Comment by tkashkin** [comment]
I have not thought about `WINEARCH`. You can try to remove existing prefix and create a new 32 bit prefix.

**Comment by afettouhi** [comment]
Yes, that works. I can install wmp10 now.

**Comment by tkashkin** [comment]
You should be able to choose WINEARCH in latest version.

**Comment by afettouhi** [comment]
Yes, I can see that now. I just build the latest git version. Many thanks for this!
